//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace INSS.ODS.Bankruptcy.API.Common.Resources.Application {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ContinueToSubmitBalanceRemainingResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ContinueToSubmitBalanceRemainingResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("INSS.ODS.Bankruptcy.API.Common.Resources.Application.ContinueToSubmitBalanceRemainingResou" +
                            "rces", typeof(ContinueToSubmitBalanceRemainingResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pay application fee.
        /// </summary>
        public static string Application_ContinueToSubmitBalanceRemaining_ContinueButton_Label {
            get {
                return ResourceManager.GetString("Application_ContinueToSubmitBalanceRemaining_ContinueButton_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You will need to pay your remaining application fee of .
        /// </summary>
        public static string Application_ContinueToSubmitBalanceRemaining_Info1 {
            get {
                return ResourceManager.GetString("Application_ContinueToSubmitBalanceRemaining_Info1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to before we submit your application..
        /// </summary>
        public static string Application_ContinueToSubmitBalanceRemaining_Info2 {
            get {
                return ResourceManager.GetString("Application_ContinueToSubmitBalanceRemaining_Info2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Continue to submit.
        /// </summary>
        public static string Application_ContinueToSubmitBalanceRemaining_PageTitle {
            get {
                return ResourceManager.GetString("Application_ContinueToSubmitBalanceRemaining_PageTitle", resourceCulture);
            }
        }
    }
}
