//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace INSS.ODS.Bankruptcy.API.Common.Resources.Application {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ForgottenApplicationNumberPostalResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ForgottenApplicationNumberPostalResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("INSS.ODS.Bankruptcy.API.Common.Resources.Application.ForgottenApplicationNumberPostalResou" +
                            "rces", typeof(ForgottenApplicationNumberPostalResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter the first line of your address.
        /// </summary>
        public static string Application_ForgottenApplicationNumberPostal_AddressLine1_Error_Empty {
            get {
                return ResourceManager.GetString("Application_ForgottenApplicationNumberPostal_AddressLine1_Error_Empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address line 1.
        /// </summary>
        public static string Application_ForgottenApplicationNumberPostal_AddressLine1_Label {
            get {
                return ResourceManager.GetString("Application_ForgottenApplicationNumberPostal_AddressLine1_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First name.
        /// </summary>
        public static string Application_ForgottenApplicationNumberPostal_FirstName_Label {
            get {
                return ResourceManager.GetString("Application_ForgottenApplicationNumberPostal_FirstName_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last name.
        /// </summary>
        public static string Application_ForgottenApplicationNumberPostal_LastName_Label {
            get {
                return ResourceManager.GetString("Application_ForgottenApplicationNumberPostal_LastName_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No application found that matches those details.
        /// </summary>
        public static string Application_ForgottenApplicationNumberPostal_No_Applicant_Error {
            get {
                return ResourceManager.GetString("Application_ForgottenApplicationNumberPostal_No_Applicant_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter your postcode.
        /// </summary>
        public static string Application_ForgottenApplicationNumberPostal_Postcode_Error_Empty {
            get {
                return ResourceManager.GetString("Application_ForgottenApplicationNumberPostal_Postcode_Error_Empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Postcode.
        /// </summary>
        public static string Application_ForgottenApplicationNumberPostal_Postcode_Label {
            get {
                return ResourceManager.GetString("Application_ForgottenApplicationNumberPostal_Postcode_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forgotten application number.
        /// </summary>
        public static string Application_ForgottenApplicationNumberPostcode_PageTitle {
            get {
                return ResourceManager.GetString("Application_ForgottenApplicationNumberPostcode_PageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter your name and the postcode of the address you gave us when you registered. We will then re-send you your application number..
        /// </summary>
        public static string Application_ForgottenApplicationNumberPostcode_Title2 {
            get {
                return ResourceManager.GetString("Application_ForgottenApplicationNumberPostcode_Title2", resourceCulture);
            }
        }
    }
}
