//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace INSS.ODS.Bankruptcy.API.Common.Resources.Application {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class SubmitApplicationResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SubmitApplicationResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("INSS.ODS.Bankruptcy.API.Common.Resources.Application.SubmitApplicationResources", typeof(SubmitApplicationResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back to application overview.
        /// </summary>
        public static string Submit_Application_Back_Label {
            get {
                return ResourceManager.GetString("Submit_Application_Back_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Submit my application.
        /// </summary>
        public static string Submit_Application_Continue_Button_Label1 {
            get {
                return ResourceManager.GetString("Submit_Application_Continue_Button_Label1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The completion status of the application could not be checked.
        /// </summary>
        public static string Submit_Application_Error_ApplicationCompletionStatusNotDetermined {
            get {
                return ResourceManager.GetString("Submit_Application_Error_ApplicationCompletionStatusNotDetermined", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The section.
        /// </summary>
        public static string Submit_Application_Error_IncompleteSectionNamePefix {
            get {
                return ResourceManager.GetString("Submit_Application_Error_IncompleteSectionNamePefix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to is not complete.
        /// </summary>
        public static string Submit_Application_Error_IncompleteSectionNameSuffix {
            get {
                return ResourceManager.GetString("Submit_Application_Error_IncompleteSectionNameSuffix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Submit application.
        /// </summary>
        public static string Submit_Application_Page_Title {
            get {
                return ResourceManager.GetString("Submit_Application_Page_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///				
        ///				&lt;div class=&quot;form-group&quot;&gt;
        ///					&lt;p&gt;You can now submit your application.&lt;/p&gt; 
        ///					&lt;p&gt;In doing so, you will be confirming several facts about yourself, your situation and your application.
        ///					Please read these below carefully before continuing.&lt;/p&gt;
        ///				&lt;/div&gt;
        ///				
        ///				&lt;div class=&quot;form-group&quot;&gt;
        ///					&lt;p&gt;By clicking submit you  are confirming that:&lt;/p&gt;
        ///					&lt;ul class=&quot;list-bullet bolder panel-body&quot;&gt;
        ///						&lt;li&gt;you are the person named in this application&lt;/li&gt;
        ///						&lt;li&gt;you are unable to pay your debts&lt;/ [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Submit_Application_Text {
            get {
                return ResourceManager.GetString("Submit_Application_Text", resourceCulture);
            }
        }
    }
}
