//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace INSS.ODS.Bankruptcy.API.Common.Resources.Employment {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class OverviewResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal OverviewResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("INSS.ODS.Bankruptcy.API.Common.Resources.Employment.OverviewResources", typeof(OverviewResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Director of a company with Ltd, PLC LLP or CIC as part of the company name (eg ABC Trading Ltd).
        /// </summary>
        public static string Employment_Overview_Director_Hint {
            get {
                return ResourceManager.GetString("Employment_Overview_Director_Hint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Have you been a director of a limited company in the last 12 months?.
        /// </summary>
        public static string Employment_Overview_Director_Label {
            get {
                return ResourceManager.GetString("Employment_Overview_Director_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Have you been employed by someone in the last 12 months?.
        /// </summary>
        public static string Employment_Overview_Employed_Label {
            get {
                return ResourceManager.GetString("Employment_Overview_Employed_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We need to know about your recent employment history..
        /// </summary>
        public static string Employment_Overview_Intro {
            get {
                return ResourceManager.GetString("Employment_Overview_Intro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This will help us better understand your financial situation..
        /// </summary>
        public static string Employment_Overview_Intro_2 {
            get {
                return ResourceManager.GetString("Employment_Overview_Intro_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Employment Summary.
        /// </summary>
        public static string Employment_Overview_PageTitle {
            get {
                return ResourceManager.GetString("Employment_Overview_PageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Partner in a business where you and at least one business partner personally share responsibility for the business (eg Smith and Johnson Estate Agents).
        /// </summary>
        public static string Employment_Overview_Partner_Hint {
            get {
                return ResourceManager.GetString("Employment_Overview_Partner_Hint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Have you been a partner in a non-limited business in the last 3 years?.
        /// </summary>
        public static string Employment_Overview_Partner_Label {
            get {
                return ResourceManager.GetString("Employment_Overview_Partner_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to For example, as a sole trader.
        /// </summary>
        public static string Employment_Overview_SelfEmployed_Hint {
            get {
                return ResourceManager.GetString("Employment_Overview_SelfEmployed_Hint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Have you been self-employed in the last 3 years?.
        /// </summary>
        public static string Employment_Overview_SelfEmployed_Label {
            get {
                return ResourceManager.GetString("Employment_Overview_SelfEmployed_Label", resourceCulture);
            }
        }
    }
}
