//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace INSS.ODS.Bankruptcy.API.Common.Resources.Vehicle {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class FinanceAgreementResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal FinanceAgreementResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("INSS.ODS.Bankruptcy.API.Common.Resources.Vehicle.FinanceAgreementResources", typeof(FinanceAgreementResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter positive value for amount .
        /// </summary>
        public static string Vehicle_FinanceAgreement_AmountOwe_Error_PositveValueOnly {
            get {
                return ResourceManager.GetString("Vehicle_FinanceAgreement_AmountOwe_Error_PositveValueOnly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter amount you still owe to the finance company.
        /// </summary>
        public static string Vehicle_FinanceAgreement_AmountOwe_Error_Required {
            get {
                return ResourceManager.GetString("Vehicle_FinanceAgreement_AmountOwe_Error_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please use the correct format, eg £120.50.
        /// </summary>
        public static string Vehicle_FinanceAgreement_AmountOwe_Error_Scale {
            get {
                return ResourceManager.GetString("Vehicle_FinanceAgreement_AmountOwe_Error_Scale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check your latest statement or contact the finance company if you’re not sure.
        /// </summary>
        public static string Vehicle_FinanceAgreement_AmountOwe_Hint {
            get {
                return ResourceManager.GetString("Vehicle_FinanceAgreement_AmountOwe_Hint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to How much does the finance company say you still owe for your vehicle?.
        /// </summary>
        public static string Vehicle_FinanceAgreement_AmountOwe_Label {
            get {
                return ResourceManager.GetString("Vehicle_FinanceAgreement_AmountOwe_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back.
        /// </summary>
        public static string Vehicle_FinanceAgreement_Back_ButtonText {
            get {
                return ResourceManager.GetString("Vehicle_FinanceAgreement_Back_ButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Continue.
        /// </summary>
        public static string Vehicle_FinanceAgreement_Button_Text {
            get {
                return ResourceManager.GetString("Vehicle_FinanceAgreement_Button_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter a date that isn&apos;t in the future.
        /// </summary>
        public static string Vehicle_FinanceAgreement_Date_Error_FutureDateNotAllowed {
            get {
                return ResourceManager.GetString("Vehicle_FinanceAgreement_Date_Error_FutureDateNotAllowed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter a agreement date that is after 01/01/1900.
        /// </summary>
        public static string Vehicle_FinanceAgreement_Date_Error_MinimumDate {
            get {
                return ResourceManager.GetString("Vehicle_FinanceAgreement_Date_Error_MinimumDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter the date the finance agreement started .
        /// </summary>
        public static string Vehicle_FinanceAgreement_Date_Error_Required {
            get {
                return ResourceManager.GetString("Vehicle_FinanceAgreement_Date_Error_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to For example, Aug 2012.
        /// </summary>
        public static string Vehicle_FinanceAgreement_Date_Hint {
            get {
                return ResourceManager.GetString("Vehicle_FinanceAgreement_Date_Hint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date the finance agreement started.
        /// </summary>
        public static string Vehicle_FinanceAgreement_Date_Label {
            get {
                return ResourceManager.GetString("Vehicle_FinanceAgreement_Date_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finance agreement details.
        /// </summary>
        public static string Vehicle_FinanceAgreement_PageTitle_Label {
            get {
                return ResourceManager.GetString("Vehicle_FinanceAgreement_PageTitle_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account or reference number length must be minimum 3 characters and maximum 20 characters.
        /// </summary>
        public static string Vehicle_FinanceAgreement_ReferenceNumber_Error_Length {
            get {
                return ResourceManager.GetString("Vehicle_FinanceAgreement_ReferenceNumber_Error_Length", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account or reference number length must be maximum 20 characters.
        /// </summary>
        public static string Vehicle_FinanceAgreement_ReferenceNumber_Error_MaxLength {
            get {
                return ResourceManager.GetString("Vehicle_FinanceAgreement_ReferenceNumber_Error_MaxLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account or reference number length must be minimum 3 characters.
        /// </summary>
        public static string Vehicle_FinanceAgreement_ReferenceNumber_Error_MinLength {
            get {
                return ResourceManager.GetString("Vehicle_FinanceAgreement_ReferenceNumber_Error_MinLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter the account or reference number.
        /// </summary>
        public static string Vehicle_FinanceAgreement_ReferenceNumber_Error_Required {
            get {
                return ResourceManager.GetString("Vehicle_FinanceAgreement_ReferenceNumber_Error_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Leave blank if you don&apos;t have one.
        /// </summary>
        public static string Vehicle_FinanceAgreement_ReferenceNumber_Hint {
            get {
                return ResourceManager.GetString("Vehicle_FinanceAgreement_ReferenceNumber_Hint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account or reference number.
        /// </summary>
        public static string Vehicle_FinanceAgreement_ReferenceNumber_Label {
            get {
                return ResourceManager.GetString("Vehicle_FinanceAgreement_ReferenceNumber_Label", resourceCulture);
            }
        }
    }
}
