//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace INSS.ODS.Bankruptcy.API.Common.Resources.Vehicle {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class VehicleResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal VehicleResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("INSS.ODS.Bankruptcy.API.Common.Resources.Vehicle.VehicleResources", typeof(VehicleResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add vehicle.
        /// </summary>
        public static string Vehicle_Add_Vehicle_Label {
            get {
                return ResourceManager.GetString("Vehicle_Add_Vehicle_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add another vehicle.
        /// </summary>
        public static string Vehicle_Add_Vehicle_Label_Alt {
            get {
                return ResourceManager.GetString("Vehicle_Add_Vehicle_Label_Alt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back.
        /// </summary>
        public static string Vehicle_Vehicle_Back_ButtonText {
            get {
                return ResourceManager.GetString("Vehicle_Vehicle_Back_ButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Make.
        /// </summary>
        public static string Vehicle_Vehicle_Make_Label {
            get {
                return ResourceManager.GetString("Vehicle_Vehicle_Make_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter the make and model of the vehicle..
        /// </summary>
        public static string Vehicle_Vehicle_MakeModel_Error_AnyOneFieldRequired {
            get {
                return ResourceManager.GetString("Vehicle_Vehicle_MakeModel_Error_AnyOneFieldRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Model.
        /// </summary>
        public static string Vehicle_Vehicle_Model_Label {
            get {
                return ResourceManager.GetString("Vehicle_Vehicle_Model_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select the nature of your interest in the vehicle..
        /// </summary>
        public static string Vehicle_Vehicle_NatureInterestOfVehicle_Error_Required {
            get {
                return ResourceManager.GetString("Vehicle_Vehicle_NatureInterestOfVehicle_Error_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vehicle details.
        /// </summary>
        public static string Vehicle_Vehicle_PageTitle {
            get {
                return ResourceManager.GetString("Vehicle_Vehicle_PageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please check the registration number. Your answers can only use letters and numbers..
        /// </summary>
        public static string Vehicle_Vehicle_RegistrationNumber_Error_AlphaNumericOnly {
            get {
                return ResourceManager.GetString("Vehicle_Vehicle_RegistrationNumber_Error_AlphaNumericOnly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The vehicle registration number must be between 1 and 20 characters long..
        /// </summary>
        public static string Vehicle_Vehicle_RegistrationNumber_Error_Length {
            get {
                return ResourceManager.GetString("Vehicle_Vehicle_RegistrationNumber_Error_Length", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter the vehicle registration number..
        /// </summary>
        public static string Vehicle_Vehicle_RegistrationNumber_Error_Required {
            get {
                return ResourceManager.GetString("Vehicle_Vehicle_RegistrationNumber_Error_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registration number.
        /// </summary>
        public static string Vehicle_Vehicle_RegistrationNumber_Label {
            get {
                return ResourceManager.GetString("Vehicle_Vehicle_RegistrationNumber_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I don&apos;t own it, but I use it on a regular basis.
        /// </summary>
        public static string Vehicle_Vehicle_VehicleNatureOfInterest_JustUseRegularly {
            get {
                return ResourceManager.GetString("Vehicle_Vehicle_VehicleNatureOfInterest_JustUseRegularly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What&apos;s the nature of your interest in the vehicle?.
        /// </summary>
        public static string Vehicle_Vehicle_VehicleNatureOfInterest_Label {
            get {
                return ResourceManager.GetString("Vehicle_Vehicle_VehicleNatureOfInterest_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to It&apos;s a motability scheme vehicle.
        /// </summary>
        public static string Vehicle_Vehicle_VehicleNatureOfInterest_MotabilityScheme {
            get {
                return ResourceManager.GetString("Vehicle_Vehicle_VehicleNatureOfInterest_MotabilityScheme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I currently own it (including on finance).
        /// </summary>
        public static string Vehicle_Vehicle_VehicleNatureOfInterest_Owner {
            get {
                return ResourceManager.GetString("Vehicle_Vehicle_VehicleNatureOfInterest_Owner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I sold/disposed of it in the last 12 months.
        /// </summary>
        public static string Vehicle_Vehicle_VehicleNatureOfInterest_Sold {
            get {
                return ResourceManager.GetString("Vehicle_Vehicle_VehicleNatureOfInterest_Sold", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Car.
        /// </summary>
        public static string Vehicle_Vehicle_VehicleType_Car {
            get {
                return ResourceManager.GetString("Vehicle_Vehicle_VehicleType_Car", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select a vehicle type..
        /// </summary>
        public static string Vehicle_Vehicle_VehicleType_Error_Required {
            get {
                return ResourceManager.GetString("Vehicle_Vehicle_VehicleType_Error_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type of vehicle.
        /// </summary>
        public static string Vehicle_Vehicle_VehicleType_Label {
            get {
                return ResourceManager.GetString("Vehicle_Vehicle_VehicleType_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Motorcycle.
        /// </summary>
        public static string Vehicle_Vehicle_VehicleType_MotorCycle {
            get {
                return ResourceManager.GetString("Vehicle_Vehicle_VehicleType_MotorCycle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Other.
        /// </summary>
        public static string Vehicle_Vehicle_VehicleType_Other {
            get {
                return ResourceManager.GetString("Vehicle_Vehicle_VehicleType_Other", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Van.
        /// </summary>
        public static string Vehicle_Vehicle_VehicleType_Van {
            get {
                return ResourceManager.GetString("Vehicle_Vehicle_VehicleType_Van", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The vehicle type other field must be between 3 and 60 characters long..
        /// </summary>
        public static string Vehicle_Vehicle_VehicleTypeOther_Error_Length {
            get {
                return ResourceManager.GetString("Vehicle_Vehicle_VehicleTypeOther_Error_Length", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter value for the vehicle type other field..
        /// </summary>
        public static string Vehicle_Vehicle_VehicleTypeOther_Error_Required {
            get {
                return ResourceManager.GetString("Vehicle_Vehicle_VehicleTypeOther_Error_Required", resourceCulture);
            }
        }
    }
}
