//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace INSS.ODS.Bankruptcy.API.Common.Resources.Vehicle {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class VehicleSummaryResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal VehicleSummaryResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("INSS.ODS.Bankruptcy.API.Common.Resources.Vehicle.VehicleSummaryResources", typeof(VehicleSummaryResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add vehicle.
        /// </summary>
        public static string Vehicle_VehicleSummary_Add_ButtonText {
            get {
                return ResourceManager.GetString("Vehicle_VehicleSummary_Add_ButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add another vehicle.
        /// </summary>
        public static string Vehicle_VehicleSummary_Add_ButtonText_Alt {
            get {
                return ResourceManager.GetString("Vehicle_VehicleSummary_Add_ButtonText_Alt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back.
        /// </summary>
        public static string Vehicle_VehicleSummary_Back_ButtonText {
            get {
                return ResourceManager.GetString("Vehicle_VehicleSummary_Back_ButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Continue - I have added all my vehicles.
        /// </summary>
        public static string Vehicle_VehicleSummary_Continue_ButtonText {
            get {
                return ResourceManager.GetString("Vehicle_VehicleSummary_Continue_ButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Continue - I have no vehicles to add.
        /// </summary>
        public static string Vehicle_VehicleSummary_Continue_ButtonText_NoVehicles {
            get {
                return ResourceManager.GetString("Vehicle_VehicleSummary_Continue_ButtonText_NoVehicles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Once your bankruptcy order is made, your application will be passed onto an insolvency official for consideration. They will review your personal circumstances and determine which vehicles (if any) could reasonably be sold to help pay your debts.
        ///
        ///If you need your vehicle, you will usually be allowed to keep it.
        ///
        ///We also won&apos;t take any action against vehicles you use but don&apos;t own.​.
        /// </summary>
        public static string Vehicle_VehicleSummary_FindOutMoreDesc_Label {
            get {
                return ResourceManager.GetString("Vehicle_VehicleSummary_FindOutMoreDesc_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Make.
        /// </summary>
        public static string Vehicle_VehicleSummary_Make_Label {
            get {
                return ResourceManager.GetString("Vehicle_VehicleSummary_Make_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter either make or model of the vehicle.
        /// </summary>
        public static string Vehicle_VehicleSummary_MakeModel_Error_Required {
            get {
                return ResourceManager.GetString("Vehicle_VehicleSummary_MakeModel_Error_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Model.
        /// </summary>
        public static string Vehicle_VehicleSummary_Model_Label {
            get {
                return ResourceManager.GetString("Vehicle_VehicleSummary_Model_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vehicles.
        /// </summary>
        public static string Vehicle_VehicleSummary_Page_Title {
            get {
                return ResourceManager.GetString("Vehicle_VehicleSummary_Page_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;p&gt;We need to know about any vehicles you own and about any vehicles you regularly use. &lt;/p&gt;
        ///&lt;p&gt;Telling us about a vehicle doesn’t necessarily mean it will be taken away from you. &lt;/p&gt;
        ///&lt;p&gt;If you need your vehicle, you will usually be allowed to keep it. &lt;/p&gt;.
        /// </summary>
        public static string Vehicle_VehicleSummary_PageWithoutTable_Intro {
            get {
                return ResourceManager.GetString("Vehicle_VehicleSummary_PageWithoutTable_Intro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;p&gt;The table above summarises the vehicles you have told us about. &lt;/p&gt;
        ///&lt;p&gt;We need to know about any other vehicle you own and about any other vehicles you regularly use. &lt;/p&gt;.
        /// </summary>
        public static string Vehicle_VehicleSummary_PageWithTable_Intro {
            get {
                return ResourceManager.GetString("Vehicle_VehicleSummary_PageWithTable_Intro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter the make and model of the vehicle.
        /// </summary>
        public static string Vehicle_VehicleSummary_Table_Header {
            get {
                return ResourceManager.GetString("Vehicle_VehicleSummary_Table_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to For example, Ford Mondeo. You can add more vehicles later..
        /// </summary>
        public static string Vehicle_VehicleSummary_TableHeader_Hint {
            get {
                return ResourceManager.GetString("Vehicle_VehicleSummary_TableHeader_Hint", resourceCulture);
            }
        }
    }
}
