// ------------------------------------------------------------------------------
//  <auto-generated>
//    Generated by Xsd2Code++. Version 4.2.0.15
//  </auto-generated>
// ------------------------------------------------------------------------------

using System;
using System.Xml.Serialization;

#pragma warning disable
namespace INSS.ODS.Bankruptcy.API.Common.Models.DRO.Export
{
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
[Serializable()]
[XmlType(AnonymousType=true, Namespace="http://tempuri.org/DROApplication.xs")]
public enum AddressCountry
{
    
    /// <remarks/>
    England,
    
    /// <remarks/>
    Wales,
    
    /// <remarks/>
    Afghanistan,
    
    /// <remarks/>
    Albania,
    
    /// <remarks/>
    Algeria,
    
    /// <remarks/>
    [XmlEnum("American Samoa")]
    AmericanSamoa,
    
    /// <remarks/>
    Andorra,
    
    /// <remarks/>
    Angola,
    
    /// <remarks/>
    [XmlEnum("Antigua and Barbuda")]
    AntiguaandBarbuda,
    
    /// <remarks/>
    Argentina,
    
    /// <remarks/>
    Armenia,
    
    /// <remarks/>
    Aruba,
    
    /// <remarks/>
    Australia,
    
    /// <remarks/>
    Austria,
    
    /// <remarks/>
    Azerbaijan,
    
    /// <remarks/>
    [XmlEnum("Bahamas, The")]
    BahamasThe,
    
    /// <remarks/>
    Bahrain,
    
    /// <remarks/>
    Bangladesh,
    
    /// <remarks/>
    Barbados,
    
    /// <remarks/>
    Belarus,
    
    /// <remarks/>
    Belgium,
    
    /// <remarks/>
    Belize,
    
    /// <remarks/>
    Benin,
    
    /// <remarks/>
    Bermuda,
    
    /// <remarks/>
    Bhutan,
    
    /// <remarks/>
    Bolivia,
    
    /// <remarks/>
    [XmlEnum("Bosnia and Herzegovina")]
    BosniaandHerzegovina,
    
    /// <remarks/>
    Botswana,
    
    /// <remarks/>
    Brazil,
    
    /// <remarks/>
    [XmlEnum("Brunei Darussalam")]
    BruneiDarussalam,
    
    /// <remarks/>
    Bulgaria,
    
    /// <remarks/>
    [XmlEnum("Burkina Faso")]
    BurkinaFaso,
    
    /// <remarks/>
    Burundi,
    
    /// <remarks/>
    Cambodia,
    
    /// <remarks/>
    Cameroon,
    
    /// <remarks/>
    Canada,
    
    /// <remarks/>
    [XmlEnum("Cape Verde")]
    CapeVerde,
    
    /// <remarks/>
    [XmlEnum("Cayman Islands")]
    CaymanIslands,
    
    /// <remarks/>
    [XmlEnum("Central African Republic")]
    CentralAfricanRepublic,
    
    /// <remarks/>
    Chad,
    
    /// <remarks/>
    [XmlEnum("Channel Islands")]
    ChannelIslands,
    
    /// <remarks/>
    Chile,
    
    /// <remarks/>
    China,
    
    /// <remarks/>
    Colombia,
    
    /// <remarks/>
    Comoros,
    
    /// <remarks/>
    [XmlEnum("Congo, Dem. Rep.")]
    CongoDemRep,
    
    /// <remarks/>
    [XmlEnum("Congo, Rep.")]
    CongoRep,
    
    /// <remarks/>
    [XmlEnum("Costa Rica")]
    CostaRica,
    
    /// <remarks/>
    [XmlEnum("Côte d\'Ivoire")]
    CôtedIvoire,
    
    /// <remarks/>
    Croatia,
    
    /// <remarks/>
    Cuba,
    
    /// <remarks/>
    Cyprus,
    
    /// <remarks/>
    [XmlEnum("Czech Republic")]
    CzechRepublic,
    
    /// <remarks/>
    Denmark,
    
    /// <remarks/>
    Djibouti,
    
    /// <remarks/>
    Dominica,
    
    /// <remarks/>
    [XmlEnum("Dominican Republic")]
    DominicanRepublic,
    
    /// <remarks/>
    Ecuador,
    
    /// <remarks/>
    [XmlEnum("Egypt, Arab Rep.")]
    EgyptArabRep,
    
    /// <remarks/>
    [XmlEnum("El Salvador")]
    ElSalvador,
    
    /// <remarks/>
    [XmlEnum("Equatorial Guinea")]
    EquatorialGuinea,
    
    /// <remarks/>
    Eritrea,
    
    /// <remarks/>
    Estonia,
    
    /// <remarks/>
    Ethiopia,
    
    /// <remarks/>
    [XmlEnum("Faeroe Islands")]
    FaeroeIslands,
    
    /// <remarks/>
    Fiji,
    
    /// <remarks/>
    Finland,
    
    /// <remarks/>
    France,
    
    /// <remarks/>
    [XmlEnum("French Polynesia")]
    FrenchPolynesia,
    
    /// <remarks/>
    Gabon,
    
    /// <remarks/>
    [XmlEnum("Gambia, The")]
    GambiaThe,
    
    /// <remarks/>
    Georgia,
    
    /// <remarks/>
    Germany,
    
    /// <remarks/>
    Ghana,
    
    /// <remarks/>
    Greece,
    
    /// <remarks/>
    Greenland,
    
    /// <remarks/>
    Grenada,
    
    /// <remarks/>
    Guam,
    
    /// <remarks/>
    Guatemala,
    
    /// <remarks/>
    Guinea,
    
    /// <remarks/>
    [XmlEnum("Guinea-Bissau")]
    GuineaBissau,
    
    /// <remarks/>
    Guyana,
    
    /// <remarks/>
    Haiti,
    
    /// <remarks/>
    Honduras,
    
    /// <remarks/>
    [XmlEnum("Hong Kong, China")]
    HongKongChina,
    
    /// <remarks/>
    Hungary,
    
    /// <remarks/>
    Iceland,
    
    /// <remarks/>
    India,
    
    /// <remarks/>
    Indonesia,
    
    /// <remarks/>
    [XmlEnum("Iran, Islamic Rep.")]
    IranIslamicRep,
    
    /// <remarks/>
    Iraq,
    
    /// <remarks/>
    Ireland,
    
    /// <remarks/>
    [XmlEnum("Isle of Man")]
    IsleofMan,
    
    /// <remarks/>
    Israel,
    
    /// <remarks/>
    Italy,
    
    /// <remarks/>
    Jamaica,
    
    /// <remarks/>
    Japan,
    
    /// <remarks/>
    Jordan,
    
    /// <remarks/>
    Kazakhstan,
    
    /// <remarks/>
    Kenya,
    
    /// <remarks/>
    Kiribati,
    
    /// <remarks/>
    [XmlEnum("Korea, Dem. Rep.")]
    KoreaDemRep,
    
    /// <remarks/>
    [XmlEnum("Korea, Rep.")]
    KoreaRep,
    
    /// <remarks/>
    Kuwait,
    
    /// <remarks/>
    [XmlEnum("Kyrgyz Republic")]
    KyrgyzRepublic,
    
    /// <remarks/>
    [XmlEnum("Lao PDR")]
    LaoPDR,
    
    /// <remarks/>
    Latvia,
    
    /// <remarks/>
    Lebanon,
    
    /// <remarks/>
    Lesotho,
    
    /// <remarks/>
    Liberia,
    
    /// <remarks/>
    Libya,
    
    /// <remarks/>
    Liechtenstein,
    
    /// <remarks/>
    Lithuania,
    
    /// <remarks/>
    Luxembourg,
    
    /// <remarks/>
    [XmlEnum("Macao, China")]
    MacaoChina,
    
    /// <remarks/>
    [XmlEnum("Macedonia, FYR")]
    MacedoniaFYR,
    
    /// <remarks/>
    Madagascar,
    
    /// <remarks/>
    Malawi,
    
    /// <remarks/>
    Malaysia,
    
    /// <remarks/>
    Maldives,
    
    /// <remarks/>
    Mali,
    
    /// <remarks/>
    Malta,
    
    /// <remarks/>
    [XmlEnum("Marshall Islands")]
    MarshallIslands,
    
    /// <remarks/>
    Mauritania,
    
    /// <remarks/>
    Mauritius,
    
    /// <remarks/>
    Mayotte,
    
    /// <remarks/>
    Mexico,
    
    /// <remarks/>
    [XmlEnum("Micronesia, Fed. Sts.")]
    MicronesiaFedSts,
    
    /// <remarks/>
    Moldova,
    
    /// <remarks/>
    Monaco,
    
    /// <remarks/>
    Mongolia,
    
    /// <remarks/>
    Montenegro,
    
    /// <remarks/>
    Morocco,
    
    /// <remarks/>
    Mozambique,
    
    /// <remarks/>
    Myanmar,
    
    /// <remarks/>
    Namibia,
    
    /// <remarks/>
    Nepal,
    
    /// <remarks/>
    Netherlands,
    
    /// <remarks/>
    [XmlEnum("Netherlands Antilles")]
    NetherlandsAntilles,
    
    /// <remarks/>
    [XmlEnum("New Caledonia")]
    NewCaledonia,
    
    /// <remarks/>
    [XmlEnum("New Zealand")]
    NewZealand,
    
    /// <remarks/>
    Nicaragua,
    
    /// <remarks/>
    Niger,
    
    /// <remarks/>
    Nigeria,
    
    /// <remarks/>
    [XmlEnum("Northern Ireland")]
    NorthernIreland,
    
    /// <remarks/>
    [XmlEnum("Northern Mariana Islands")]
    NorthernMarianaIslands,
    
    /// <remarks/>
    Norway,
    
    /// <remarks/>
    Oman,
    
    /// <remarks/>
    Pakistan,
    
    /// <remarks/>
    Palau,
    
    /// <remarks/>
    Panama,
    
    /// <remarks/>
    [XmlEnum("Papua New Guinea")]
    PapuaNewGuinea,
    
    /// <remarks/>
    Paraguay,
    
    /// <remarks/>
    Peru,
    
    /// <remarks/>
    Philippines,
    
    /// <remarks/>
    Poland,
    
    /// <remarks/>
    Portugal,
    
    /// <remarks/>
    [XmlEnum("Puerto Rico")]
    PuertoRico,
    
    /// <remarks/>
    Qatar,
    
    /// <remarks/>
    Romania,
    
    /// <remarks/>
    [XmlEnum("Russian Federation")]
    RussianFederation,
    
    /// <remarks/>
    Rwanda,
    
    /// <remarks/>
    Samoa,
    
    /// <remarks/>
    [XmlEnum("San Marino")]
    SanMarino,
    
    /// <remarks/>
    [XmlEnum("São Tomé and Principe")]
    SãoToméandPrincipe,
    
    /// <remarks/>
    [XmlEnum("Saudi Arabia")]
    SaudiArabia,
    
    /// <remarks/>
    Scotland,
    
    /// <remarks/>
    Senegal,
    
    /// <remarks/>
    Serbia,
    
    /// <remarks/>
    Seychelles,
    
    /// <remarks/>
    [XmlEnum("Sierra Leone")]
    SierraLeone,
    
    /// <remarks/>
    Singapore,
    
    /// <remarks/>
    [XmlEnum("Slovak Republic")]
    SlovakRepublic,
    
    /// <remarks/>
    Slovenia,
    
    /// <remarks/>
    [XmlEnum("Solomon Islands")]
    SolomonIslands,
    
    /// <remarks/>
    Somalia,
    
    /// <remarks/>
    [XmlEnum("South Africa")]
    SouthAfrica,
    
    /// <remarks/>
    Spain,
    
    /// <remarks/>
    [XmlEnum("Sri Lanka")]
    SriLanka,
    
    /// <remarks/>
    [XmlEnum("St. Kitts and Nevis")]
    StKittsandNevis,
    
    /// <remarks/>
    [XmlEnum("St. Lucia")]
    StLucia,
    
    /// <remarks/>
    [XmlEnum("St. Vincent and the Grenadines")]
    StVincentandtheGrenadines,
    
    /// <remarks/>
    Sudan,
    
    /// <remarks/>
    Suriname,
    
    /// <remarks/>
    Swaziland,
    
    /// <remarks/>
    Sweden,
    
    /// <remarks/>
    Switzerland,
    
    /// <remarks/>
    [XmlEnum("Syrian Arab Republic")]
    SyrianArabRepublic,
    
    /// <remarks/>
    Tajikistan,
    
    /// <remarks/>
    Tanzania,
    
    /// <remarks/>
    Thailand,
    
    /// <remarks/>
    [XmlEnum("Timor-Leste")]
    TimorLeste,
    
    /// <remarks/>
    Togo,
    
    /// <remarks/>
    Tonga,
    
    /// <remarks/>
    [XmlEnum("Trinidad and Tobago")]
    TrinidadandTobago,
    
    /// <remarks/>
    Tunisia,
    
    /// <remarks/>
    Turkey,
    
    /// <remarks/>
    Turkmenistan,
    
    /// <remarks/>
    Uganda,
    
    /// <remarks/>
    Ukraine,
    
    /// <remarks/>
    [XmlEnum("United Arab Emirates")]
    UnitedArabEmirates,
    
    /// <remarks/>
    [XmlEnum("United Kingdom")]
    UnitedKingdom,
    
    /// <remarks/>
    [XmlEnum("United States")]
    UnitedStates,
    
    /// <remarks/>
    Uruguay,
    
    /// <remarks/>
    Uzbekistan,
    
    /// <remarks/>
    Vanuatu,
    
    /// <remarks/>
    [XmlEnum("Venezuela, RB")]
    VenezuelaRB,
    
    /// <remarks/>
    Vietnam,
    
    /// <remarks/>
    [XmlEnum("Virgin Islands (U.S.)")]
    VirginIslandsUS,
    
    /// <remarks/>
    Palestine,
    
    /// <remarks/>
    [XmlEnum("Yemen, Rep.")]
    YemenRep,
    
    /// <remarks/>
    Zambia,
    
    /// <remarks/>
    Zimbabwe,
    
    /// <remarks/>
    Jersey,
    
    /// <remarks/>
    Guernsey,
}
}
#pragma warning restore
