// ------------------------------------------------------------------------------
//  <auto-generated>
//    Generated by Xsd2Code++. Version 4.2.0.15
//  </auto-generated>
// ------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Diagnostics;
using System.Xml.Serialization;

#pragma warning disable
namespace INSS.ODS.Bankruptcy.API.Common.Models.DRO.Export
{
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
[Serializable()]
[DebuggerStepThrough()]
[DesignerCategory("code")]
[XmlType(AnonymousType=true, Namespace="http://tempuri.org/DROApplication.xs")]
public partial class DROApplicationCreditor
{
    
    private DROApplicationCreditorOrganisationType _organisationType;
    
    private string _creditorName;
    
    private DROAddress _creditorAddress;
    
    private System.Nullable<decimal> _amount;
    
    private string _accountReference;
    
    private System.Nullable<bool> _securedCreditor;
    
    private string _itemSecured;
    
    private System.Nullable<decimal> _securedValue;
    
    private System.Nullable<bool> _earningsOrder;
    
    private string _earningsOrderDetails;
    
    private System.Nullable<decimal> _earningsOrderAmount;
    
    private System.Nullable<bool> _excludedDebt;

    private System.Nullable<bool> _unableToTraceAddress;
    
    public DROApplicationCreditor()
    {
        this._creditorAddress = new DROAddress();
    }
    
    public DROApplicationCreditorOrganisationType OrganisationType
    {
        get
        {
            return this._organisationType;
        }
        set
        {
            this._organisationType = value;
        }
    }
    
    public string CreditorName
    {
        get
        {
            return this._creditorName;
        }
        set
        {
            this._creditorName = value;
        }
    }
    
    [XmlElement(IsNullable=true)]
    public DROAddress CreditorAddress
    {
        get
        {
            return this._creditorAddress;
        }
        set
        {
            this._creditorAddress = value;
        }
    }
    
    [XmlElement(IsNullable=true)]
    public System.Nullable<decimal> Amount
    {
        get
        {
            return this._amount;
        }
        set
        {
            this._amount = value;
        }
    }
    
    [XmlElement(IsNullable=true)]
    public string AccountReference
    {
        get
        {
            return this._accountReference;
        }
        set
        {
            this._accountReference = value;
        }
    }
    
    [XmlElement(IsNullable=true)]
    public System.Nullable<bool> SecuredCreditor
    {
        get
        {
            return this._securedCreditor;
        }
        set
        {
            this._securedCreditor = value;
        }
    }
    
    [XmlElement(IsNullable=true)]
    public string ItemSecured
    {
        get
        {
            return this._itemSecured;
        }
        set
        {
            this._itemSecured = value;
        }
    }
    
    [XmlElement(IsNullable=true)]
    public System.Nullable<decimal> SecuredValue
    {
        get
        {
            return this._securedValue;
        }
        set
        {
            this._securedValue = value;
        }
    }
    
    [XmlElement(IsNullable=true)]
    public System.Nullable<bool> EarningsOrder
    {
        get
        {
            return this._earningsOrder;
        }
        set
        {
            this._earningsOrder = value;
        }
    }
    
    [XmlElement(IsNullable=true)]
    public string EarningsOrderDetails
    {
        get
        {
            return this._earningsOrderDetails;
        }
        set
        {
            this._earningsOrderDetails = value;
        }
    }
    
    [XmlElement(IsNullable=true)]
    public System.Nullable<decimal> EarningsOrderAmount
    {
        get
        {
            return this._earningsOrderAmount;
        }
        set
        {
            this._earningsOrderAmount = value;
        }
    }
    
    [XmlElement(IsNullable=true)]
    public System.Nullable<bool> ExcludedDebt
    {
        get
        {
            return this._excludedDebt;
        }
        set
        {
            this._excludedDebt = value;
        }
    }

    [XmlElement(IsNullable = false)]
        public System.Nullable<bool> UnableToTraceAddress
        {
            get
            {
                return this._unableToTraceAddress;
            }
            set
            {
                this._unableToTraceAddress = value;
            }
        }
    }
}
#pragma warning restore
