// ------------------------------------------------------------------------------
//  <auto-generated>
//    Generated by Xsd2Code++. Version 4.2.0.15
//  </auto-generated>
// ------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Diagnostics;
using System.Xml.Serialization;

#pragma warning disable
namespace INSS.ODS.Bankruptcy.API.Common.Models.DRO.Export
{
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
[Serializable()]
[DebuggerStepThrough()]
[DesignerCategory("code")]
[XmlType(AnonymousType=true, Namespace="http://tempuri.org/DROApplication.xs")]
public partial class DROApplicationInsolvencyHistoryDebtManagmentPlan
{
    
    private string _organisationName;
    
    private string _organisationReference;
    
    private System.Nullable<System.DateTime> _dateStarted;
    
    private DROAddress _organisationAddress;
    
    public DROApplicationInsolvencyHistoryDebtManagmentPlan()
    {
        this._organisationAddress = new DROAddress();
    }
    
    [XmlElement(IsNullable=true)]
    public string OrganisationName
    {
        get
        {
            return this._organisationName;
        }
        set
        {
            this._organisationName = value;
        }
    }
    
    [XmlElement(IsNullable=true)]
    public string OrganisationReference
    {
        get
        {
            return this._organisationReference;
        }
        set
        {
            this._organisationReference = value;
        }
    }
    
    [XmlElement(DataType="date", IsNullable=true)]
    public System.Nullable<System.DateTime> DateStarted
    {
        get
        {
            return this._dateStarted;
        }
        set
        {
            this._dateStarted = value;
        }
    }
    
    [XmlElement(IsNullable=true)]
    public DROAddress OrganisationAddress
    {
        get
        {
            return this._organisationAddress;
        }
        set
        {
            this._organisationAddress = value;
        }
    }
}
}
#pragma warning restore
