// ------------------------------------------------------------------------------
//  <auto-generated>
//    Generated by Xsd2Code++. Version 4.2.0.15
//  </auto-generated>
// ------------------------------------------------------------------------------

using System;
using System.Xml.Serialization;

#pragma warning disable
namespace INSS.ODS.Bankruptcy.API.Common.Models.DRO.Export
{
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
[Serializable()]
[XmlType(AnonymousType=true, Namespace="http://tempuri.org/DROApplication.xs")]
public enum DROApplicationInsolvencyHistoryCurrentFormalInsolvencyProceedingInsolvencyProceeding
{
    
    /// <remarks/>
    [XmlEnum("Undischarged Bankrupt")]
    UndischargedBankrupt,
    
    /// <remarks/>
    [XmlEnum("Subject to an Interim Order")]
    SubjecttoanInterimOrder,
    
    /// <remarks/>
    [XmlEnum("Subject to an IVA")]
    SubjecttoanIVA,
    
    /// <remarks/>
    [XmlEnum("Subject to a BRO")]
    SubjecttoaBRO,
    
    /// <remarks/>
    [XmlEnum("Subject to a DRRO")]
    SubjecttoaDRRO,
    
    /// <remarks/>
    [XmlEnum("Subject to a DRO")]
    SubjecttoaDRO,
}
}
#pragma warning restore
