// ------------------------------------------------------------------------------
//  <auto-generated>
//    Generated by Xsd2Code++. Version 4.2.0.15
//  </auto-generated>
// ------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Diagnostics;
using System.Xml.Serialization;

#pragma warning disable
namespace INSS.ODS.Bankruptcy.API.Common.Models.DRO.Export
{
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
[Serializable()]
[DebuggerStepThrough()]
[DesignerCategory("code")]
[XmlType(AnonymousType=true, Namespace="http://tempuri.org/DROApplication.xs")]
public partial class DROApplicationEmploymentDetail
{
    
    private DROApplicationEmploymentDetailOccupationType _occupationType;
    
    private List<DROApplicationEmploymentDetailEmployer> _employer;
    
    private List<DROApplicationEmploymentDetailOwnBusinessDetail> _ownBusinessDetail;
    
    private List<DROApplicationEmploymentDetailPreviousTrading> _previousTrading;
    
    public DROApplicationEmploymentDetail()
    {
        this._previousTrading = new List<DROApplicationEmploymentDetailPreviousTrading>();
        this._ownBusinessDetail = new List<DROApplicationEmploymentDetailOwnBusinessDetail>();
        this._employer = new List<DROApplicationEmploymentDetailEmployer>();
    }
    
    public DROApplicationEmploymentDetailOccupationType OccupationType
    {
        get
        {
            return this._occupationType;
        }
        set
        {
            this._occupationType = value;
        }
    }
    
    [XmlElement("Employer")]
    public List<DROApplicationEmploymentDetailEmployer> Employer
    {
        get
        {
            return this._employer;
        }
        set
        {
            this._employer = value;
        }
    }
    
    [XmlElement("OwnBusinessDetail")]
    public List<DROApplicationEmploymentDetailOwnBusinessDetail> OwnBusinessDetail
    {
        get
        {
            return this._ownBusinessDetail;
        }
        set
        {
            this._ownBusinessDetail = value;
        }
    }
    
    [XmlElement("PreviousTrading")]
    public List<DROApplicationEmploymentDetailPreviousTrading> PreviousTrading
    {
        get
        {
            return this._previousTrading;
        }
        set
        {
            this._previousTrading = value;
        }
    }
}
}
#pragma warning restore
