// ------------------------------------------------------------------------------
//  <auto-generated>
//    Generated by Xsd2Code++. Version 4.2.0.15
//  </auto-generated>
// ------------------------------------------------------------------------------

using System;
using System.Xml.Serialization;

#pragma warning disable
namespace INSS.ODS.Bankruptcy.API.Common.Models.DRO.Export
{
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
[Serializable()]
[XmlType(AnonymousType=true, Namespace="http://tempuri.org/DROApplication.xs")]
public enum DROApplicationInsolvencyHistoryPreviousInsolvencyInsolvencyProcedure
{
    
    /// <remarks/>
    IVA,
    
    /// <remarks/>
    [XmlEnum("Administration Order")]
    AdministrationOrder,
    
    /// <remarks/>
    [XmlEnum("Debt Relief Order")]
    DebtReliefOrder,
    
    /// <remarks/>
    Bankruptcy,
    
    /// <remarks/>
    [XmlEnum("Bankruptcy Restrictions Order")]
    BankruptcyRestrictionsOrder,
    
    /// <remarks/>
    [XmlEnum("Debt Relief Restrictions Order")]
    DebtReliefRestrictionsOrder,
    
    /// <remarks/>
    [XmlEnum("Enforcement Order")]
    EnforcementOrder,
}
}
#pragma warning restore
