// ------------------------------------------------------------------------------
//  <auto-generated>
//    Generated by Xsd2Code++. Version 4.2.0.15
//  </auto-generated>
// ------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Diagnostics;
using System.Xml.Serialization;

#pragma warning disable
namespace INSS.ODS.Bankruptcy.API.Common.Models.DRO.Export
{
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
[Serializable()]
[DebuggerStepThrough()]
[DesignerCategory("code")]
[XmlType(AnonymousType=true, Namespace="http://tempuri.org/DROApplication.xs")]
public partial class DROApplicationAssetDetail
{
    
    private System.Nullable<decimal> _cashInHand;
    
    private System.Nullable<decimal> _cashAtBank;
    
    private System.Nullable<decimal> _moneyOwed;
    
    private string _toolsTradeDetails;
    
    private System.Nullable<bool> _leaseholdProperty;
    
    private System.Nullable<decimal> _propertyValue;
    
    private string _commentary;
    
    private List<DROApplicationAssetDetailRealisableAsset> _realisableAsset;
    
    private DROApplicationAssetDetailMotorVehicle _motorVehicle;
    
    public DROApplicationAssetDetail()
    {
        this._motorVehicle = new DROApplicationAssetDetailMotorVehicle();
        this._realisableAsset = new List<DROApplicationAssetDetailRealisableAsset>();
    }
    
    [XmlElement(IsNullable=true)]
    public System.Nullable<decimal> CashInHand
    {
        get
        {
            return this._cashInHand;
        }
        set
        {
            this._cashInHand = value;
        }
    }
    
    [XmlElement(IsNullable=true)]
    public System.Nullable<decimal> CashAtBank
    {
        get
        {
            return this._cashAtBank;
        }
        set
        {
            this._cashAtBank = value;
        }
    }
    
    [XmlElement(IsNullable=true)]
    public System.Nullable<decimal> MoneyOwed
    {
        get
        {
            return this._moneyOwed;
        }
        set
        {
            this._moneyOwed = value;
        }
    }
    
    [XmlElement(IsNullable=true)]
    public string ToolsTradeDetails
    {
        get
        {
            return this._toolsTradeDetails;
        }
        set
        {
            this._toolsTradeDetails = value;
        }
    }
    
    [XmlElement(IsNullable=true)]
    public System.Nullable<bool> LeaseholdProperty
    {
        get
        {
            return this._leaseholdProperty;
        }
        set
        {
            this._leaseholdProperty = value;
        }
    }
    
    [XmlElement(IsNullable=true)]
    public System.Nullable<decimal> PropertyValue
    {
        get
        {
            return this._propertyValue;
        }
        set
        {
            this._propertyValue = value;
        }
    }
    
    [XmlElement(IsNullable=true)]
    public string Commentary
    {
        get
        {
            return this._commentary;
        }
        set
        {
            this._commentary = value;
        }
    }
    
    [XmlElement("RealisableAsset")]
    public List<DROApplicationAssetDetailRealisableAsset> RealisableAsset
    {
        get
        {
            return this._realisableAsset;
        }
        set
        {
            this._realisableAsset = value;
        }
    }
    
    [XmlElement(IsNullable=true)]
    public DROApplicationAssetDetailMotorVehicle MotorVehicle
    {
        get
        {
            return this._motorVehicle;
        }
        set
        {
            this._motorVehicle = value;
        }
    }
}
}
#pragma warning restore
