//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace INSS.ODS.Bankruptcy.API.Common.Resources.Payments {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class RefundPolicyResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal RefundPolicyResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("INSS.ODS.Bankruptcy.API.Common.Resources.Payments.RefundPolicyResources", typeof(RefundPolicyResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;h3 class=&quot;heading-medium&quot;&gt;Refunds before you have submitted your application&lt;/h3&gt;
        ///            &lt;p&gt;If you decide not to submit your application you should first sign in to your
        ///               application and select ‘discard my application’.&lt;/p&gt;
        ///            &lt;p&gt;You can’t cancel your application after you have submitted it.&lt;/p&gt;
        ///            &lt;p&gt;After cancelling your application:&lt;/p&gt;
        ///            &lt;ul class=&quot;help&quot;&gt;
        ///              &lt;li&gt;you’ll receive a full refund of the money you have paid&lt;/li&gt;
        ///              &lt;li&gt;anyon [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Payments_RefundPolicy_Content {
            get {
                return ResourceManager.GetString("Payments_RefundPolicy_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Continue.
        /// </summary>
        public static string Payments_RefundPolicy_Continue_Label {
            get {
                return ResourceManager.GetString("Payments_RefundPolicy_Continue_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Make a fee payment.
        /// </summary>
        public static string Payments_RefundPolicy_MakeAPayment_Label {
            get {
                return ResourceManager.GetString("Payments_RefundPolicy_MakeAPayment_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refund Policy.
        /// </summary>
        public static string Payments_RefundPolicy_PageTitle {
            get {
                return ResourceManager.GetString("Payments_RefundPolicy_PageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paying the fee.
        /// </summary>
        public static string Payments_RefundPolicy_PayingHelp_Label {
            get {
                return ResourceManager.GetString("Payments_RefundPolicy_PayingHelp_Label", resourceCulture);
            }
        }
    }
}
