//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace INSS.ODS.Bankruptcy.API.Common.Resources.CompanyDirectorships {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AddLimitedCompanyNameResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AddLimitedCompanyNameResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("INSS.ODS.Bankruptcy.API.Common.Resources.CompanyDirectorships.AddLimitedCompanyNameResourc" +
                            "es", typeof(AddLimitedCompanyNameResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add limited company.
        /// </summary>
        public static string CompanyDirectorships_AddLimitedCompanyName_AddButton_Label {
            get {
                return ResourceManager.GetString("CompanyDirectorships_AddLimitedCompanyName_AddButton_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back.
        /// </summary>
        public static string CompanyDirectorships_AddLimitedCompanyName_BackLink_Label {
            get {
                return ResourceManager.GetString("CompanyDirectorships_AddLimitedCompanyName_BackLink_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter the name of the limited company.
        /// </summary>
        public static string CompanyDirectorships_AddLimitedCompanyName_CompanyName_Error_Empty {
            get {
                return ResourceManager.GetString("CompanyDirectorships_AddLimitedCompanyName_CompanyName_Error_Empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You entered a company name which doesn&apos;t includes Ltd, Limited, LLP, Limited Liability Partnership or PLC. We only need to know about directorships you have held with limited companies. Please check the company name and try again. If it isn&apos;t a limited company, we don&apos;t need to know about it here..
        /// </summary>
        public static string CompanyDirectorships_AddLimitedCompanyName_CompanyName_Error_IncorrectEnding {
            get {
                return ResourceManager.GetString("CompanyDirectorships_AddLimitedCompanyName_CompanyName_Error_IncorrectEnding", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please check the company name. You entered {0} which is invalid..
        /// </summary>
        public static string CompanyDirectorships_AddLimitedCompanyName_CompanyName_Error_InvalidCharacter {
            get {
                return ResourceManager.GetString("CompanyDirectorships_AddLimitedCompanyName_CompanyName_Error_InvalidCharacter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please answer in less than 101 characters.
        /// </summary>
        public static string CompanyDirectorships_AddLimitedCompanyName_CompanyName_Error_TooLong {
            get {
                return ResourceManager.GetString("CompanyDirectorships_AddLimitedCompanyName_CompanyName_Error_TooLong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please answer in more than 2 character.
        /// </summary>
        public static string CompanyDirectorships_AddLimitedCompanyName_CompanyName_Error_TooShort {
            get {
                return ResourceManager.GetString("CompanyDirectorships_AddLimitedCompanyName_CompanyName_Error_TooShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to For example, ABC Trading Ltd. You can add more companies later..
        /// </summary>
        public static string CompanyDirectorships_AddLimitedCompanyName_CompanyName_Hint {
            get {
                return ResourceManager.GetString("CompanyDirectorships_AddLimitedCompanyName_CompanyName_Hint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter the name of the company.
        /// </summary>
        public static string CompanyDirectorships_AddLimitedCompanyName_CompanyName_Label {
            get {
                return ResourceManager.GetString("CompanyDirectorships_AddLimitedCompanyName_CompanyName_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We need to know about all limited company directorships you have held in the last 12 months..
        /// </summary>
        public static string CompanyDirectorships_AddLimitedCompanyName_Page_Paragraph_One {
            get {
                return ResourceManager.GetString("CompanyDirectorships_AddLimitedCompanyName_Page_Paragraph_One", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Limited companies are registered with Companies House and have Ltd, PLC, LLP, or CIC as part of the company name, eg ABC Trading Ltd.
        /// </summary>
        public static string CompanyDirectorships_AddLimitedCompanyName_Page_Paragraph_Two {
            get {
                return ResourceManager.GetString("CompanyDirectorships_AddLimitedCompanyName_Page_Paragraph_Two", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company directorships.
        /// </summary>
        public static string CompanyDirectorships_AddLimitedCompanyName_Page_Title {
            get {
                return ResourceManager.GetString("CompanyDirectorships_AddLimitedCompanyName_Page_Title", resourceCulture);
            }
        }
    }
}
