//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace INSS.ODS.Bankruptcy.API.Common.Resources.BankAccount {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AccountDetailsResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AccountDetailsResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("INSS.ODS.Bankruptcy.API.Common.Resources.BankAccount.AccountDetailsResources", typeof(AccountDetailsResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter your account number.
        /// </summary>
        public static string BankAccount_AccountDetails_AccountNumber_Error_Empty {
            get {
                return ResourceManager.GetString("BankAccount_AccountDetails_AccountNumber_Error_Empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can find this on your account statement or at the bottom of your debit card. &lt;br/&gt; Contact the bank if you&apos;re unsure of your account number.
        /// </summary>
        public static string BankAccount_AccountDetails_AccountNumber_Hint {
            get {
                return ResourceManager.GetString("BankAccount_AccountDetails_AccountNumber_Hint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account number.
        /// </summary>
        public static string BankAccount_AccountDetails_AccountNumber_Label {
            get {
                return ResourceManager.GetString("BankAccount_AccountDetails_AccountNumber_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter your current balance.
        /// </summary>
        public static string BankAccount_AccountDetails_CurrentBalance_Error_Empty {
            get {
                return ResourceManager.GetString("BankAccount_AccountDetails_CurrentBalance_Error_Empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to For example, 200 or if you&apos;re overdrawn by £100, enter -100.
        /// </summary>
        public static string BankAccount_AccountDetails_CurrentBalance_Hint {
            get {
                return ResourceManager.GetString("BankAccount_AccountDetails_CurrentBalance_Hint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current balance.
        /// </summary>
        public static string BankAccount_AccountDetails_CurrentBalance_Label {
            get {
                return ResourceManager.GetString("BankAccount_AccountDetails_CurrentBalance_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The date you opened the account must be after 1900.
        /// </summary>
        public static string BankAccount_AccountDetails_DateOpened_Error_Date_After_1900 {
            get {
                return ResourceManager.GetString("BankAccount_AccountDetails_DateOpened_Error_Date_After_1900", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The date you opened the account cannot be a date in future.
        /// </summary>
        public static string BankAccount_AccountDetails_DateOpened_Error_Date_In_The_Past {
            get {
                return ResourceManager.GetString("BankAccount_AccountDetails_DateOpened_Error_Date_In_The_Past", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter the date you opened the account.
        /// </summary>
        public static string BankAccount_AccountDetails_DateOpened_Error_Empty {
            get {
                return ResourceManager.GetString("BankAccount_AccountDetails_DateOpened_Error_Empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to For example, Aug 2012.
        /// </summary>
        public static string BankAccount_AccountDetails_DateOpened_Hint {
            get {
                return ResourceManager.GetString("BankAccount_AccountDetails_DateOpened_Hint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter a date that isn&apos;t in the future.
        /// </summary>
        public static string BankAccount_AccountDetails_DateOpened_InTheFuture {
            get {
                return ResourceManager.GetString("BankAccount_AccountDetails_DateOpened_InTheFuture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date you opened the account.
        /// </summary>
        public static string BankAccount_AccountDetails_DateOpened_Label {
            get {
                return ResourceManager.GetString("BankAccount_AccountDetails_DateOpened_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter a date that&apos;s after your date of birth.
        /// </summary>
        public static string BankAccount_AccountDetails_DateOpened_LessThanApplicantsDateOfBirth {
            get {
                return ResourceManager.GetString("BankAccount_AccountDetails_DateOpened_LessThanApplicantsDateOfBirth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is this a joint account?.
        /// </summary>
        public static string BankAccount_AccountDetails_IsJointAccount_Label {
            get {
                return ResourceManager.GetString("BankAccount_AccountDetails_IsJointAccount_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please confirm if this is a joint account.
        /// </summary>
        public static string BankAccount_AccountDetails_JointAccount_Error_Empty {
            get {
                return ResourceManager.GetString("BankAccount_AccountDetails_JointAccount_Error_Empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please tell us about your account with {0}.
        /// </summary>
        public static string BankAccount_AccountDetails_Page_Hint {
            get {
                return ResourceManager.GetString("BankAccount_AccountDetails_Page_Hint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account Details.
        /// </summary>
        public static string BankAccount_AccountDetails_PageTitle_Label {
            get {
                return ResourceManager.GetString("BankAccount_AccountDetails_PageTitle_Label", resourceCulture);
            }
        }
    }
}
