//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace INSS.ODS.Bankruptcy.API.Common.Resources.BankAccount {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AddAccountResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AddAccountResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("INSS.ODS.Bankruptcy.API.Common.Resources.BankAccount.AddAccountResources", typeof(AddAccountResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add account.
        /// </summary>
        public static string BankAccount_AddAccount_AddButton_Label {
            get {
                return ResourceManager.GetString("BankAccount_AddAccount_AddButton_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add account.
        /// </summary>
        public static string BankAccount_AddAccount_AddButton_Label_Alt {
            get {
                return ResourceManager.GetString("BankAccount_AddAccount_AddButton_Label_Alt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back.
        /// </summary>
        public static string BankAccount_AddAccount_BackLink_Label {
            get {
                return ResourceManager.GetString("BankAccount_AddAccount_BackLink_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The table above summarises the accounts you have told us about..
        /// </summary>
        public static string BankAccount_AddAccount_BankAccountSummary_ParagraphOne {
            get {
                return ResourceManager.GetString("BankAccount_AddAccount_BankAccountSummary_ParagraphOne", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Continue - I have added all my accounts.
        /// </summary>
        public static string BankAccount_AddAccount_ContinueAddedAllAccountsLink_Label {
            get {
                return ResourceManager.GetString("BankAccount_AddAccount_ContinueAddedAllAccountsLink_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string BankAccount_AddAccount_DeleteButton_Label {
            get {
                return ResourceManager.GetString("BankAccount_AddAccount_DeleteButton_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        public static string BankAccount_AddAccount_EditButton_Label {
            get {
                return ResourceManager.GetString("BankAccount_AddAccount_EditButton_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Continue - I haven&apos;t had any bank accounts.
        /// </summary>
        public static string BankAccount_AddAccount_NoAccountLink_Label {
            get {
                return ResourceManager.GetString("BankAccount_AddAccount_NoAccountLink_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We need to know about all the accounts you have had in the last 2 years..
        /// </summary>
        public static string BankAccount_AddAccount_PageParagraphOne {
            get {
                return ResourceManager.GetString("BankAccount_AddAccount_PageParagraphOne", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This includes all of your personal accounts and savings in the UK and abroad as well as any joint, business, dormant or frozen accounts..
        /// </summary>
        public static string BankAccount_AddAccount_PageParagraphTwo {
            get {
                return ResourceManager.GetString("BankAccount_AddAccount_PageParagraphTwo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bank accounts and savings.
        /// </summary>
        public static string BankAccount_AddAccount_PageTitle_Label {
            get {
                return ResourceManager.GetString("BankAccount_AddAccount_PageTitle_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please check your sort code. You entered an invalid character..
        /// </summary>
        public static string BankAccount_AddAccount_SortCode_Error_InvalidCharacter {
            get {
                return ResourceManager.GetString("BankAccount_AddAccount_SortCode_Error_InvalidCharacter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We couldn&apos;t match the sort code with a UK bank. Please check your answer and try again. Leave the sort code field blank if it&apos;s a foreign bank account or if you don&apos;t know it..
        /// </summary>
        public static string BankAccount_AddAccount_SortCode_Error_NotRecognised {
            get {
                return ResourceManager.GetString("BankAccount_AddAccount_SortCode_Error_NotRecognised", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We couldn&apos;t match the sort code with a UK bank. Please check your answer and try again. Leave the sort code field blank if it&apos;s a foreign bank account or if you don&apos;t know it..
        /// </summary>
        public static string BankAccount_AddAccount_SortCode_Error_WrongLength {
            get {
                return ResourceManager.GetString("BankAccount_AddAccount_SortCode_Error_WrongLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sort Code.
        /// </summary>
        public static string BankAccount_AddAccount_SortCode_Label {
            get {
                return ResourceManager.GetString("BankAccount_AddAccount_SortCode_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter the account sort code.
        /// </summary>
        public static string BankAccount_AddAccount_SortCodeHeading_Label {
            get {
                return ResourceManager.GetString("BankAccount_AddAccount_SortCodeHeading_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can find it on your account statement or at the bottom of your debit card. 
        ///For example, 123456. You can add more accounts later..
        /// </summary>
        public static string BankAccount_AddAccount_SortCodeParagraphOne {
            get {
                return ResourceManager.GetString("BankAccount_AddAccount_SortCodeParagraphOne", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Leave the sort code blank if it&apos;s a foreign account or if you don&apos;t have one.
        /// </summary>
        public static string BankAccount_AddAccount_SortCodeParagraphTwo {
            get {
                return ResourceManager.GetString("BankAccount_AddAccount_SortCodeParagraphTwo", resourceCulture);
            }
        }
    }
}
