//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace INSS.ODS.Bankruptcy.API.Common.Resources.BankAccount {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class BankDetailsResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal BankDetailsResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("INSS.ODS.Bankruptcy.API.Common.Resources.BankAccount.BankDetailsResources", typeof(BankDetailsResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address.
        /// </summary>
        public static string BankAccount_BankDetails_AddressHeader_Label {
            get {
                return ResourceManager.GetString("BankAccount_BankDetails_AddressHeader_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please check your address. You entered {character} which is invalid..
        /// </summary>
        public static string BankAccount_BankDetails_AddressLine1_Error_InvalidCharacters {
            get {
                return ResourceManager.GetString("BankAccount_BankDetails_AddressLine1_Error_InvalidCharacters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter the address of your building society or bank.
        /// </summary>
        public static string BankAccount_BankDetails_AddressLine1_Error_Mandatory {
            get {
                return ResourceManager.GetString("BankAccount_BankDetails_AddressLine1_Error_Mandatory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Building and street.
        /// </summary>
        public static string BankAccount_BankDetails_AddressLine1_Label {
            get {
                return ResourceManager.GetString("BankAccount_BankDetails_AddressLine1_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter the name of building society or bank.
        /// </summary>
        public static string BankAccount_BankDetails_BankName_Error_Mandatory {
            get {
                return ResourceManager.GetString("BankAccount_BankDetails_BankName_Error_Mandatory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to For example, ABC Bank Ltd.
        /// </summary>
        public static string BankAccount_BankDetails_BankName_Hint {
            get {
                return ResourceManager.GetString("BankAccount_BankDetails_BankName_Hint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bank name.
        /// </summary>
        public static string BankAccount_BankDetails_BankName_Label {
            get {
                return ResourceManager.GetString("BankAccount_BankDetails_BankName_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter the country of your building society or bank.
        /// </summary>
        public static string BankAccount_BankDetails_Country_Error_Mandatory {
            get {
                return ResourceManager.GetString("BankAccount_BankDetails_Country_Error_Mandatory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Country.
        /// </summary>
        public static string BankAccount_BankDetails_Country_Label {
            get {
                return ResourceManager.GetString("BankAccount_BankDetails_Country_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to County.
        /// </summary>
        public static string BankAccount_BankDetails_County_Label {
            get {
                return ResourceManager.GetString("BankAccount_BankDetails_County_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bank details.
        /// </summary>
        public static string BankAccount_BankDetails_PageTitle {
            get {
                return ResourceManager.GetString("BankAccount_BankDetails_PageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter the postcode of your building society or bank&apos;s address.
        /// </summary>
        public static string BankAccount_BankDetails_PostCode_Error_Mandatory {
            get {
                return ResourceManager.GetString("BankAccount_BankDetails_PostCode_Error_Mandatory", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Please enter the postcode of your building society or bank&apos;s address.
        /// </summary>
        public static string BankAccount_BankDetails_PostCode_Error_MaxLength
        {
            get
            {
                return ResourceManager.GetString("BankAccount_BankDetails_PostCode_Error_MaxLength", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Please enter the postcode of your building society or bank&apos;s address.
        /// </summary>
        public static string BankAccount_BankDetails_PostCode_Error_SpecialCharacters
        {
            get
            {
                return ResourceManager.GetString("BankAccount_BankDetails_PostCode_Error_SpecialCharacters", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Postal code.
        /// </summary>
        public static string BankAccount_BankDetails_PostCode_Label {
            get {
                return ResourceManager.GetString("BankAccount_BankDetails_PostCode_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter your bank&apos;s sort code. You can normally find this on your debit card. &lt;br&gt; Leave blank, if this is a foreign bank account. .
        /// </summary>
        public static string BankAccount_BankDetails_SortCode_Hint {
            get {
                return ResourceManager.GetString("BankAccount_BankDetails_SortCode_Hint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bank Sort Code.
        /// </summary>
        public static string BankAccount_BankDetails_SortCode_Label {
            get {
                return ResourceManager.GetString("BankAccount_BankDetails_SortCode_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Town/city.
        /// </summary>
        public static string BankAccount_BankDetails_TownCity_Label {
            get {
                return ResourceManager.GetString("BankAccount_BankDetails_TownCity_Label", resourceCulture);
            }
        }
    }
}
