//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace INSS.ODS.Bankruptcy.API.Common.Resources.Common {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ElementLabelResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ElementLabelResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("INSS.ODS.Bankruptcy.API.Common.Resources.Common.ElementLabelResources", typeof(ElementLabelResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back.
        /// </summary>
        public static string Common_ElementLabel_Back_Label {
            get {
                return ResourceManager.GetString("Common_ElementLabel_Back_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back to Application Overview.
        /// </summary>
        public static string Common_ElementLabel_BackToOverview_Label {
            get {
                return ResourceManager.GetString("Common_ElementLabel_BackToOverview_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change your answer.
        /// </summary>
        public static string Common_ElementLabel_ChangeYourAnswer_Label {
            get {
                return ResourceManager.GetString("Common_ElementLabel_ChangeYourAnswer_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Complete this record.
        /// </summary>
        public static string Common_ElementLabel_CompleteRecord_Label {
            get {
                return ResourceManager.GetString("Common_ElementLabel_CompleteRecord_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Complete this section.
        /// </summary>
        public static string Common_ElementLabel_CompleteSection_Label {
            get {
                return ResourceManager.GetString("Common_ElementLabel_CompleteSection_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Continue.
        /// </summary>
        public static string Common_ElementLabel_Continue_Label {
            get {
                return ResourceManager.GetString("Common_ElementLabel_Continue_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string Common_ElementLabel_Delete_Label {
            get {
                return ResourceManager.GetString("Common_ElementLabel_Delete_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        public static string Common_ElementLabel_Edit_Label {
            get {
                return ResourceManager.GetString("Common_ElementLabel_Edit_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        public static string Common_ElementLabel_No_Label {
            get {
                return ResourceManager.GetString("Common_ElementLabel_No_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View your answers.
        /// </summary>
        public static string Common_ElementLabel_ViewYourAnswers_Label {
            get {
                return ResourceManager.GetString("Common_ElementLabel_ViewYourAnswers_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        public static string Common_ElementLabel_Yes_Label {
            get {
                return ResourceManager.GetString("Common_ElementLabel_Yes_Label", resourceCulture);
            }
        }
    }
}
