//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace INSS.ODS.Bankruptcy.API.Common.Resources.ApplicationOverview {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class DiscardApplicationResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal DiscardApplicationResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("INSS.ODS.Bankruptcy.API.Common.Resources.ApplicationOverview.DiscardApplicationResources", typeof(DiscardApplicationResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IMPORTANT! do not continue with cancelling your application if you have changed your bank account since you paid your fee. .
        /// </summary>
        public static string ApplicationOverview_DiscardApplication_BankAccountWarning_Text1 {
            get {
                return ResourceManager.GetString("ApplicationOverview_DiscardApplication_BankAccountWarning_Text1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please email the Adjudicator&apos;s Office at Adjudicator1@insolvency.gov.uk, quoting your ADJ reference, so that we can make alternative arrangements for your refund..
        /// </summary>
        public static string ApplicationOverview_DiscardApplication_BankAccountWarning_Text2 {
            get {
                return ResourceManager.GetString("ApplicationOverview_DiscardApplication_BankAccountWarning_Text2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string ApplicationOverview_DiscardApplication_Cancel_Label {
            get {
                return ResourceManager.GetString("ApplicationOverview_DiscardApplication_Cancel_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Discard Application.
        /// </summary>
        public static string ApplicationOverview_DiscardApplication_Confirm_Label {
            get {
                return ResourceManager.GetString("ApplicationOverview_DiscardApplication_Confirm_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        public static string ApplicationOverview_DiscardApplication_Final_Cancel_Label {
            get {
                return ResourceManager.GetString("ApplicationOverview_DiscardApplication_Final_Cancel_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        public static string ApplicationOverview_DiscardApplication_Final_Confirm_Label {
            get {
                return ResourceManager.GetString("ApplicationOverview_DiscardApplication_Final_Confirm_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Discard Application.
        /// </summary>
        public static string ApplicationOverview_DiscardApplication_PageTitle {
            get {
                return ResourceManager.GetString("ApplicationOverview_DiscardApplication_PageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to discard your application?.
        /// </summary>
        public static string ApplicationOverview_DiscardApplication_SubTitle {
            get {
                return ResourceManager.GetString("ApplicationOverview_DiscardApplication_SubTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The application and all information you have entered will be deleted, including your account and your application number..
        /// </summary>
        public static string ApplicationOverview_DiscardApplication_Text1 {
            get {
                return ResourceManager.GetString("ApplicationOverview_DiscardApplication_Text1", resourceCulture);
            }
        }
    }
}
