//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace INSS.ODS.Bankruptcy.API.Common.Resources.OtherAssets {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class PossessionsResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal PossessionsResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("INSS.ODS.Bankruptcy.API.Common.Resources.OtherAssets.PossessionsResources", typeof(PossessionsResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add another item.
        /// </summary>
        public static string OtherAssets_Possessions_Add_Label {
            get {
                return ResourceManager.GetString("OtherAssets_Possessions_Add_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Amount must be greater than or equal to £500.
        /// </summary>
        public static string OtherAssets_Possessions_Amount_Error_Minimum {
            get {
                return ResourceManager.GetString("OtherAssets_Possessions_Amount_Error_Minimum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter a value.
        /// </summary>
        public static string OtherAssets_Possessions_Amount_Error_Required {
            get {
                return ResourceManager.GetString("OtherAssets_Possessions_Amount_Error_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please provide the most accurate figure you can.
        /// </summary>
        public static string OtherAssets_Possessions_Amount_HintText {
            get {
                return ResourceManager.GetString("OtherAssets_Possessions_Amount_HintText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to How much is it worth?.
        /// </summary>
        public static string OtherAssets_Possessions_Amount_Label {
            get {
                return ResourceManager.GetString("OtherAssets_Possessions_Amount_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete this item?.
        /// </summary>
        public static string OtherAssets_Possessions_Delete_Confirmation {
            get {
                return ResourceManager.GetString("OtherAssets_Possessions_Delete_Confirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The description is too long. Please answer in less than 100 characters..
        /// </summary>
        public static string OtherAssets_Possessions_Description_Error_MaxLength {
            get {
                return ResourceManager.GetString("OtherAssets_Possessions_Description_Error_MaxLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter a description for this item.
        /// </summary>
        public static string OtherAssets_Possessions_Description_Error_Required {
            get {
                return ResourceManager.GetString("OtherAssets_Possessions_Description_Error_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to For example, a smart TV.
        /// </summary>
        public static string OtherAssets_Possessions_Description_HintText {
            get {
                return ResourceManager.GetString("OtherAssets_Possessions_Description_HintText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What is the item?.
        /// </summary>
        public static string OtherAssets_Possessions_Description_Label {
            get {
                return ResourceManager.GetString("OtherAssets_Possessions_Description_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;p&gt;Tell us about any items currently worth more than &lt;strong&gt;£500&lt;/strong&gt; each, including:&lt;/p&gt; &lt;ul id=&quot;details3&quot; class=&quot;rowbottom help  list-bullet&quot;&gt;     
        ///        &lt;li&gt;jewellery&lt;/li&gt;
        ///        &lt;li&gt;antiques&lt;/li&gt;
        ///        &lt;li&gt;bicycles&lt;/li&gt;
        ///        &lt;li&gt;boats or other vessels (eg kayaks, rafts)&lt;/li&gt;
        ///        &lt;li&gt;paintings or other works or art (eg sculptures)
        ///        &lt;/li&gt;
        ///    &lt;/ul&gt;.
        /// </summary>
        public static string OtherAssets_Possessions_IntroText {
            get {
                return ResourceManager.GetString("OtherAssets_Possessions_IntroText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Items or possessions.
        /// </summary>
        public static string OtherAssets_Possessions_PageTitle {
            get {
                return ResourceManager.GetString("OtherAssets_Possessions_PageTitle", resourceCulture);
            }
        }
    }
}
