//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace INSS.ODS.Bankruptcy.API.Common.Resources.OtherAssets {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class WillsResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal WillsResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("INSS.ODS.Bankruptcy.API.Common.Resources.OtherAssets.WillsResources", typeof(WillsResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add another trust and will.
        /// </summary>
        public static string OtherAssets_Wills_Add_Label {
            get {
                return ResourceManager.GetString("OtherAssets_Wills_Add_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Amount must be greater than zero.
        /// </summary>
        public static string OtherAssets_Wills_Amount_Error_Minimum {
            get {
                return ResourceManager.GetString("OtherAssets_Wills_Amount_Error_Minimum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter the amount you will receive.
        /// </summary>
        public static string OtherAssets_Wills_Amount_Error_Required {
            get {
                return ResourceManager.GetString("OtherAssets_Wills_Amount_Error_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If you’ve been left a physical item in a will, tell us its approximate value..
        /// </summary>
        public static string OtherAssets_Wills_Amount_HintText {
            get {
                return ResourceManager.GetString("OtherAssets_Wills_Amount_HintText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Amount you receive or will receive in the future.
        /// </summary>
        public static string OtherAssets_Wills_Amount_Label {
            get {
                return ResourceManager.GetString("OtherAssets_Wills_Amount_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string OtherAssets_Wills_Delete_Label {
            get {
                return ResourceManager.GetString("OtherAssets_Wills_Delete_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to item.
        /// </summary>
        public static string OtherAssets_Wills_DeleteConfirmation_ItemName {
            get {
                return ResourceManager.GetString("OtherAssets_Wills_DeleteConfirmation_ItemName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The description is too long. Please answer in less than 100 characters..
        /// </summary>
        public static string OtherAssets_Wills_Description_Error_MaxLength {
            get {
                return ResourceManager.GetString("OtherAssets_Wills_Description_Error_MaxLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter the name of the trust or of the deceased individual.
        /// </summary>
        public static string OtherAssets_Wills_Description_Error_Required {
            get {
                return ResourceManager.GetString("OtherAssets_Wills_Description_Error_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to For example, The John Smith Trust or John Smith.
        /// </summary>
        public static string OtherAssets_Wills_Description_HintText {
            get {
                return ResourceManager.GetString("OtherAssets_Wills_Description_HintText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name of the trust or of the deceased individual.
        /// </summary>
        public static string OtherAssets_Wills_Description_Label {
            get {
                return ResourceManager.GetString("OtherAssets_Wills_Description_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;p&gt;Include:&lt;/p&gt;&lt;ul id=&quot;details5&quot; class=&quot;rowbottom help list-bullet&quot;&gt;
        ///        &lt;li&gt;any trusts you are a beneficiary of&lt;/li&gt;
        ///        &lt;li&gt;anything that has been left to you in a deceased individual’s will that you haven’t yet received (eg money, stock, possessions)&lt;/li&gt;
        ///    &lt;/ul&gt;.
        /// </summary>
        public static string OtherAssets_Wills_IntroText {
            get {
                return ResourceManager.GetString("OtherAssets_Wills_IntroText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trusts and wills.
        /// </summary>
        public static string OtherAssets_Wills_PageTitle {
            get {
                return ResourceManager.GetString("OtherAssets_Wills_PageTitle", resourceCulture);
            }
        }
    }
}
