//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace INSS.ODS.Bankruptcy.API.Common.Resources.DRO {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class PensionsResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal PensionsResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("INSS.ODS.Bankruptcy.API.Common.Resources.DRO.PensionsResources", typeof(PensionsResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select an answer.
        /// </summary>
        public static string Pensions_ApprovedPension_Error_Empty {
            get {
                return ResourceManager.GetString("Pensions_ApprovedPension_Error_Empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An approved pension is any occupational or personal pension approved by HMRC for tax purposes.
        /// </summary>
        public static string Pensions_ApprovedPension_HelpText {
            get {
                return ResourceManager.GetString("Pensions_ApprovedPension_HelpText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is this an approved pension?.
        /// </summary>
        public static string Pensions_ApprovedPension_Label {
            get {
                return ResourceManager.GetString("Pensions_ApprovedPension_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select an answer.
        /// </summary>
        public static string Pensions_CurrentEmployerPension_Error_Empty {
            get {
                return ResourceManager.GetString("Pensions_CurrentEmployerPension_Error_Empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is this Pension with the current employer?.
        /// </summary>
        public static string Pensions_CurrentEmployerPension_Label {
            get {
                return ResourceManager.GetString("Pensions_CurrentEmployerPension_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Don&apos;t include any pensions you&apos;re currently receiving payments from.
        /// </summary>
        public static string Pensions_HaveAnyPensions_HelpText {
            get {
                return ResourceManager.GetString("Pensions_HaveAnyPensions_HelpText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you have a pension?.
        /// </summary>
        public static string Pensions_HaveAnyPensions_Label {
            get {
                return ResourceManager.GetString("Pensions_HaveAnyPensions_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter the pension provider&apos;s name.
        /// </summary>
        public static string Pensions_PensionProviderName_Label {
            get {
                return ResourceManager.GetString("Pensions_PensionProviderName_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select an answer.
        /// </summary>
        public static string Pensions_PersonalPension_Error_Empty {
            get {
                return ResourceManager.GetString("Pensions_PersonalPension_Error_Empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Answer no if this is a State Pension.
        /// </summary>
        public static string Pensions_PersonalPension_HelpText {
            get {
                return ResourceManager.GetString("Pensions_PersonalPension_HelpText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Will you be eligible to draw money from this pension before the end of your DRO (application date plus 12 months)?.
        /// </summary>
        public static string Pensions_PersonalPension_Label {
            get {
                return ResourceManager.GetString("Pensions_PersonalPension_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter your policy number.
        /// </summary>
        public static string Pensions_Policynumber_Error_Empty {
            get {
                return ResourceManager.GetString("Pensions_Policynumber_Error_Empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Policy number.
        /// </summary>
        public static string Pensions_PolicyNumber_Label {
            get {
                return ResourceManager.GetString("Pensions_PolicyNumber_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The policy number cannot be more than 35 characters.
        /// </summary>
        public static string Pensions_PolicyNumber_Too_Long_Error {
            get {
                return ResourceManager.GetString("Pensions_PolicyNumber_Too_Long_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The pension provider&apos;s name field can&apos;t be more than 80 characters.
        /// </summary>
        public static string Pensions_ProviderName_Error_Incorrect_Length {
            get {
                return ResourceManager.GetString("Pensions_ProviderName_Error_Incorrect_Length", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to For workplace pensions, you can enter the name of your employer.
        /// </summary>
        public static string Pensions_ProviderName_HelpText {
            get {
                return ResourceManager.GetString("Pensions_ProviderName_HelpText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pension provider&apos;s name.
        /// </summary>
        public static string Pensions_ProviderName_Label {
            get {
                return ResourceManager.GetString("Pensions_ProviderName_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter the pension provider&apos;s name.
        /// </summary>
        public static string Pensions_Query_Error_Empty {
            get {
                return ResourceManager.GetString("Pensions_Query_Error_Empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you currently receiving any payments from this pension?.
        /// </summary>
        public static string Pensions_ReceivePaymentFromPension_Label {
            get {
                return ResourceManager.GetString("Pensions_ReceivePaymentFromPension_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 5. Select pension.
        /// </summary>
        public static string Pensions_Search_Title {
            get {
                return ResourceManager.GetString("Pensions_Search_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter the value of the pension.
        /// </summary>
        public static string Pensions_ValueOfPension_Error_Empty {
            get {
                return ResourceManager.GetString("Pensions_ValueOfPension_Error_Empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to How much is the pension currently worth?.
        /// </summary>
        public static string Pensions_ValueOfPension_Label {
            get {
                return ResourceManager.GetString("Pensions_ValueOfPension_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string PensionsResources_Popup_CancelButton_Label {
            get {
                return ResourceManager.GetString("PensionsResources_Popup_CancelButton_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete this item?.
        /// </summary>
        public static string PensionsResources_Popup_Message {
            get {
                return ResourceManager.GetString("PensionsResources_Popup_Message", resourceCulture);
            }
        }
    }
}
