//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace INSS.ODS.Bankruptcy.API.Common.Resources.DRO {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class PrivacyResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal PrivacyResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("INSS.ODS.Bankruptcy.API.Common.Resources.DRO.PrivacyResources", typeof(PrivacyResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Privacy: The Insolvency Service.
        /// </summary>
        public static string Home_Privacy_PageTitle {
            get {
                return ResourceManager.GetString("Home_Privacy_PageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This service is run by the Insolvency Service. We&apos;ll handle the information you give to us according
        ///
        ///to the provisions of the &lt;a href=&quot;http://www.legislation.gov.uk/ukpga/1998/29/contents&quot;&gt;Data Protection Act 1998&lt;/a&gt; and the details of the adjudicator’s functions 
        ///
        ///registered with the &lt;a href=&quot;https://ico.org.uk/&quot;&gt; Information Commissioners Office (ICO)&lt;/a&gt;..
        /// </summary>
        public static string Home_Privacy_Section1_Para1 {
            get {
                return ResourceManager.GetString("Home_Privacy_Section1_Para1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The official receiver (OR) is a data controller for the purposes of the Data Protection Act 1998 and is registered to process the personal data you enter when completing your application..
        /// </summary>
        public static string Home_Privacy_Section1_Para2 {
            get {
                return ResourceManager.GetString("Home_Privacy_Section1_Para2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Most of the information the OR will hold about you will come from information you have given them. You’ll already know this personal information, but you can check if it’s accurate by sending a completed  &lt;a href=&quot;{0}&quot;&gt;subject access request&lt;/a&gt;(MS Word Document, 145KB) to &lt;a href=&quot;mailto:foi@insolvency.gov.uk&quot;&gt;foi@insolvency.gov.uk&lt;/a&gt;..
        /// </summary>
        public static string Home_Privacy_Section1_Para3 {
            get {
                return ResourceManager.GetString("Home_Privacy_Section1_Para3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You’ll receive within 40 days..
        /// </summary>
        public static string Home_Privacy_Section1_Para4 {
            get {
                return ResourceManager.GetString("Home_Privacy_Section1_Para4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If your information is incorrect and is likely to cause any issues, you should write to the FOI/DPA 
        ///team with details on what needs to be updated.
        ///&lt;p &gt;
        ///FOI/DPA, &lt;br /&gt;Technical Section, &lt;br /&gt; The Insolvency Service, &lt;br /&gt; 1 City Walk, &lt;br /&gt; Leeds &lt;br/&gt; LS11 9DA &lt;/p&gt;.
        /// </summary>
        public static string Home_Privacy_Section1_Para5 {
            get {
                return ResourceManager.GetString("Home_Privacy_Section1_Para5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Further information on how the 
        ///Insolvency Service and the official receiver treat your personal information can be found in the 
        ///&lt;a href=&quot;https://www.gov.uk/government/organisations/insolvency-service/about/personal-information-charter&quot;&gt;Insolvency Service personal information charter&lt;/a&gt;..
        /// </summary>
        public static string Home_Privacy_Section1_Para6 {
            get {
                return ResourceManager.GetString("Home_Privacy_Section1_Para6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to How we use your data.
        /// </summary>
        public static string Home_Privacy_Section2_Heading {
            get {
                return ResourceManager.GetString("Home_Privacy_Section2_Heading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to When you use our online service, the personal information you give to us will be used:.
        /// </summary>
        public static string Home_Privacy_Section2_Para1 {
            get {
                return ResourceManager.GetString("Home_Privacy_Section2_Para1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to to assess and make a decision about your Debt Relief Order (DRO) application.
        /// </summary>
        public static string Home_Privacy_Section2_Para1_List1_Item1 {
            get {
                return ResourceManager.GetString("Home_Privacy_Section2_Para1_List1_Item1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to to manage your DRO if your application is successful.
        /// </summary>
        public static string Home_Privacy_Section2_Para1_List1_Item2 {
            get {
                return ResourceManager.GetString("Home_Privacy_Section2_Para1_List1_Item2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to to list your DRO in the &lt;a href=&quot;https://www.insolvencydirect.bis.gov.uk/eiir/&quot;&gt;Individual Insolvency Register&lt;/a&gt;.
        /// </summary>
        public static string Home_Privacy_Section2_Para1_List1_Item3 {
            get {
                return ResourceManager.GetString("Home_Privacy_Section2_Para1_List1_Item3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to so we can contact you regarding your application or DRO.
        /// </summary>
        public static string Home_Privacy_Section2_Para1_List1_Item4 {
            get {
                return ResourceManager.GetString("Home_Privacy_Section2_Para1_List1_Item4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to so we can contact you to help us improve our service.
        /// </summary>
        public static string Home_Privacy_Section2_Para1_List1_Item5 {
            get {
                return ResourceManager.GetString("Home_Privacy_Section2_Para1_List1_Item5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We may also use the information you include in your application about organisations and individuals to contact them as required to manage your DRO. For example, we will need to contact your creditors using the details you provided to make them aware that you have a DRO..
        /// </summary>
        public static string Home_Privacy_Section2_Para2 {
            get {
                return ResourceManager.GetString("Home_Privacy_Section2_Para2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please note that the Insolvency Service can&apos;t provide legal or financial advice. You should seek this
        ///from a Citizen&apos;s Advice Bureau, a solicitor, a qualified accountant, an authorised insolvency 
        ///practitioner, reputable financial advisor or advice centre..
        /// </summary>
        public static string Home_Privacy_Section2_Para3 {
            get {
                return ResourceManager.GetString("Home_Privacy_Section2_Para3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Storing your data.
        /// </summary>
        public static string Home_Privacy_Section3_Heading {
            get {
                return ResourceManager.GetString("Home_Privacy_Section3_Heading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your data will be stored securely within the European Economic Area (EEA) while you complete 
        ///your application and while your application is being considered.  A copy of your information will 
        ///then be transferred to the Insolvency Service&apos;s long term records, where it will be stored securely 
        ///and used only as allowed by the Insolvency Act 1986..
        /// </summary>
        public static string Home_Privacy_Section3_Para1 {
            get {
                return ResourceManager.GetString("Home_Privacy_Section3_Para1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We may share the information in your application with your creditors, their representatives,
        ///government departments, agencies, organisations or individuals if we&apos;re required to do so by law. 
        ///For example, we will share your personal details with an insolvency practitioner should one be 
        ///appointed as your trustee instead of the official receiver..
        /// </summary>
        public static string Home_Privacy_Section3_Para2 {
            get {
                return ResourceManager.GetString("Home_Privacy_Section3_Para2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We’ll never share your information with other organisations for marketing, market research or 
        ///commercial purposes, and we don’t pass on your personal information to any other websites..
        /// </summary>
        public static string Home_Privacy_Section3_Para3 {
            get {
                return ResourceManager.GetString("Home_Privacy_Section3_Para3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Online payments.
        /// </summary>
        public static string Home_Privacy_Section4_Heading {
            get {
                return ResourceManager.GetString("Home_Privacy_Section4_Heading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If you choose to pay the application fee online, you will be directed to our payment partner, 
        ///WorldPay, for the payment to be processed.  The details you give them will be encrypted in line 
        ///with the Payment Card Industry Data Security Standard (PCI-DSS)..
        /// </summary>
        public static string Home_Privacy_Section4_Para1 {
            get {
                return ResourceManager.GetString("Home_Privacy_Section4_Para1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Insolvency Service won’t store any of your payment card details and isn&apos;t liable for any
        ///
        ///information you enter into WorldPay’s pages. To pay online you must abide by WorldPay’s terms 
        ///
        ///and conditions, which you can read here along with some frequently, asked questions:.
        /// </summary>
        public static string Home_Privacy_Section4_Para2 {
            get {
                return ResourceManager.GetString("Home_Privacy_Section4_Para2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;a href=https://support.worldpay.com/support/index.php?page=tandc&gt;WorldPay website terms and conditions&lt;/a&gt;.
        /// </summary>
        public static string Home_Privacy_Section4_Para2_List1_Item1 {
            get {
                return ResourceManager.GetString("Home_Privacy_Section4_Para2_List1_Item1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;a href=&quot;https://support.worldpay.com/support/shopper/index.php?page=shopper-faq&quot;&gt;WorldPay shopper FAQs&lt;/a&gt;.
        /// </summary>
        public static string Home_Privacy_Section4_Para2_List1_Item2 {
            get {
                return ResourceManager.GetString("Home_Privacy_Section4_Para2_List1_Item2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Credit search.
        /// </summary>
        public static string Home_Privacy_Section5_Heading {
            get {
                return ResourceManager.GetString("Home_Privacy_Section5_Heading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to When you submit your application, the OR will run a credit search on you with the credit reference agency Experian. The OR uses this search to check that the information in your application is correct, not to find out your credit score. The search won’t affect your credit rating, and the results won’t be shared with anyone outside the Insolvency Service..
        /// </summary>
        public static string Home_Privacy_Section5_Para1 {
            get {
                return ResourceManager.GetString("Home_Privacy_Section5_Para1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Experian will keep a record of the search for 12 months. This also won’t affect your credit rating. You can find information about and contact details for Equifax at  &lt;a href=&quot;http://www.experian.co.uk/&quot;&gt;www.experian.co.uk&lt;/a&gt;..
        /// </summary>
        public static string Home_Privacy_Section5_Para2 {
            get {
                return ResourceManager.GetString("Home_Privacy_Section5_Para2", resourceCulture);
            }
        }
    }
}
