//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace INSS.ODS.Bankruptcy.API.Common.Resources.DRO {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class UnderValueTransactionsResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal UnderValueTransactionsResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("INSS.ODS.Bankruptcy.API.Common.Resources.DRO.UnderValueTransactionsResources", typeof(UnderValueTransactionsResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please provide your answer in the dd/mm/yyyy format.
        /// </summary>
        public static string UnderValueTransactions_DateSoldOrGivenAway_Error_Incomplete {
            get {
                return ResourceManager.GetString("UnderValueTransactions_DateSoldOrGivenAway_Error_Incomplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to For example 31 08 1976.
        /// </summary>
        public static string UnderValueTransactions_DateSoldOrGivenAway_HelpText {
            get {
                return ResourceManager.GetString("UnderValueTransactions_DateSoldOrGivenAway_HelpText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date you sold or gave the item away.
        /// </summary>
        public static string UnderValueTransactions_DateSoldOrGivenAway_Label {
            get {
                return ResourceManager.GetString("UnderValueTransactions_DateSoldOrGivenAway_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In the last 2 years, have you given away or sold any assets for less than they&apos;re worth?.
        /// </summary>
        public static string UnderValueTransactions_GivenAwayOrSold_Label {
            get {
                return ResourceManager.GetString("UnderValueTransactions_GivenAwayOrSold_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please leave blank if you gave the item away.
        /// </summary>
        public static string UnderValueTransactions_HowMuchReceivedForAsset_Help_Text {
            get {
                return ResourceManager.GetString("UnderValueTransactions_HowMuchReceivedForAsset_Help_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to How much money did you receive after any charges and legal fees?.
        /// </summary>
        public static string UnderValueTransactions_HowMuchReceivedForAsset_Label {
            get {
                return ResourceManager.GetString("UnderValueTransactions_HowMuchReceivedForAsset_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item Description can&apos;t be more than 50 characters long.
        /// </summary>
        public static string UnderValueTransactions_ItemDescription_Error_TooLong {
            get {
                return ResourceManager.GetString("UnderValueTransactions_ItemDescription_Error_TooLong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What did you sell or give away?.
        /// </summary>
        public static string UnderValueTransactions_ItemDescription_Label {
            get {
                return ResourceManager.GetString("UnderValueTransactions_ItemDescription_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string UnderValueTransactions_Popup_CancelButton {
            get {
                return ResourceManager.GetString("UnderValueTransactions_Popup_CancelButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string UnderValueTransactions_Popup_DeleteButton {
            get {
                return ResourceManager.GetString("UnderValueTransactions_Popup_DeleteButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete this asset?.
        /// </summary>
        public static string UnderValueTransactions_Popup_Message {
            get {
                return ResourceManager.GetString("UnderValueTransactions_Popup_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Provide further details field can&apos;t be more than 250 characters long.
        /// </summary>
        public static string UnderValueTransactions_ProvideAnyFurtherDetails_Error_TooLong {
            get {
                return ResourceManager.GetString("UnderValueTransactions_ProvideAnyFurtherDetails_Error_TooLong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to For example, identification marks or the condition of the asset.
        /// </summary>
        public static string UnderValueTransactions_ProvideAnyFurtherDetails_HelpText {
            get {
                return ResourceManager.GetString("UnderValueTransactions_ProvideAnyFurtherDetails_HelpText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Why did you sell/transfer the item for less than its market value?.
        /// </summary>
        public static string UnderValueTransactions_ProvideAnyFurtherDetails_Label {
            get {
                return ResourceManager.GetString("UnderValueTransactions_ProvideAnyFurtherDetails_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Include details of why you were motivated to make the sale at this time, how you valued the item, any advertising of the asset for sale (online or locally) and how any proceeds of sale were spent.
        /// </summary>
        public static string UnderValueTransactions_ProvideAnyFurtherDetails_Label_Hint_Text {
            get {
                return ResourceManager.GetString("UnderValueTransactions_ProvideAnyFurtherDetails_Label_Hint_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Left :.
        /// </summary>
        public static string UnderValueTransactions_ProvideAnyFurtherDetails_WordsLeft {
            get {
                return ResourceManager.GetString("UnderValueTransactions_ProvideAnyFurtherDetails_WordsLeft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Count :.
        /// </summary>
        public static string UnderValueTransactions_ProvideAnyFurtherDetails_WordsUsed {
            get {
                return ResourceManager.GetString("UnderValueTransactions_ProvideAnyFurtherDetails_WordsUsed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What happened to the proceeds of the sale?.
        /// </summary>
        public static string UnderValueTransactions_WhatHappenedToTheProceedsOfTheSale_Label {
            get {
                return ResourceManager.GetString("UnderValueTransactions_WhatHappenedToTheProceedsOfTheSale_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What was the market value of the item?.
        /// </summary>
        public static string UnderValueTransactions_WhatWasTheMarketValueOfTheAsset_Label {
            get {
                return ResourceManager.GetString("UnderValueTransactions_WhatWasTheMarketValueOfTheAsset_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Who did you sell or give the item to?.
        /// </summary>
        public static string UnderValueTransactions_WhoDidYouSellOrGiveTo_Label {
            get {
                return ResourceManager.GetString("UnderValueTransactions_WhoDidYouSellOrGiveTo_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A family member.
        /// </summary>
        public static string UnderValueTransactions_WhoDidYouSellOrGiveTo_Option1_Label {
            get {
                return ResourceManager.GetString("UnderValueTransactions_WhoDidYouSellOrGiveTo_Option1_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A member of your spouse&apos;s family.
        /// </summary>
        public static string UnderValueTransactions_WhoDidYouSellOrGiveTo_Option2_Label {
            get {
                return ResourceManager.GetString("UnderValueTransactions_WhoDidYouSellOrGiveTo_Option2_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An employee.
        /// </summary>
        public static string UnderValueTransactions_WhoDidYouSellOrGiveTo_Option3_Label {
            get {
                return ResourceManager.GetString("UnderValueTransactions_WhoDidYouSellOrGiveTo_Option3_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An employer.
        /// </summary>
        public static string UnderValueTransactions_WhoDidYouSellOrGiveTo_Option4_Label {
            get {
                return ResourceManager.GetString("UnderValueTransactions_WhoDidYouSellOrGiveTo_Option4_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A business partner.
        /// </summary>
        public static string UnderValueTransactions_WhoDidYouSellOrGiveTo_Option5_Label {
            get {
                return ResourceManager.GetString("UnderValueTransactions_WhoDidYouSellOrGiveTo_Option5_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A business partner&apos;s spouse.
        /// </summary>
        public static string UnderValueTransactions_WhoDidYouSellOrGiveTo_Option6_Label {
            get {
                return ResourceManager.GetString("UnderValueTransactions_WhoDidYouSellOrGiveTo_Option6_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A company you are a director of.
        /// </summary>
        public static string UnderValueTransactions_WhoDidYouSellOrGiveTo_Option7_Label {
            get {
                return ResourceManager.GetString("UnderValueTransactions_WhoDidYouSellOrGiveTo_Option7_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Other.
        /// </summary>
        public static string UnderValueTransactions_WhoDidYouSellOrGiveTo_Option8_Label {
            get {
                return ResourceManager.GetString("UnderValueTransactions_WhoDidYouSellOrGiveTo_Option8_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Why didn&apos;t you sell/transfer the asset for it&apos;s market value?.
        /// </summary>
        public static string UnderValueTransactions_WhyDidYouSellOrGiveAway_Label {
            get {
                return ResourceManager.GetString("UnderValueTransactions_WhyDidYouSellOrGiveAway_Label", resourceCulture);
            }
        }
    }
}
