//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace INSS.ODS.Bankruptcy.API.Common.Resources.Property {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AddNameOfLodgerResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AddNameOfLodgerResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("INSS.ODS.Bankruptcy.API.Common.Resources.Property.AddNameOfLodgerResources", typeof(AddNameOfLodgerResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to lodger.
        /// </summary>
        public static string Property_AddNameOfLodger__DeleteConfirmation_lodger {
            get {
                return ResourceManager.GetString("Property_AddNameOfLodger__DeleteConfirmation_lodger", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add lodger.
        /// </summary>
        public static string Property_AddNameOfLodger_AddLodger_ButtonText {
            get {
                return ResourceManager.GetString("Property_AddNameOfLodger_AddLodger_ButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back.
        /// </summary>
        public static string Property_AddNameOfLodger_Back_ButtonText {
            get {
                return ResourceManager.GetString("Property_AddNameOfLodger_Back_ButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to save lodger details due to server error. Please try again later..
        /// </summary>
        public static string Property_AddNameOfLodger_Continue_Error_ServerError {
            get {
                return ResourceManager.GetString("Property_AddNameOfLodger_Continue_Error_ServerError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to add the lodger you typed in below? To add this lodger, please select the green &apos;Add lodger&apos;.
        /// </summary>
        public static string Property_AddNameOfLodger_Continue_Error_WithNameTyped {
            get {
                return ResourceManager.GetString("Property_AddNameOfLodger_Continue_Error_WithNameTyped", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Continue - I have added all my lodgers.
        /// </summary>
        public static string Property_AddNameOfLodger_Continue_WithLodger_ButtonText {
            get {
                return ResourceManager.GetString("Property_AddNameOfLodger_Continue_WithLodger_ButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Continue - I don&apos;t have any lodger to add.
        /// </summary>
        public static string Property_AddNameOfLodger_Continue_WithNoLodger_ButtonText {
            get {
                return ResourceManager.GetString("Property_AddNameOfLodger_Continue_WithNoLodger_ButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete this lodger?.
        /// </summary>
        public static string Property_AddNameOfLodger_Delete_Confirmation_Message {
            get {
                return ResourceManager.GetString("Property_AddNameOfLodger_Delete_Confirmation_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First name.
        /// </summary>
        public static string Property_AddNameOfLodger_Label_FirstName {
            get {
                return ResourceManager.GetString("Property_AddNameOfLodger_Label_FirstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last name.
        /// </summary>
        public static string Property_AddNameOfLodger_Label_LastName {
            get {
                return ResourceManager.GetString("Property_AddNameOfLodger_Label_LastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We need to know about all the lodgers who live at {0}..
        /// </summary>
        public static string Property_AddNameOfLodger_Page_Hint {
            get {
                return ResourceManager.GetString("Property_AddNameOfLodger_Page_Hint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter the lodger&apos;s first and last name.
        /// </summary>
        public static string Property_AddNameOfLodger_Page_SubHeading {
            get {
                return ResourceManager.GetString("Property_AddNameOfLodger_Page_SubHeading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Property lodgers.
        /// </summary>
        public static string Property_AddNameOfLodger_Page_Title {
            get {
                return ResourceManager.GetString("Property_AddNameOfLodger_Page_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to For example, John Smith..
        /// </summary>
        public static string Property_AddNameOfLodger_SubHeading_Hint {
            get {
                return ResourceManager.GetString("Property_AddNameOfLodger_SubHeading_Hint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;p&gt;&lt;span class=&quot;repeat&quot;&gt;The table above summarises the lodgers you have told us about.&lt;/span&gt;&lt;/p&gt;
        ///&lt;p&gt;&lt;span class=&quot;repeat&quot;&gt;We need to know about any other lodgers who live at {0}.&lt;/span&gt;&lt;/p&gt;.
        /// </summary>
        public static string Property_AddNameOfLodger_Summary_Para {
            get {
                return ResourceManager.GetString("Property_AddNameOfLodger_Summary_Para", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Coming soon...
        /// </summary>
        public static string Property_AddNameOfLodger_SummaryPage_Title {
            get {
                return ResourceManager.GetString("Property_AddNameOfLodger_SummaryPage_Title", resourceCulture);
            }
        }
    }
}
