//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace INSS.ODS.Bankruptcy.API.Common.Resources.Property {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AddNameOfTenantResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AddNameOfTenantResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("INSS.ODS.Bankruptcy.API.Common.Resources.Property.AddNameOfTenantResources", typeof(AddNameOfTenantResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to tenant.
        /// </summary>
        public static string Property_AddNameOfTenant__DeleteConfirmation_Tenant {
            get {
                return ResourceManager.GetString("Property_AddNameOfTenant__DeleteConfirmation_Tenant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add name.
        /// </summary>
        public static string Property_AddNameOfTenant_AddTenant_ButtonText {
            get {
                return ResourceManager.GetString("Property_AddNameOfTenant_AddTenant_ButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add another name.
        /// </summary>
        public static string Property_AddNameOfTenant_AddTenant_ButtonText_Alt {
            get {
                return ResourceManager.GetString("Property_AddNameOfTenant_AddTenant_ButtonText_Alt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back.
        /// </summary>
        public static string Property_AddNameOfTenant_Back_ButtonText {
            get {
                return ResourceManager.GetString("Property_AddNameOfTenant_Back_ButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to save tenant details due to server error. Please try again later..
        /// </summary>
        public static string Property_AddNameOfTenant_Continue_Error_ServerError {
            get {
                return ResourceManager.GetString("Property_AddNameOfTenant_Continue_Error_ServerError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to add the tenant you typed in below? To add this tenant, please select the green &apos;Add tenant&apos;.
        /// </summary>
        public static string Property_AddNameOfTenant_Continue_Error_WithNameTyped {
            get {
                return ResourceManager.GetString("Property_AddNameOfTenant_Continue_Error_WithNameTyped", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Continue - I don&apos;t have any tenant to add.
        /// </summary>
        public static string Property_AddNameOfTenant_Continue_WithNoTenant_ButtonText {
            get {
                return ResourceManager.GetString("Property_AddNameOfTenant_Continue_WithNoTenant_ButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Continue - I have added all my tenants.
        /// </summary>
        public static string Property_AddNameOfTenant_Continue_WithTenant_ButtonText {
            get {
                return ResourceManager.GetString("Property_AddNameOfTenant_Continue_WithTenant_ButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First name.
        /// </summary>
        public static string Property_AddNameOfTenant_Label_FirstName {
            get {
                return ResourceManager.GetString("Property_AddNameOfTenant_Label_FirstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last name.
        /// </summary>
        public static string Property_AddNameOfTenant_Label_LastName {
            get {
                return ResourceManager.GetString("Property_AddNameOfTenant_Label_LastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We need to know about all the tenants who are listed on the tenancy agreement for {0}..
        /// </summary>
        public static string Property_AddNameOfTenant_Page_Hint {
            get {
                return ResourceManager.GetString("Property_AddNameOfTenant_Page_Hint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter a tenant&apos;s first and last name.
        /// </summary>
        public static string Property_AddNameOfTenant_Page_SubHeading {
            get {
                return ResourceManager.GetString("Property_AddNameOfTenant_Page_SubHeading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Property tenants.
        /// </summary>
        public static string Property_AddNameOfTenant_Page_Title {
            get {
                return ResourceManager.GetString("Property_AddNameOfTenant_Page_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to For example, John Smith..
        /// </summary>
        public static string Property_AddNameOfTenant_SubHeading_Hint {
            get {
                return ResourceManager.GetString("Property_AddNameOfTenant_SubHeading_Hint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;p&gt;&lt;span class=&quot;repeat&quot;&gt;The table above summarises the tenants you have told us about.&lt;/span&gt;&lt;/p&gt;&lt;p&gt;&lt;span class=&quot;repeat&quot;&gt;We need to know about any other tenants who are listed on the tenancy agreement for {0}.&lt;/span&gt;&lt;/p&gt;.
        /// </summary>
        public static string Property_AddNameOfTenant_Summary_Para {
            get {
                return ResourceManager.GetString("Property_AddNameOfTenant_Summary_Para", resourceCulture);
            }
        }
    }
}
