//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace INSS.ODS.Bankruptcy.API.Common.Resources.Property {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AddPropertyResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AddPropertyResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("INSS.ODS.Bankruptcy.API.Common.Resources.Property.AddPropertyResources", typeof(AddPropertyResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add property.
        /// </summary>
        public static string Property_AddProperty_Add_ButtonText {
            get {
                return ResourceManager.GetString("Property_AddProperty_Add_ButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add another property.
        /// </summary>
        public static string Property_AddProperty_Add_ButtonText_Alt {
            get {
                return ResourceManager.GetString("Property_AddProperty_Add_ButtonText_Alt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back.
        /// </summary>
        public static string Property_AddProperty_Back_ButtonText {
            get {
                return ResourceManager.GetString("Property_AddProperty_Back_ButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Continue - I have added all my properties.
        /// </summary>
        public static string Property_AddProperty_ContinueAfterAddingProperty_ButtonText {
            get {
                return ResourceManager.GetString("Property_AddProperty_ContinueAfterAddingProperty_ButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Continue - I don&apos;t have any property to add.
        /// </summary>
        public static string Property_AddProperty_ContinueNoProperty_ButtonText {
            get {
                return ResourceManager.GetString("Property_AddProperty_ContinueNoProperty_ButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to property.
        /// </summary>
        public static string Property_AddProperty_DeleteMessage_ObjectName {
            get {
                return ResourceManager.GetString("Property_AddProperty_DeleteMessage_ObjectName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter either Firstline or Postalcode of the address..
        /// </summary>
        public static string Property_AddProperty_Error_AnyOneFieldRequired {
            get {
                return ResourceManager.GetString("Property_AddProperty_Error_AnyOneFieldRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to add the property you typed in below? To add this property, please select the green &apos;Add property&apos; button..
        /// </summary>
        public static string Property_AddProperty_Error_ContinueButtonPressedWithData {
            get {
                return ResourceManager.GetString("Property_AddProperty_Error_ContinueButtonPressedWithData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First line.
        /// </summary>
        public static string Property_AddProperty_FirstLine_Label {
            get {
                return ResourceManager.GetString("Property_AddProperty_FirstLine_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We need to know about any properties you own or have a financial interest in..
        /// </summary>
        public static string Property_AddProperty_Page_Desc1 {
            get {
                return ResourceManager.GetString("Property_AddProperty_Page_Desc1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Telling us about a property doesn’t necessarily mean it will be sold - it&apos;ll depend on how much equity you have..
        /// </summary>
        public static string Property_AddProperty_Page_Desc2 {
            get {
                return ResourceManager.GetString("Property_AddProperty_Page_Desc2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Equity is the total value of your property minus what&apos;s left on your mortgage and any secured loans or charges..
        /// </summary>
        public static string Property_AddProperty_Page_Desc3 {
            get {
                return ResourceManager.GetString("Property_AddProperty_Page_Desc3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter the first line of the property’s address and postal code.
        /// </summary>
        public static string Property_AddProperty_Page_SubHeader {
            get {
                return ResourceManager.GetString("Property_AddProperty_Page_SubHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Properties.
        /// </summary>
        public static string Property_AddProperty_Page_Title {
            get {
                return ResourceManager.GetString("Property_AddProperty_Page_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;p&gt;&lt;span class=&quot;firsttime&quot;&gt;Telling us about a property doesn’t necessarily mean it will be sold - it&apos;ll depend on how much equity 
        ///you have.&lt;/span&gt;&lt;/p&gt;&lt;p&gt;&lt;span class=&quot;firsttime&quot;&gt;Equity is the total value of your property minus what&apos;s left on your mortgage and any secured loans or charges.&lt;/span&gt;&lt;/p&gt;.
        /// </summary>
        public static string Property_AddProperty_PageWithoutSummary_Hint {
            get {
                return ResourceManager.GetString("Property_AddProperty_PageWithoutSummary_Hint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Postal code.
        /// </summary>
        public static string Property_AddProperty_Postalcode_Label {
            get {
                return ResourceManager.GetString("Property_AddProperty_Postalcode_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to For example, 12 Place Street NG6 8RG. You can add more properties later..
        /// </summary>
        public static string Property_AddProperty_SubHeader_Hint {
            get {
                return ResourceManager.GetString("Property_AddProperty_SubHeader_Hint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address.
        /// </summary>
        public static string Property_AddProperty_SummaryColumn_Address {
            get {
                return ResourceManager.GetString("Property_AddProperty_SummaryColumn_Address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jointly owned.
        /// </summary>
        public static string Property_AddProperty_SummaryColumn_JointlyOwned {
            get {
                return ResourceManager.GetString("Property_AddProperty_SummaryColumn_JointlyOwned", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your interest in the property.
        /// </summary>
        public static string Property_AddProperty_SummaryColumn_Value {
            get {
                return ResourceManager.GetString("Property_AddProperty_SummaryColumn_Value", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;p&gt;&lt;span class=&quot;repeat&quot;&gt;The table above summarises all the properties you have told us about.&lt;/span&gt;&lt;/p&gt;
        ///                         &lt;p&gt;&lt;span class=&quot;repeat&quot;&gt;We need to know about any other properties you own or have a financial interest in.&lt;/span&gt;&lt;/p&gt;.
        /// </summary>
        public static string Property_AddProperty_SummaryTable_Hint {
            get {
                return ResourceManager.GetString("Property_AddProperty_SummaryTable_Hint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        public static string Property_PropertyDetails_RadioOption_No {
            get {
                return ResourceManager.GetString("Property_PropertyDetails_RadioOption_No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        public static string Property_PropertyDetails_RadioOption_Yes {
            get {
                return ResourceManager.GetString("Property_PropertyDetails_RadioOption_Yes", resourceCulture);
            }
        }
    }
}
