//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace INSS.ODS.Bankruptcy.API.Common.Resources.Property {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class IncomeFromTenantResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal IncomeFromTenantResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("INSS.ODS.Bankruptcy.API.Common.Resources.Property.IncomeFromTenantResources", typeof(IncomeFromTenantResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter lesser value..
        /// </summary>
        public static string Property_IncomeFromTenant_Amount_Error_EnterLessValue {
            get {
                return ResourceManager.GetString("Property_IncomeFromTenant_Amount_Error_EnterLessValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter the income amount..
        /// </summary>
        public static string Property_IncomeFromTenant_Amount_Error_Mandatory {
            get {
                return ResourceManager.GetString("Property_IncomeFromTenant_Amount_Error_Mandatory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter a valid amount..
        /// </summary>
        public static string Property_IncomeFromTenant_Amount_Error_NumberDecimalOnly {
            get {
                return ResourceManager.GetString("Property_IncomeFromTenant_Amount_Error_NumberDecimalOnly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter a value above zero for the income amount..
        /// </summary>
        public static string Property_IncomeFromTenant_Amount_Error_PositiveValueOnly {
            get {
                return ResourceManager.GetString("Property_IncomeFromTenant_Amount_Error_PositiveValueOnly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please use the correct format, eg £120.50.
        /// </summary>
        public static string Property_IncomeFromTenant_Amount_Error_Scale {
            get {
                return ResourceManager.GetString("Property_IncomeFromTenant_Amount_Error_Scale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please provide the total rental income.
        /// </summary>
        public static string Property_IncomeFromTenant_Amount_Hint {
            get {
                return ResourceManager.GetString("Property_IncomeFromTenant_Amount_Hint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to How much is the rent for {0}?.
        /// </summary>
        public static string Property_IncomeFromTenant_Amount_Label {
            get {
                return ResourceManager.GetString("Property_IncomeFromTenant_Amount_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back.
        /// </summary>
        public static string Property_IncomeFromTenant_Back_ButtonText {
            get {
                return ResourceManager.GetString("Property_IncomeFromTenant_Back_ButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Continue.
        /// </summary>
        public static string Property_IncomeFromTenant_Continue_ButtonText {
            get {
                return ResourceManager.GetString("Property_IncomeFromTenant_Continue_ButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select if you are using managing agent..
        /// </summary>
        public static string Property_IncomeFromTenant_ManagingAgent_Error_Mandatory {
            get {
                return ResourceManager.GetString("Property_IncomeFromTenant_ManagingAgent_Error_Mandatory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you use a managing agent?.
        /// </summary>
        public static string Property_IncomeFromTenant_ManagingAgent_Label {
            get {
                return ResourceManager.GetString("Property_IncomeFromTenant_ManagingAgent_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        public static string Property_IncomeFromTenant_ManagingAgent_No {
            get {
                return ResourceManager.GetString("Property_IncomeFromTenant_ManagingAgent_No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        public static string Property_IncomeFromTenant_ManagingAgent_Yes {
            get {
                return ResourceManager.GetString("Property_IncomeFromTenant_ManagingAgent_Yes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Income from tenants.
        /// </summary>
        public static string Property_IncomeFromTenant_Page_Title {
            get {
                return ResourceManager.GetString("Property_IncomeFromTenant_Page_Title", resourceCulture);
            }
        }
    }
}
