//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace INSS.ODS.Bankruptcy.API.Common.Resources.Property {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class JointOwnerNameResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal JointOwnerNameResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("INSS.ODS.Bankruptcy.API.Common.Resources.Property.JointOwnerNameResources", typeof(JointOwnerNameResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add joint owner.
        /// </summary>
        public static string Property_JointOwnerName_Add_Buttontext {
            get {
                return ResourceManager.GetString("Property_JointOwnerName_Add_Buttontext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter another joint owner&apos;s name.
        /// </summary>
        public static string Property_JointOwnerName_AnotherName_SubHeading {
            get {
                return ResourceManager.GetString("Property_JointOwnerName_AnotherName_SubHeading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back.
        /// </summary>
        public static string Property_JointOwnerName_Back_Buttontext {
            get {
                return ResourceManager.GetString("Property_JointOwnerName_Back_Buttontext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Continue - I have added all joint owners.
        /// </summary>
        public static string Property_JointOwnerName_Continue_AfterAddingJointOwner {
            get {
                return ResourceManager.GetString("Property_JointOwnerName_Continue_AfterAddingJointOwner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to add the joint owner you typed in below? To add this joint owner, please select the green &apos;Add joint owner&apos; button..
        /// </summary>
        public static string Property_JointOwnerName_Continue_Error_WhenBenficiaryNameTyped {
            get {
                return ResourceManager.GetString("Property_JointOwnerName_Continue_Error_WhenBenficiaryNameTyped", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Continue - I am the sole owner.
        /// </summary>
        public static string Property_JointOwnerName_Continue_HasNoJointOwner {
            get {
                return ResourceManager.GetString("Property_JointOwnerName_Continue_HasNoJointOwner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to property joint owner.
        /// </summary>
        public static string Property_JointOwnerName_DeleteConfirmation_JointOwner {
            get {
                return ResourceManager.GetString("Property_JointOwnerName_DeleteConfirmation_JointOwner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please check the first name. Your answer can only use letters (A-Z), spaces, hyphens (-) and apostrophes (&apos;)..
        /// </summary>
        public static string Property_JointOwnerName_FirstName_Error_InvalidLetters {
            get {
                return ResourceManager.GetString("Property_JointOwnerName_FirstName_Error_InvalidLetters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The first name is too long. Please answer in less than 71 characters..
        /// </summary>
        public static string Property_JointOwnerName_FirstName_Error_Length {
            get {
                return ResourceManager.GetString("Property_JointOwnerName_FirstName_Error_Length", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter a first name.
        /// </summary>
        public static string Property_JointOwnerName_FirstName_Error_Mandatory {
            get {
                return ResourceManager.GetString("Property_JointOwnerName_FirstName_Error_Mandatory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First name.
        /// </summary>
        public static string Property_JointOwnerName_FirstName_Label {
            get {
                return ResourceManager.GetString("Property_JointOwnerName_FirstName_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You.
        /// </summary>
        public static string Property_JointOwnerName_Label_For_Your_Share {
            get {
                return ResourceManager.GetString("Property_JointOwnerName_Label_For_Your_Share", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The last name is too long. Please answer in less than 36 characters..
        /// </summary>
        public static string Property_JointOwnerName_LasName_Error_Length {
            get {
                return ResourceManager.GetString("Property_JointOwnerName_LasName_Error_Length", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please check the last name. Your answer can only use letters (A-Z), spaces, hyphens (-) and apostrophes (&apos;)..
        /// </summary>
        public static string Property_JointOwnerName_LastName_Error_InvalidLetters {
            get {
                return ResourceManager.GetString("Property_JointOwnerName_LastName_Error_InvalidLetters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter a last name..
        /// </summary>
        public static string Property_JointOwnerName_LastName_Error_Mandatory {
            get {
                return ResourceManager.GetString("Property_JointOwnerName_LastName_Error_Mandatory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last name.
        /// </summary>
        public static string Property_JointOwnerName_LastName_Label {
            get {
                return ResourceManager.GetString("Property_JointOwnerName_LastName_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter either a first or last name.
        /// </summary>
        public static string Property_JointOwnerName_Name_Error_Mandatory {
            get {
                return ResourceManager.GetString("Property_JointOwnerName_Name_Error_Mandatory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to For example, John Smith..
        /// </summary>
        public static string Property_JointOwnerName_Names_Hint {
            get {
                return ResourceManager.GetString("Property_JointOwnerName_Names_Hint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter the joint owner&apos;s name.
        /// </summary>
        public static string Property_JointOwnerName_Names_SubHeading {
            get {
                return ResourceManager.GetString("Property_JointOwnerName_Names_SubHeading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We need to know about any joint owners of &lt;strong&gt;{0}&lt;/strong&gt;..
        /// </summary>
        public static string Property_JointOwnerName_Page_Intro {
            get {
                return ResourceManager.GetString("Property_JointOwnerName_Page_Intro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Joint owners.
        /// </summary>
        public static string Property_JointOwnerName_Page_Title {
            get {
                return ResourceManager.GetString("Property_JointOwnerName_Page_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;p&gt;&lt;span class=&quot;repeat&quot;&gt;The table above summarises the joint owners you have told us about.&lt;/span&gt;&lt;/p&gt; 
        ///&lt;p&gt;&lt;span class=&quot;repeat&quot;&gt;We need to know about any other joint owners of&lt;strong&gt; {0}&lt;/strong&gt;.&lt;/span&gt;&lt;/p&gt;.
        /// </summary>
        public static string Property_JointOwnerName_Summary_Para {
            get {
                return ResourceManager.GetString("Property_JointOwnerName_Summary_Para", resourceCulture);
            }
        }
    }
}
