//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace INSS.ODS.Bankruptcy.API.Common.Resources.Property {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class MorePropertyDescriptionResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal MorePropertyDescriptionResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("INSS.ODS.Bankruptcy.API.Common.Resources.Property.MorePropertyDescriptionResources", typeof(MorePropertyDescriptionResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back.
        /// </summary>
        public static string Property_MorePropertyDescription_Back_ButtonText {
            get {
                return ResourceManager.GetString("Property_MorePropertyDescription_Back_ButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Continue.
        /// </summary>
        public static string Property_MorePropertyDescription_Continue_ButtonText {
            get {
                return ResourceManager.GetString("Property_MorePropertyDescription_Continue_ButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter a date that isn&apos;t in the future..
        /// </summary>
        public static string Property_MorePropertyDescription_Date_Error_FutureDateNotAllowed {
            get {
                return ResourceManager.GetString("Property_MorePropertyDescription_Date_Error_FutureDateNotAllowed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter the financial interest start date that is after 01/01/1900..
        /// </summary>
        public static string Property_MorePropertyDescription_Date_Error_MinimumDate {
            get {
                return ResourceManager.GetString("Property_MorePropertyDescription_Date_Error_MinimumDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter the date you purchased or started having a financial interest in the property..
        /// </summary>
        public static string Property_MorePropertyDescription_Date_Error_Required {
            get {
                return ResourceManager.GetString("Property_MorePropertyDescription_Date_Error_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I don&apos;t know.
        /// </summary>
        public static string Property_MorePropertyDescription_IsShared_DoNotKnow {
            get {
                return ResourceManager.GetString("Property_MorePropertyDescription_IsShared_DoNotKnow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select if the property is part of a shared ownership scheme.
        /// </summary>
        public static string Property_MorePropertyDescription_IsShared_Error_Required {
            get {
                return ResourceManager.GetString("Property_MorePropertyDescription_IsShared_Error_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shared ownership schemes involve you buying a share of a property and paying rent to a housing association for the rest.
        /// </summary>
        public static string Property_MorePropertyDescription_IsShared_Hint {
            get {
                return ResourceManager.GetString("Property_MorePropertyDescription_IsShared_Hint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is {0} part of a shared ownership scheme?.
        /// </summary>
        public static string Property_MorePropertyDescription_IsShared_Label {
            get {
                return ResourceManager.GetString("Property_MorePropertyDescription_IsShared_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        public static string Property_MorePropertyDescription_IsShared_No {
            get {
                return ResourceManager.GetString("Property_MorePropertyDescription_IsShared_No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        public static string Property_MorePropertyDescription_IsShared_Yes {
            get {
                return ResourceManager.GetString("Property_MorePropertyDescription_IsShared_Yes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Beneficial interest only.
        /// </summary>
        public static string Property_MorePropertyDescription_NatureOfInterest_BenefialInterestOnly {
            get {
                return ResourceManager.GetString("Property_MorePropertyDescription_NatureOfInterest_BenefialInterestOnly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select the nature of your interest in the property..
        /// </summary>
        public static string Property_MorePropertyDescription_NatureOfInterest_Error_Mandatory {
            get {
                return ResourceManager.GetString("Property_MorePropertyDescription_NatureOfInterest_Error_Mandatory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Joint owner.
        /// </summary>
        public static string Property_MorePropertyDescription_NatureOfInterest_JointOwner {
            get {
                return ResourceManager.GetString("Property_MorePropertyDescription_NatureOfInterest_JointOwner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What is the nature of your interest in the property?.
        /// </summary>
        public static string Property_MorePropertyDescription_NatureOfInterest_Label {
            get {
                return ResourceManager.GetString("Property_MorePropertyDescription_NatureOfInterest_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Other.
        /// </summary>
        public static string Property_MorePropertyDescription_NatureOfInterest_Other {
            get {
                return ResourceManager.GetString("Property_MorePropertyDescription_NatureOfInterest_Other", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sole owner.
        /// </summary>
        public static string Property_MorePropertyDescription_NatureOfInterest_SoleOwner {
            get {
                return ResourceManager.GetString("Property_MorePropertyDescription_NatureOfInterest_SoleOwner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The length of &quot;Other&quot; field is not valid. Allowed length is minimum 3 and maximum 60 characters.
        /// </summary>
        public static string Property_MorePropertyDescription_NatureOfInterestOther_Error_Length {
            get {
                return ResourceManager.GetString("Property_MorePropertyDescription_NatureOfInterestOther_Error_Length", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter the value for the &quot;Other&quot; field..
        /// </summary>
        public static string Property_MorePropertyDescription_NatureOfInterestOther_Error_Mandatory {
            get {
                return ResourceManager.GetString("Property_MorePropertyDescription_NatureOfInterestOther_Error_Mandatory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Property description.
        /// </summary>
        public static string Property_MorePropertyDescription_Page_Title {
            get {
                return ResourceManager.GetString("Property_MorePropertyDescription_Page_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to For example, Aug 2015.
        /// </summary>
        public static string Property_MorePropertyDescription_PurchaseDate_Hint {
            get {
                return ResourceManager.GetString("Property_MorePropertyDescription_PurchaseDate_Hint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to When did you purchase or start having a financial interest in the property?.
        /// </summary>
        public static string Property_MorePropertyDescription_PurchaseDate_Label {
            get {
                return ResourceManager.GetString("Property_MorePropertyDescription_PurchaseDate_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter a value greater than zero..
        /// </summary>
        public static string Property_MorePropertyDescription_Worth_Error_AboveZero {
            get {
                return ResourceManager.GetString("Property_MorePropertyDescription_Worth_Error_AboveZero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please use the correct format, eg £120.50.
        /// </summary>
        public static string Property_MorePropertyDescription_Worth_Error_DecimalPlaces {
            get {
                return ResourceManager.GetString("Property_MorePropertyDescription_Worth_Error_DecimalPlaces", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter how much the property is currently worth.
        /// </summary>
        public static string Property_MorePropertyDescription_Worth_Error_Mandatory {
            get {
                return ResourceManager.GetString("Property_MorePropertyDescription_Worth_Error_Mandatory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter a value above zero for the current worth of the property..
        /// </summary>
        public static string Property_MorePropertyDescription_Worth_Error_PositiveValueOnly {
            get {
                return ResourceManager.GetString("Property_MorePropertyDescription_Worth_Error_PositiveValueOnly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please provide the most accurate figure you can
        ///If {0} is part of a shared ownership scheme, we only need to know the value of your share of the property.
        /// </summary>
        public static string Property_MorePropertyDescription_Worth_Hint {
            get {
                return ResourceManager.GetString("Property_MorePropertyDescription_Worth_Hint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please provide the most accurate figure you can.
        /// </summary>
        public static string Property_MorePropertyDescription_Worth_Hint1 {
            get {
                return ResourceManager.GetString("Property_MorePropertyDescription_Worth_Hint1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If {0} is part of a shared ownership scheme, we only need to know the value of your share of the property.
        /// </summary>
        public static string Property_MorePropertyDescription_Worth_Hint2 {
            get {
                return ResourceManager.GetString("Property_MorePropertyDescription_Worth_Hint2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to How much is {0} currently worth?.
        /// </summary>
        public static string Property_MorePropertyDescription_Worth_Label {
            get {
                return ResourceManager.GetString("Property_MorePropertyDescription_Worth_Label", resourceCulture);
            }
        }
    }
}
