//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace INSS.ODS.Bankruptcy.API.Common.Resources.Property {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class PropertyDebtDetailsResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal PropertyDebtDetailsResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("INSS.ODS.Bankruptcy.API.Common.Resources.Property.PropertyDebtDetailsResources", typeof(PropertyDebtDetailsResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter the amount you owe..
        /// </summary>
        public static string Property_PropertyDebtDetails_AmountOwe_Error_Mandatory {
            get {
                return ResourceManager.GetString("Property_PropertyDebtDetails_AmountOwe_Error_Mandatory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter a value above zero for the amount you owe to creditor..
        /// </summary>
        public static string Property_PropertyDebtDetails_AmountOwe_Error_PositiveValueOnly {
            get {
                return ResourceManager.GetString("Property_PropertyDebtDetails_AmountOwe_Error_PositiveValueOnly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please use the correct format, eg £120.50.
        /// </summary>
        public static string Property_PropertyDebtDetails_AmountOwe_Error_Scale {
            get {
                return ResourceManager.GetString("Property_PropertyDebtDetails_AmountOwe_Error_Scale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to How much does the creditor say you currently owe?.
        /// </summary>
        public static string Property_PropertyDebtDetails_AmountOwe_Label {
            get {
                return ResourceManager.GetString("Property_PropertyDebtDetails_AmountOwe_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back.
        /// </summary>
        public static string Property_PropertyDebtDetails_Back_ButtonText {
            get {
                return ResourceManager.GetString("Property_PropertyDebtDetails_Back_ButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Continue.
        /// </summary>
        public static string Property_PropertyDebtDetails_Continue_ButtonText {
            get {
                return ResourceManager.GetString("Property_PropertyDebtDetails_Continue_ButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The creditor name can contain letters and numbers only.
        /// </summary>
        public static string Property_PropertyDebtDetails_CreditorName_Error_AlphaNumericOnly {
            get {
                return ResourceManager.GetString("Property_PropertyDebtDetails_CreditorName_Error_AlphaNumericOnly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The creditor name must be between 3 and 100 characters long..
        /// </summary>
        public static string Property_PropertyDebtDetails_CreditorName_Error_Length {
            get {
                return ResourceManager.GetString("Property_PropertyDebtDetails_CreditorName_Error_Length", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter the creditor name.
        /// </summary>
        public static string Property_PropertyDebtDetails_CreditorName_Error_Required {
            get {
                return ResourceManager.GetString("Property_PropertyDebtDetails_CreditorName_Error_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Of the creditor.
        /// </summary>
        public static string Property_PropertyDebtDetails_CreditorName_Hint {
            get {
                return ResourceManager.GetString("Property_PropertyDebtDetails_CreditorName_Hint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string Property_PropertyDebtDetails_CreditorName_Label {
            get {
                return ResourceManager.GetString("Property_PropertyDebtDetails_CreditorName_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You cannot enter a future date for debt start date.
        /// </summary>
        public static string Property_PropertyDebtDetails_DebtStartDate_Error_FutureDateNotAllowed {
            get {
                return ResourceManager.GetString("Property_PropertyDebtDetails_DebtStartDate_Error_FutureDateNotAllowed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter a debt start date that is after 01/01/1900.
        /// </summary>
        public static string Property_PropertyDebtDetails_DebtStartDate_Error_MinDateRequirement {
            get {
                return ResourceManager.GetString("Property_PropertyDebtDetails_DebtStartDate_Error_MinDateRequirement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter the debt start date.
        /// </summary>
        public static string Property_PropertyDebtDetails_DebtStartDate_Error_Required {
            get {
                return ResourceManager.GetString("Property_PropertyDebtDetails_DebtStartDate_Error_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to For &lt;b&gt;mortgages and secured loans&lt;/b&gt;, enter the date you received the money&lt;br/&gt;For &lt;b&gt;charges&lt;/b&gt;, enter the date the charge was made.
        /// </summary>
        public static string Property_PropertyDebtDetails_DebtStartDate_Hint1 {
            get {
                return ResourceManager.GetString("Property_PropertyDebtDetails_DebtStartDate_Hint1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to For charges, enter the date the charge was made.
        /// </summary>
        public static string Property_PropertyDebtDetails_DebtStartDate_Hint2 {
            get {
                return ResourceManager.GetString("Property_PropertyDebtDetails_DebtStartDate_Hint2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date the debt started.
        /// </summary>
        public static string Property_PropertyDebtDetails_DebtStartDate_Label {
            get {
                return ResourceManager.GetString("Property_PropertyDebtDetails_DebtStartDate_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Charge.
        /// </summary>
        public static string Property_PropertyDebtDetails_DebtType_Charge {
            get {
                return ResourceManager.GetString("Property_PropertyDebtDetails_DebtType_Charge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select the debt type.
        /// </summary>
        public static string Property_PropertyDebtDetails_DebtType_Error_Required {
            get {
                return ResourceManager.GetString("Property_PropertyDebtDetails_DebtType_Error_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type of debt.
        /// </summary>
        public static string Property_PropertyDebtDetails_DebtType_Label {
            get {
                return ResourceManager.GetString("Property_PropertyDebtDetails_DebtType_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Secured loan.
        /// </summary>
        public static string Property_PropertyDebtDetails_DebtType_Loan {
            get {
                return ResourceManager.GetString("Property_PropertyDebtDetails_DebtType_Loan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mortgage.
        /// </summary>
        public static string Property_PropertyDebtDetails_DebtType_Mortgage {
            get {
                return ResourceManager.GetString("Property_PropertyDebtDetails_DebtType_Mortgage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select if it&apos;s a joint debt.
        /// </summary>
        public static string Property_PropertyDebtDetails_IsJointDebt_Error_Required {
            get {
                return ResourceManager.GetString("Property_PropertyDebtDetails_IsJointDebt_Error_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is it a joint debt?.
        /// </summary>
        public static string Property_PropertyDebtDetails_IsJointDebt_Label {
            get {
                return ResourceManager.GetString("Property_PropertyDebtDetails_IsJointDebt_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Secured debt details.
        /// </summary>
        public static string Property_PropertyDebtDetails_Page_Title {
            get {
                return ResourceManager.GetString("Property_PropertyDebtDetails_Page_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes - with another person.
        /// </summary>
        public static string Property_PropertyDebtDetails_RadioOption_YesWithAnotherPerson {
            get {
                return ResourceManager.GetString("Property_PropertyDebtDetails_RadioOption_YesWithAnotherPerson", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes - with {0}.
        /// </summary>
        public static string Property_PropertyDebtDetails_RadioOption_YesWithJointOwners {
            get {
                return ResourceManager.GetString("Property_PropertyDebtDetails_RadioOption_YesWithJointOwners", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The reference number must be between 2 and 60 characters long..
        /// </summary>
        public static string Property_PropertyDebtDetails_RefNo_Error_Length {
            get {
                return ResourceManager.GetString("Property_PropertyDebtDetails_RefNo_Error_Length", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter the Reference number.
        /// </summary>
        public static string Property_PropertyDebtDetails_RefNo_Error_Required {
            get {
                return ResourceManager.GetString("Property_PropertyDebtDetails_RefNo_Error_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to For &lt;b&gt;mortgages and secured loans&lt;/b&gt;, you can find this on your annual statement&lt;br/&gt;For &lt;b&gt;charges&lt;/b&gt;, you can find this on the paperwork you received when the charge was made &lt;br/&gt;Leave blank if you don&apos;t have one.
        /// </summary>
        public static string Property_PropertyDebtDetails_RefNo_Hint1 {
            get {
                return ResourceManager.GetString("Property_PropertyDebtDetails_RefNo_Hint1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to For charges, you can find this on the paperwork you received when the charge was made.
        /// </summary>
        public static string Property_PropertyDebtDetails_RefNo_Hint2 {
            get {
                return ResourceManager.GetString("Property_PropertyDebtDetails_RefNo_Hint2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Leave blank if you don&apos;t have one.
        /// </summary>
        public static string Property_PropertyDebtDetails_RefNo_Hint3 {
            get {
                return ResourceManager.GetString("Property_PropertyDebtDetails_RefNo_Hint3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reference number.
        /// </summary>
        public static string Property_PropertyDebtDetails_RefNo_Label {
            get {
                return ResourceManager.GetString("Property_PropertyDebtDetails_RefNo_Label", resourceCulture);
            }
        }
    }
}
