//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace INSS.ODS.Bankruptcy.API.Common.Resources.Property {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class SelectSecuredDebtCreditorResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SelectSecuredDebtCreditorResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("INSS.ODS.Bankruptcy.API.Common.Resources.Property.SelectSecuredDebtCreditorResources", typeof(SelectSecuredDebtCreditorResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Continue - I don&apos;t have any secured debts.
        /// </summary>
        public static string Property_SelectSecuredDebtCreditor_Continue_NoSecuredDebts_Label {
            get {
                return ResourceManager.GetString("Property_SelectSecuredDebtCreditor_Continue_NoSecuredDebts_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Continue - I have added all my mortgages and secured debts.
        /// </summary>
        public static string Property_SelectSecuredDebtCreditor_Continue_SecuredDebtsAdded_Label {
            get {
                return ResourceManager.GetString("Property_SelectSecuredDebtCreditor_Continue_SecuredDebtsAdded_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mortgage and Secured Debts creditor search results.
        /// </summary>
        public static string Property_SelectSecuredDebtCreditor_SelectCreditor_PageTitle {
            get {
                return ResourceManager.GetString("Property_SelectSecuredDebtCreditor_SelectCreditor_PageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select the name of creditor..
        /// </summary>
        public static string Property_SelectSecuredDebtCreditor_SelectedCreditor_Error_Empty {
            get {
                return ResourceManager.GetString("Property_SelectSecuredDebtCreditor_SelectedCreditor_Error_Empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select the name of creditor from the list below.
        /// </summary>
        public static string Property_SelectSecuredDebtCreditor_SelectedCreditor_Label {
            get {
                return ResourceManager.GetString("Property_SelectSecuredDebtCreditor_SelectedCreditor_Label", resourceCulture);
            }
        }
    }
}
