//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace INSS.ODS.Bankruptcy.API.Common.Resources.PensionAndInsurance {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class OtherPolicyBeneficiariesResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal OtherPolicyBeneficiariesResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("INSS.ODS.Bankruptcy.API.Common.Resources.PensionAndInsurance.OtherPolicyBeneficiariesResou" +
                            "rces", typeof(OtherPolicyBeneficiariesResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add beneficiary.
        /// </summary>
        public static string PensionAndInsurance_OtherPolicyBeneficiaries_AddBeneficiaryButton_Label {
            get {
                return ResourceManager.GetString("PensionAndInsurance_OtherPolicyBeneficiaries_AddBeneficiaryButton_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First name.
        /// </summary>
        public static string PensionAndInsurance_OtherPolicyBeneficiaries_BenficiaryFirstName_Label {
            get {
                return ResourceManager.GetString("PensionAndInsurance_OtherPolicyBeneficiaries_BenficiaryFirstName_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last name.
        /// </summary>
        public static string PensionAndInsurance_OtherPolicyBeneficiaries_BenficiaryLastName_Label {
            get {
                return ResourceManager.GetString("PensionAndInsurance_OtherPolicyBeneficiaries_BenficiaryLastName_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to For example, John Smith. You can add more beneficiaries later..
        /// </summary>
        public static string PensionAndInsurance_OtherPolicyBeneficiaries_BenficiaryName_Hint {
            get {
                return ResourceManager.GetString("PensionAndInsurance_OtherPolicyBeneficiaries_BenficiaryName_Hint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter another beneficiary&apos;s first and last name.
        /// </summary>
        public static string PensionAndInsurance_OtherPolicyBeneficiaries_BenficiaryName_Label {
            get {
                return ResourceManager.GetString("PensionAndInsurance_OtherPolicyBeneficiaries_BenficiaryName_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;p&gt;&lt;span class=&quot;repeat&quot;&gt;We need to know about any other beneficaries of your policy with &lt;span class=&quot;company_name&quot;&gt;{0}&lt;/span&gt;.&lt;/span&gt;&lt;/p&gt;.
        /// </summary>
        public static string PensionAndInsurance_OtherPolicyBeneficiaries_CompanyNamePara {
            get {
                return ResourceManager.GetString("PensionAndInsurance_OtherPolicyBeneficiaries_CompanyNamePara", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to policy beneficiary.
        /// </summary>
        public static string PensionAndInsurance_OtherPolicyBeneficiaries_DeleteConfirmation_PolicyBeneficiary {
            get {
                return ResourceManager.GetString("PensionAndInsurance_OtherPolicyBeneficiaries_DeleteConfirmation_PolicyBeneficiary" +
                        "", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The sum of all beneficiary shares must be equal to 100%. Please edit beneficiary shares or add another beneficiary.  .
        /// </summary>
        public static string PensionAndInsurance_OtherPolicyBeneficiaries_Error_InvalidShares {
            get {
                return ResourceManager.GetString("PensionAndInsurance_OtherPolicyBeneficiaries_Error_InvalidShares", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Policy beneficiaries.
        /// </summary>
        public static string PensionAndInsurance_OtherPolicyBeneficiaries_PageTitle {
            get {
                return ResourceManager.GetString("PensionAndInsurance_OtherPolicyBeneficiaries_PageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;p&gt;&lt;span class=&quot;repeat&quot;&gt;The table above summarises the beneficiares you have told us about.&lt;/span&gt;&lt;/p&gt;.
        /// </summary>
        public static string PensionAndInsurance_OtherPolicyBeneficiaries_TablePara {
            get {
                return ResourceManager.GetString("PensionAndInsurance_OtherPolicyBeneficiaries_TablePara", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to save changes to the beneficiary shares due to server error. Please try again later..
        /// </summary>
        public static string PensionInsurance_OtherPolicyBeneficiaries_Continue_Error_ServerError {
            get {
                return ResourceManager.GetString("PensionInsurance_OtherPolicyBeneficiaries_Continue_Error_ServerError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to add the name of beneficiary you typed in below? To add this beneficiary, please select the green &apos;Add beneficiary&apos; button..
        /// </summary>
        public static string PensionInsurance_OtherPolicyBeneficiaries_Continue_Error_WhenBenficiaryNameTyped {
            get {
                return ResourceManager.GetString("PensionInsurance_OtherPolicyBeneficiaries_Continue_Error_WhenBenficiaryNameTyped", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Continue - I am the sole beneficiary.
        /// </summary>
        public static string PensionInsurance_OtherPolicyBeneficiaries_Continue_HasNoOtherBenficiaries_Label {
            get {
                return ResourceManager.GetString("PensionInsurance_OtherPolicyBeneficiaries_Continue_HasNoOtherBenficiaries_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Continue - I have added all beneficiaries.
        /// </summary>
        public static string PensionInsurance_OtherPolicyBeneficiaries_Continue_HasOtherBenficiaries_Label {
            get {
                return ResourceManager.GetString("PensionInsurance_OtherPolicyBeneficiaries_Continue_HasOtherBenficiaries_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You.
        /// </summary>
        public static string PensionInsurance_OtherPolicyBeneficiaries_Label_For_Your_Share {
            get {
                return ResourceManager.GetString("PensionInsurance_OtherPolicyBeneficiaries_Label_For_Your_Share", resourceCulture);
            }
        }
    }
}
