//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace INSS.ODS.Bankruptcy.API.Common.Resources.PensionAndInsurance {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class PolicyProviderDetailsResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal PolicyProviderDetailsResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("INSS.ODS.Bankruptcy.API.Common.Resources.PensionAndInsurance.PolicyProviderDetailsResource" +
                            "s", typeof(PolicyProviderDetailsResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pleases select the date the policy was taken out.
        /// </summary>
        public static string PensionAndInsurance_PolicyProviderDetails_CommencementDate {
            get {
                return ResourceManager.GetString("PensionAndInsurance_PolicyProviderDetails_CommencementDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select when the policy was taken out.
        /// </summary>
        public static string PensionAndInsurance_PolicyProviderDetails_CommencementDate_Error_Empty {
            get {
                return ResourceManager.GetString("PensionAndInsurance_PolicyProviderDetails_CommencementDate_Error_Empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Policy provider address.
        /// </summary>
        public static string PensionAndInsurance_PolicyProviderDetails_PageTitle {
            get {
                return ResourceManager.GetString("PensionAndInsurance_PolicyProviderDetails_PageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The policy reference number cannot be more than 30 characters.
        /// </summary>
        public static string PensionAndInsurance_PolicyProviderDetails_PolicyReferenceNo_TooLong {
            get {
                return ResourceManager.GetString("PensionAndInsurance_PolicyProviderDetails_PolicyReferenceNo_TooLong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What type of policy do you have with {0}.
        /// </summary>
        public static string PensionAndInsurance_PolicyProviderDetails_PolicyType {
            get {
                return ResourceManager.GetString("PensionAndInsurance_PolicyProviderDetails_PolicyType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please provide the policy type.
        /// </summary>
        public static string PensionAndInsurance_PolicyProviderDetails_PolicyType_Error_Empty {
            get {
                return ResourceManager.GetString("PensionAndInsurance_PolicyProviderDetails_PolicyType_Error_Empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please provide your policy type between 3 and 70 characters.
        /// </summary>
        public static string PensionAndInsurance_PolicyProviderDetails_PolicyType_TooLong_Or_Short {
            get {
                return ResourceManager.GetString("PensionAndInsurance_PolicyProviderDetails_PolicyType_TooLong_Or_Short", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address.
        /// </summary>
        public static string PensionAndInsurance_PolicyProviderDetails_ProviderAddress_Label {
            get {
                return ResourceManager.GetString("PensionAndInsurance_PolicyProviderDetails_ProviderAddress_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to When did you take out the policy?.
        /// </summary>
        public static string PensionAndInsurance_PolicyProviderDetails_ProviderCommencementDate_Label {
            get {
                return ResourceManager.GetString("PensionAndInsurance_PolicyProviderDetails_ProviderCommencementDate_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter the name of policy provider or broker..
        /// </summary>
        public static string PensionAndInsurance_PolicyProviderDetails_ProviderName_Error_Empty {
            get {
                return ResourceManager.GetString("PensionAndInsurance_PolicyProviderDetails_ProviderName_Error_Empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Provider name must have at least 3 letters and it cannot be longer than 50 letters..
        /// </summary>
        public static string PensionAndInsurance_PolicyProviderDetails_ProviderName_Error_InvalidLength {
            get {
                return ResourceManager.GetString("PensionAndInsurance_PolicyProviderDetails_ProviderName_Error_InvalidLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Of the policy provider or broker.
        /// </summary>
        public static string PensionAndInsurance_PolicyProviderDetails_ProviderName_Hint {
            get {
                return ResourceManager.GetString("PensionAndInsurance_PolicyProviderDetails_ProviderName_Hint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string PensionAndInsurance_PolicyProviderDetails_ProviderName_Label {
            get {
                return ResourceManager.GetString("PensionAndInsurance_PolicyProviderDetails_ProviderName_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can find this on any correspondence from your policy provider or broker
        ///Leave blank if you don&apos;t have one.
        /// </summary>
        public static string PensionAndInsurance_PolicyProviderDetails_ProviderPolicyRef_Hint {
            get {
                return ResourceManager.GetString("PensionAndInsurance_PolicyProviderDetails_ProviderPolicyRef_Hint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Policy reference number.
        /// </summary>
        public static string PensionAndInsurance_PolicyProviderDetails_ProviderPolicyRef_Label {
            get {
                return ResourceManager.GetString("PensionAndInsurance_PolicyProviderDetails_ProviderPolicyRef_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What type of policy is it?.
        /// </summary>
        public static string PensionAndInsurance_PolicyProviderDetails_ProviderPolicyType_Label {
            get {
                return ResourceManager.GetString("PensionAndInsurance_PolicyProviderDetails_ProviderPolicyType_Label", resourceCulture);
            }
        }
    }
}
