//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace INSS.ODS.Bankruptcy.API.Common.Resources.PensionAndInsurance {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class SummaryResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SummaryResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("INSS.ODS.Bankruptcy.API.Common.Resources.PensionAndInsurance.SummaryResources", typeof(SummaryResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add policy provider.
        /// </summary>
        public static string PensionAndInsurance_Summary_AddPolicyProviderButton_Label {
            get {
                return ResourceManager.GetString("PensionAndInsurance_Summary_AddPolicyProviderButton_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add another policy provider.
        /// </summary>
        public static string PensionAndInsurance_Summary_AddPolicyProviderButton_Label_Alt {
            get {
                return ResourceManager.GetString("PensionAndInsurance_Summary_AddPolicyProviderButton_Label_Alt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to policy.
        /// </summary>
        public static string PensionAndInsurance_Summary_DeleteConfirmation_ItemName {
            get {
                return ResourceManager.GetString("PensionAndInsurance_Summary_DeleteConfirmation_ItemName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;p&gt;The table above summarises the policies and pensions you have told us about. &lt;/p&gt;.
        /// </summary>
        public static string PensionAndInsurance_Summary_ExistingPolicies_Para_1 {
            get {
                return ResourceManager.GetString("PensionAndInsurance_Summary_ExistingPolicies_Para_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;p&gt;We need to know about any other pension, endowment or life insurance policies you currently have.&lt;/p&gt;.
        /// </summary>
        public static string PensionAndInsurance_Summary_ExistingPolicies_Para_2 {
            get {
                return ResourceManager.GetString("PensionAndInsurance_Summary_ExistingPolicies_Para_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;p&gt;We need to know about all the pension, endowment and life insurance policies you currently have.&lt;/p&gt;.
        /// </summary>
        public static string PensionAndInsurance_Summary_NoExistingPolicies_Para_1 {
            get {
                return ResourceManager.GetString("PensionAndInsurance_Summary_NoExistingPolicies_Para_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;p&gt;Don&apos;t include your State Pension or any policies you have cashed in, transferred, or given away - we&apos;ll ask you about these later.&lt;/p&gt;.
        /// </summary>
        public static string PensionAndInsurance_Summary_NoExistingPolicies_Para_2 {
            get {
                return ResourceManager.GetString("PensionAndInsurance_Summary_NoExistingPolicies_Para_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pensions and insurance.
        /// </summary>
        public static string PensionAndInsurance_Summary_PageTitle {
            get {
                return ResourceManager.GetString("PensionAndInsurance_Summary_PageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter the name of policy provider or broker..
        /// </summary>
        public static string PensionAndInsurance_Summary_ProviderName_Error_Empty {
            get {
                return ResourceManager.GetString("PensionAndInsurance_Summary_ProviderName_Error_Empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Provider name must have at least 3 letters and it cannot be longer than 50 letters..
        /// </summary>
        public static string PensionAndInsurance_Summary_ProviderName_Error_InvalidLength {
            get {
                return ResourceManager.GetString("PensionAndInsurance_Summary_ProviderName_Error_InvalidLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to For example, ABC Insurance Ltd. You can add more providers later. For workplace pensions, you can enter the name of your employer..
        /// </summary>
        public static string PensionAndInsurance_Summary_ProviderName_Hint {
            get {
                return ResourceManager.GetString("PensionAndInsurance_Summary_ProviderName_Hint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter the name of your policy provider or broker.
        /// </summary>
        public static string PensionAndInsurance_Summary_ProviderName_Label {
            get {
                return ResourceManager.GetString("PensionAndInsurance_Summary_ProviderName_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Actions.
        /// </summary>
        public static string PensionAndInsurance_Summary_Table_Header_Actions {
            get {
                return ResourceManager.GetString("PensionAndInsurance_Summary_Table_Header_Actions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you don&apos;t want to add this pension provider?.
        /// </summary>
        public static string PensionInsurance_Summary_Continue_Error_WhenProviderNameTyped {
            get {
                return ResourceManager.GetString("PensionInsurance_Summary_Continue_Error_WhenProviderNameTyped", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Continue - I have added all my policies.
        /// </summary>
        public static string PensionInsurance_Summary_Continue_HasExistingPolicy_Label1 {
            get {
                return ResourceManager.GetString("PensionInsurance_Summary_Continue_HasExistingPolicy_Label1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Continue - I don&apos;t have a policy to add.
        /// </summary>
        public static string PensionInsurance_Summary_Continue_NoPolicy_Label {
            get {
                return ResourceManager.GetString("PensionInsurance_Summary_Continue_NoPolicy_Label", resourceCulture);
            }
        }
    }
}
