//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace INSS.ODS.Bankruptcy.API.Common.Resources.Personal {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ContactResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ContactResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("INSS.ODS.Bankruptcy.API.Common.Resources.Personal.ContactResources", typeof(ContactResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Residency details.
        /// </summary>
        public static string Current_Occupancy_PageTitle {
            get {
                return ResourceManager.GetString("Current_Occupancy_PageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address.
        /// </summary>
        public static string Personal_Contact_Address_Label {
            get {
                return ResourceManager.GetString("Personal_Contact_Address_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date you moved in?.
        /// </summary>
        public static string Personal_Contact_AddressWhenMovedIn_Label {
            get {
                return ResourceManager.GetString("Personal_Contact_AddressWhenMovedIn_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter your email address.
        /// </summary>
        public static string Personal_Contact_Email_Error_Empty {
            get {
                return ResourceManager.GetString("Personal_Contact_Email_Error_Empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email Address Is Invalid.
        /// </summary>
        public static string Personal_Contact_Email_Invalid_Error {
            get {
                return ResourceManager.GetString("Personal_Contact_Email_Invalid_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string Personal_Contact_Email_Label {
            get {
                return ResourceManager.GetString("Personal_Contact_Email_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We won&apos;t share this with anyone outside of the Insolvency Service and will only use it to contact you about your bankruptcy.
        /// </summary>
        public static string Personal_Contact_Mobile__Hint {
            get {
                return ResourceManager.GetString("Personal_Contact_Mobile__Hint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your Mobile number can only contain digits, spaces, brackets and the plus sign.
        /// </summary>
        public static string Personal_Contact_Mobile_Error_Format {
            get {
                return ResourceManager.GetString("Personal_Contact_Mobile_Error_Format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your Mobile number must have no more than 50 characters.
        /// </summary>
        public static string Personal_Contact_Mobile_Error_MaxLength {
            get {
                return ResourceManager.GetString("Personal_Contact_Mobile_Error_MaxLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The number you provide needs to be at least 10 digits long.
        /// </summary>
        public static string Personal_Contact_Mobile_Error_MinLength {
            get {
                return ResourceManager.GetString("Personal_Contact_Mobile_Error_MinLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mobile.
        /// </summary>
        public static string Personal_Contact_Mobile_Label {
            get {
                return ResourceManager.GetString("Personal_Contact_Mobile_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your contact details.
        /// </summary>
        public static string Personal_Contact_PageTitle {
            get {
                return ResourceManager.GetString("Personal_Contact_PageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search address.
        /// </summary>
        public static string Personal_Contact_Search_Address_Label {
            get {
                return ResourceManager.GetString("Personal_Contact_Search_Address_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your Telephone number can only contain digits, spaces, brackets and the plus sign.
        /// </summary>
        public static string Personal_Contact_Telephone_Error_Format {
            get {
                return ResourceManager.GetString("Personal_Contact_Telephone_Error_Format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your Telephone number must have no more than 50 characters.
        /// </summary>
        public static string Personal_Contact_Telephone_Error_MaxLength {
            get {
                return ResourceManager.GetString("Personal_Contact_Telephone_Error_MaxLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The number you provide needs to be at least 10 digits long.
        /// </summary>
        public static string Personal_Contact_Telephone_Error_MinLength {
            get {
                return ResourceManager.GetString("Personal_Contact_Telephone_Error_MinLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Telephone.
        /// </summary>
        public static string Personal_Contact_Telephone_Label {
            get {
                return ResourceManager.GetString("Personal_Contact_Telephone_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter either a Telephone or a Mobile Number.
        /// </summary>
        public static string Personal_Contact_TelephoneOrMobile_Error_Required {
            get {
                return ResourceManager.GetString("Personal_Contact_TelephoneOrMobile_Error_Required", resourceCulture);
            }
        }
    }
}
