//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace INSS.ODS.Bankruptcy.API.Common.Resources.Personal {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class MovedInResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal MovedInResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("INSS.ODS.Bankruptcy.API.Common.Resources.Personal.MovedInResources", typeof(MovedInResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add person.
        /// </summary>
        public static string Personal_MovedIn_Add_FullName_Label {
            get {
                return ResourceManager.GetString("Personal_MovedIn_Add_FullName_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add another person.
        /// </summary>
        public static string Personal_MovedIn_Add_FullName_Label_Alt {
            get {
                return ResourceManager.GetString("Personal_MovedIn_Add_FullName_Label_Alt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Continue - I have added everyone who lives with me.
        /// </summary>
        public static string Personal_MovedIn_Continue_Added_Everyone_Label {
            get {
                return ResourceManager.GetString("Personal_MovedIn_Continue_Added_Everyone_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Continue - I live alone.
        /// </summary>
        public static string Personal_MovedIn_Continue_Live_Alone_Label {
            get {
                return ResourceManager.GetString("Personal_MovedIn_Continue_Live_Alone_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete this person?.
        /// </summary>
        public static string Personal_MovedIn_Delete_Confirmation_Message {
            get {
                return ResourceManager.GetString("Personal_MovedIn_Delete_Confirmation_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to For example, John Smith. You can add more people later..
        /// </summary>
        public static string Personal_MovedIn_FullName_Hint {
            get {
                return ResourceManager.GetString("Personal_MovedIn_FullName_Hint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter the person&apos;s name.
        /// </summary>
        public static string Personal_MovedIn_FullName_Label {
            get {
                return ResourceManager.GetString("Personal_MovedIn_FullName_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I live alone.
        /// </summary>
        public static string Personal_MovedIn_Household_Answer {
            get {
                return ResourceManager.GetString("Personal_MovedIn_Household_Answer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We need to know about anyone who lives with you at {0}, including children. .
        /// </summary>
        public static string Personal_MovedIn_Household_Hint {
            get {
                return ResourceManager.GetString("Personal_MovedIn_Household_Hint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This information will help us understand your household&apos;s likely expenses..
        /// </summary>
        public static string Personal_MovedIn_Household_Hint1 {
            get {
                return ResourceManager.GetString("Personal_MovedIn_Household_Hint1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your household.
        /// </summary>
        public static string Personal_MovedIn_Household_Label {
            get {
                return ResourceManager.GetString("Personal_MovedIn_Household_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to People who live with you.
        /// </summary>
        public static string Personal_MovedIn_Household_Question {
            get {
                return ResourceManager.GetString("Personal_MovedIn_Household_Question", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your current address.
        /// </summary>
        public static string Personal_MovedIn_PageTitle {
            get {
                return ResourceManager.GetString("Personal_MovedIn_PageTitle", resourceCulture);
            }
        }
    }
}
