//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace INSS.ODS.Bankruptcy.API.Common.Resources.Creditors {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AttachmentOfEarningsResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AttachmentOfEarningsResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("INSS.ODS.Bankruptcy.API.Common.Resources.Creditors.AttachmentOfEarningsResources", typeof(AttachmentOfEarningsResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to How much is deducted directly from your income to pay this debt?.
        /// </summary>
        public static string Creditors_AttachmentOfEarnings_AmountTaken_Label {
            get {
                return ResourceManager.GetString("Creditors_AttachmentOfEarnings_AmountTaken_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Amount taken should be greater then zero.
        /// </summary>
        public static string Creditors_AttachmentOfEarnings_AmountTaken_Min {
            get {
                return ResourceManager.GetString("Creditors_AttachmentOfEarnings_AmountTaken_Min", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter the amount taken.
        /// </summary>
        public static string Creditors_AttachmentOfEarnings_AmountTaken_Required {
            get {
                return ResourceManager.GetString("Creditors_AttachmentOfEarnings_AmountTaken_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please use the correct format, eg £120.50.
        /// </summary>
        public static string Creditors_AttachmentOfEarnings_AmountTaken_Scale {
            get {
                return ResourceManager.GetString("Creditors_AttachmentOfEarnings_AmountTaken_Scale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back.
        /// </summary>
        public static string Creditors_AttachmentOfEarnings_Back_Button {
            get {
                return ResourceManager.GetString("Creditors_AttachmentOfEarnings_Back_Button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Continue.
        /// </summary>
        public static string Creditors_AttachmentOfEarnings_Continue_Button {
            get {
                return ResourceManager.GetString("Creditors_AttachmentOfEarnings_Continue_Button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to How often is this amount taken?.
        /// </summary>
        public static string Creditors_AttachmentOfEarnings_HowOften_Label {
            get {
                return ResourceManager.GetString("Creditors_AttachmentOfEarnings_HowOften_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please indicate how often this amount is taken.
        /// </summary>
        public static string Creditors_AttachmentOfEarnings_HowOften_Required {
            get {
                return ResourceManager.GetString("Creditors_AttachmentOfEarnings_HowOften_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Every week.
        /// </summary>
        public static string Creditors_AttachmentOfEarnings_HowOften_Value1 {
            get {
                return ResourceManager.GetString("Creditors_AttachmentOfEarnings_HowOften_Value1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Every two weeks.
        /// </summary>
        public static string Creditors_AttachmentOfEarnings_HowOften_Value2 {
            get {
                return ResourceManager.GetString("Creditors_AttachmentOfEarnings_HowOften_Value2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Every four weeks.
        /// </summary>
        public static string Creditors_AttachmentOfEarnings_HowOften_Value3 {
            get {
                return ResourceManager.GetString("Creditors_AttachmentOfEarnings_HowOften_Value3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Every month.
        /// </summary>
        public static string Creditors_AttachmentOfEarnings_HowOften_Value4 {
            get {
                return ResourceManager.GetString("Creditors_AttachmentOfEarnings_HowOften_Value4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Every three months.
        /// </summary>
        public static string Creditors_AttachmentOfEarnings_HowOften_Value5 {
            get {
                return ResourceManager.GetString("Creditors_AttachmentOfEarnings_HowOften_Value5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Every year.
        /// </summary>
        public static string Creditors_AttachmentOfEarnings_HowOften_Value6 {
            get {
                return ResourceManager.GetString("Creditors_AttachmentOfEarnings_HowOften_Value6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attachment of earnings details.
        /// </summary>
        public static string Creditors_AttachmentOfEarnings_PageTitle {
            get {
                return ResourceManager.GetString("Creditors_AttachmentOfEarnings_PageTitle", resourceCulture);
            }
        }
    }
}
