//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace INSS.ODS.Bankruptcy.API.Common.Resources.Creditors {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class DebtDetailsResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal DebtDetailsResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("INSS.ODS.Bankruptcy.API.Common.Resources.Creditors.DebtDetailsResources", typeof(DebtDetailsResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attachment of earnings cannot be yes if there are seized or sold assets.
        /// </summary>
        public static string Creditors_DebtDetails_AttachmentOfEarnings_Error {
            get {
                return ResourceManager.GetString("Creditors_DebtDetails_AttachmentOfEarnings_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Does {0} currently have an attachment of earnings against you?.
        /// </summary>
        public static string Creditors_DebtDetails_AttachmentOfEarnings_Label {
            get {
                return ResourceManager.GetString("Creditors_DebtDetails_AttachmentOfEarnings_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please indicate if you have any attachment of earnings.
        /// </summary>
        public static string Creditors_DebtDetails_AttachmentOfEarnings_Required {
            get {
                return ResourceManager.GetString("Creditors_DebtDetails_AttachmentOfEarnings_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back.
        /// </summary>
        public static string Creditors_DebtDetails_BackButton_Label {
            get {
                return ResourceManager.GetString("Creditors_DebtDetails_BackButton_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Continue.
        /// </summary>
        public static string Creditors_DebtDetails_ContinueButton_Label {
            get {
                return ResourceManager.GetString("Creditors_DebtDetails_ContinueButton_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select the date range you took out the credit card.
        /// </summary>
        public static string Creditors_DebtDetails_CreditCard_DateStarted_Label {
            get {
                return ResourceManager.GetString("Creditors_DebtDetails_CreditCard_DateStarted_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to When did the debt start?.
        /// </summary>
        public static string Creditors_DebtDetails_Date_Started_Label {
            get {
                return ResourceManager.GetString("Creditors_DebtDetails_Date_Started_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0 to 6 months ago.
        /// </summary>
        public static string Creditors_DebtDetails_DateStarted_0To6MonthsAgo {
            get {
                return ResourceManager.GetString("Creditors_DebtDetails_DateStarted_0To6MonthsAgo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1 to 2 years ago.
        /// </summary>
        public static string Creditors_DebtDetails_DateStarted_1To2YearsAgo {
            get {
                return ResourceManager.GetString("Creditors_DebtDetails_DateStarted_1To2YearsAgo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 3 to 5 years ago.
        /// </summary>
        public static string Creditors_DebtDetails_DateStarted_3To5YearsAgo {
            get {
                return ResourceManager.GetString("Creditors_DebtDetails_DateStarted_3To5YearsAgo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 6 to 10 years ago.
        /// </summary>
        public static string Creditors_DebtDetails_DateStarted_6To10YearsAgo {
            get {
                return ResourceManager.GetString("Creditors_DebtDetails_DateStarted_6To10YearsAgo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 7 to 12 months ago.
        /// </summary>
        public static string Creditors_DebtDetails_DateStarted_7To12MonthsAgo {
            get {
                return ResourceManager.GetString("Creditors_DebtDetails_DateStarted_7To12MonthsAgo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter the date you took out the credit card.
        /// </summary>
        public static string Creditors_DebtDetails_DateStarted_CreditCard_Hint {
            get {
                return ResourceManager.GetString("Creditors_DebtDetails_DateStarted_CreditCard_Hint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter the date the fine was issued.
        /// </summary>
        public static string Creditors_DebtDetails_DateStarted_Fine_Hint {
            get {
                return ResourceManager.GetString("Creditors_DebtDetails_DateStarted_Fine_Hint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Over 10 years ago.
        /// </summary>
        public static string Creditors_DebtDetails_DateStarted_Over10YearsAgo {
            get {
                return ResourceManager.GetString("Creditors_DebtDetails_DateStarted_Over10YearsAgo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter the first date you didn&apos;t pay the full bill.
        /// </summary>
        public static string Creditors_DebtDetails_DateStarted_Utility_Hint {
            get {
                return ResourceManager.GetString("Creditors_DebtDetails_DateStarted_Utility_Hint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Debt repayment or consolidation.
        /// </summary>
        public static string Creditors_DebtDetails_DebtRepayment_Label {
            get {
                return ResourceManager.GetString("Creditors_DebtDetails_DebtRepayment_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select date range the fine was issued.
        /// </summary>
        public static string Creditors_DebtDetails_Fines_DateStarted_Label {
            get {
                return ResourceManager.GetString("Creditors_DebtDetails_Fines_DateStarted_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gambling.
        /// </summary>
        public static string Creditors_DebtDetails_Gambling_Label {
            get {
                return ResourceManager.GetString("Creditors_DebtDetails_Gambling_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Holidays.
        /// </summary>
        public static string Creditors_DebtDetails_Holidays_Label {
            get {
                return ResourceManager.GetString("Creditors_DebtDetails_Holidays_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home improvements.
        /// </summary>
        public static string Creditors_DebtDetails_HomeImprovements_Label {
            get {
                return ResourceManager.GetString("Creditors_DebtDetails_HomeImprovements_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Household bills/living expenses.
        /// </summary>
        public static string Creditors_DebtDetails_HouseholdBills_Label {
            get {
                return ResourceManager.GetString("Creditors_DebtDetails_HouseholdBills_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select date range you first stopped making payments.
        /// </summary>
        public static string Creditors_DebtDetails_Other_DateStarted_Label {
            get {
                return ResourceManager.GetString("Creditors_DebtDetails_Other_DateStarted_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Other.
        /// </summary>
        public static string Creditors_DebtDetails_Other_Label {
            get {
                return ResourceManager.GetString("Creditors_DebtDetails_Other_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Debt details.
        /// </summary>
        public static string Creditors_DebtDetails_Page_Title {
            get {
                return ResourceManager.GetString("Creditors_DebtDetails_Page_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payments or gifts to family/friends.
        /// </summary>
        public static string Creditors_DebtDetails_PaymentsToFamily_Label {
            get {
                return ResourceManager.GetString("Creditors_DebtDetails_PaymentsToFamily_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select the date range you received the loan.
        /// </summary>
        public static string Creditors_DebtDetails_PersonalLoan_DateStarted_Label {
            get {
                return ResourceManager.GetString("Creditors_DebtDetails_PersonalLoan_DateStarted_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select a reason.
        /// </summary>
        public static string Creditors_DebtDetails_Reason_Error_Mandatory {
            get {
                return ResourceManager.GetString("Creditors_DebtDetails_Reason_Error_Mandatory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have entered text for the Other option, but you have not selected it..
        /// </summary>
        public static string Creditors_DebtDetails_Reason_Error_OtherText {
            get {
                return ResourceManager.GetString("Creditors_DebtDetails_Reason_Error_OtherText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You select other but have not entered the other text.
        /// </summary>
        public static string Creditors_DebtDetails_Reason_OtherText_NoOther {
            get {
                return ResourceManager.GetString("Creditors_DebtDetails_Reason_OtherText_NoOther", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tick all that apply.
        /// </summary>
        public static string Creditors_DebtDetails_ReasonForDebt_Hint {
            get {
                return ResourceManager.GetString("Creditors_DebtDetails_ReasonForDebt_Hint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reason for the debt.
        /// </summary>
        public static string Creditors_DebtDetails_ReasonForDebt_Label {
            get {
                return ResourceManager.GetString("Creditors_DebtDetails_ReasonForDebt_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please tell us which was the most recent action.
        /// </summary>
        public static string Creditors_DebtDetails_Recent_Action_Error {
            get {
                return ResourceManager.GetString("Creditors_DebtDetails_Recent_Action_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In the last 6 months, has {0} taken or sold any of your assets (including via a bailiff or enforcement officer)?.
        /// </summary>
        public static string Creditors_DebtDetails_SeizedAssets_Label {
            get {
                return ResourceManager.GetString("Creditors_DebtDetails_SeizedAssets_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seized or sold assets cannot be yes if there are attachment of earnings.
        /// </summary>
        public static string Creditors_DebtDetails_SeizedOrSoldAssets_Error {
            get {
                return ResourceManager.GetString("Creditors_DebtDetails_SeizedOrSoldAssets_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please indicate if any assets were sold or seized.
        /// </summary>
        public static string Creditors_DebtDetails_SeizedOrSoldAssets_Required {
            get {
                return ResourceManager.GetString("Creditors_DebtDetails_SeizedOrSoldAssets_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter the approximate period when this debt began.
        /// </summary>
        public static string Creditors_DebtDetails_StartDate_Error_Mandatory {
            get {
                return ResourceManager.GetString("Creditors_DebtDetails_StartDate_Error_Mandatory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter a date that isn&apos;t in the future.
        /// </summary>
        public static string Creditors_DebtDetails_StartDate_Error_MaxValue {
            get {
                return ResourceManager.GetString("Creditors_DebtDetails_StartDate_Error_MaxValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The date the debt began must be after 1900.
        /// </summary>
        public static string Creditors_DebtDetails_StartDate_Error_MinValue {
            get {
                return ResourceManager.GetString("Creditors_DebtDetails_StartDate_Error_MinValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select the date range you received the money.
        /// </summary>
        public static string Creditors_DebtDetails_StudentLoan_DateStarted_Label {
            get {
                return ResourceManager.GetString("Creditors_DebtDetails_StudentLoan_DateStarted_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trading expenses.
        /// </summary>
        public static string Creditors_DebtDetails_TradingExpenses_Label {
            get {
                return ResourceManager.GetString("Creditors_DebtDetails_TradingExpenses_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select the date range you didn&apos;t pay the full bill.
        /// </summary>
        public static string Creditors_DebtDetails_Utilities_DateStarted_Label {
            get {
                return ResourceManager.GetString("Creditors_DebtDetails_Utilities_DateStarted_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vehicle purchase.
        /// </summary>
        public static string Creditors_DebtDetails_VehiclePurchase_Label {
            get {
                return ResourceManager.GetString("Creditors_DebtDetails_VehiclePurchase_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wedding.
        /// </summary>
        public static string Creditors_DebtDetails_Wedding_Label {
            get {
                return ResourceManager.GetString("Creditors_DebtDetails_Wedding_Label", resourceCulture);
            }
        }
    }
}
