//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace INSS.ODS.Bankruptcy.API.Common.Resources.Creditors {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ReasonForDebtResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ReasonForDebtResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("INSS.ODS.Bankruptcy.API.Common.Resources.Creditors.ReasonForDebtResources", typeof(ReasonForDebtResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back.
        /// </summary>
        public static string Creditors_ReasonForDebt_BackButton_Label {
            get {
                return ResourceManager.GetString("Creditors_ReasonForDebt_BackButton_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Debt repayment or consolidation.
        /// </summary>
        public static string Creditors_ReasonForDebt_DebtRepayment_Label {
            get {
                return ResourceManager.GetString("Creditors_ReasonForDebt_DebtRepayment_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gambling.
        /// </summary>
        public static string Creditors_ReasonForDebt_Gambling_Label {
            get {
                return ResourceManager.GetString("Creditors_ReasonForDebt_Gambling_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Holidays.
        /// </summary>
        public static string Creditors_ReasonForDebt_Holidays_Label {
            get {
                return ResourceManager.GetString("Creditors_ReasonForDebt_Holidays_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home improvements.
        /// </summary>
        public static string Creditors_ReasonForDebt_HomeImprovements_Label {
            get {
                return ResourceManager.GetString("Creditors_ReasonForDebt_HomeImprovements_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Household bills/living expenses.
        /// </summary>
        public static string Creditors_ReasonForDebt_HouseholdBills_Label {
            get {
                return ResourceManager.GetString("Creditors_ReasonForDebt_HouseholdBills_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Other.
        /// </summary>
        public static string Creditors_ReasonForDebt_Other_Label {
            get {
                return ResourceManager.GetString("Creditors_ReasonForDebt_Other_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reason for the debt.
        /// </summary>
        public static string Creditors_ReasonForDebt_Page_Title {
            get {
                return ResourceManager.GetString("Creditors_ReasonForDebt_Page_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payments or gifts to family/friends.
        /// </summary>
        public static string Creditors_ReasonForDebt_PaymentsToFamily_Label {
            get {
                return ResourceManager.GetString("Creditors_ReasonForDebt_PaymentsToFamily_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select a reason.
        /// </summary>
        public static string Creditors_ReasonForDebt_Reason_Error_Mandatory {
            get {
                return ResourceManager.GetString("Creditors_ReasonForDebt_Reason_Error_Mandatory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter a value that is no more than 50 characters in length.
        /// </summary>
        public static string Creditors_ReasonForDebt_Reason_Error_Other_MaxLength {
            get {
                return ResourceManager.GetString("Creditors_ReasonForDebt_Reason_Error_Other_MaxLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter at least 3 characters.
        /// </summary>
        public static string Creditors_ReasonForDebt_Reason_Error_Other_MinLength {
            get {
                return ResourceManager.GetString("Creditors_ReasonForDebt_Reason_Error_Other_MinLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have entered text for the Other option, but you have not selected it..
        /// </summary>
        public static string Creditors_ReasonForDebt_Reason_Error_OtherText {
            get {
                return ResourceManager.GetString("Creditors_ReasonForDebt_Reason_Error_OtherText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string Creditors_ReasonForDebt_Reason_Label {
            get {
                return ResourceManager.GetString("Creditors_ReasonForDebt_Reason_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trading expenses.
        /// </summary>
        public static string Creditors_ReasonForDebt_TradingExpenses_Label {
            get {
                return ResourceManager.GetString("Creditors_ReasonForDebt_TradingExpenses_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vehicle purchase.
        /// </summary>
        public static string Creditors_ReasonForDebt_VehiclePurchase_Label {
            get {
                return ResourceManager.GetString("Creditors_ReasonForDebt_VehiclePurchase_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wedding.
        /// </summary>
        public static string Creditors_ReasonForDebt_Wedding_Label {
            get {
                return ResourceManager.GetString("Creditors_ReasonForDebt_Wedding_Label", resourceCulture);
            }
        }
    }
}
