//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace INSS.ODS.Bankruptcy.API.Common.Resources.Creditors {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class SeizedAndSoldAssetsResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SeizedAndSoldAssetsResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("INSS.ODS.Bankruptcy.API.Common.Resources.Creditors.SeizedAndSoldAssetsResources", typeof(SeizedAndSoldAssetsResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add another item.
        /// </summary>
        public static string Creditors_SiezedAndSoldAssetsResources_Add_Another_Item_Label {
            get {
                return ResourceManager.GetString("Creditors_SiezedAndSoldAssetsResources_Add_Another_Item_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Continue.
        /// </summary>
        public static string Creditors_SiezedAndSoldAssetsResources_Continue_Label {
            get {
                return ResourceManager.GetString("Creditors_SiezedAndSoldAssetsResources_Continue_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string Creditors_SiezedAndSoldAssetsResources_Delete_Label {
            get {
                return ResourceManager.GetString("Creditors_SiezedAndSoldAssetsResources_Delete_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select if the item is jointly owned.
        /// </summary>
        public static string Creditors_SiezedAndSoldAssetsResources_Item_Jointly_Owned_Required {
            get {
                return ResourceManager.GetString("Creditors_SiezedAndSoldAssetsResources_Item_Jointly_Owned_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What&apos;s the item?.
        /// </summary>
        public static string Creditors_SiezedAndSoldAssetsResources_Item_Label {
            get {
                return ResourceManager.GetString("Creditors_SiezedAndSoldAssetsResources_Item_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter an item with length between 3 and 100 characters.
        /// </summary>
        public static string Creditors_SiezedAndSoldAssetsResources_Item_Length {
            get {
                return ResourceManager.GetString("Creditors_SiezedAndSoldAssetsResources_Item_Length", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter a value that is no more than 100 characters in length.
        /// </summary>
        public static string Creditors_SiezedAndSoldAssetsResources_Item_MaxLength {
            get {
                return ResourceManager.GetString("Creditors_SiezedAndSoldAssetsResources_Item_MaxLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter at least 2 characters.
        /// </summary>
        public static string Creditors_SiezedAndSoldAssetsResources_Item_MinLength {
            get {
                return ResourceManager.GetString("Creditors_SiezedAndSoldAssetsResources_Item_MinLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter the item.
        /// </summary>
        public static string Creditors_SiezedAndSoldAssetsResources_Item_Required {
            get {
                return ResourceManager.GetString("Creditors_SiezedAndSoldAssetsResources_Item_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Has the item been sold?.
        /// </summary>
        public static string Creditors_SiezedAndSoldAssetsResources_Item_Sold_Label {
            get {
                return ResourceManager.GetString("Creditors_SiezedAndSoldAssetsResources_Item_Sold_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select if the item is sold.
        /// </summary>
        public static string Creditors_SiezedAndSoldAssetsResources_Item_Sold_Required {
            get {
                return ResourceManager.GetString("Creditors_SiezedAndSoldAssetsResources_Item_Sold_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter a value greater than zero.
        /// </summary>
        public static string Creditors_SiezedAndSoldAssetsResources_Item_Worth_Error_MinValue {
            get {
                return ResourceManager.GetString("Creditors_SiezedAndSoldAssetsResources_Item_Worth_Error_MinValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please use the correct format, eg £120.50.
        /// </summary>
        public static string Creditors_SiezedAndSoldAssetsResources_Item_Worth_Error_Scale {
            get {
                return ResourceManager.GetString("Creditors_SiezedAndSoldAssetsResources_Item_Worth_Error_Scale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to How much was it worth when it was taken?.
        /// </summary>
        public static string Creditors_SiezedAndSoldAssetsResources_Item_Worth_Label {
            get {
                return ResourceManager.GetString("Creditors_SiezedAndSoldAssetsResources_Item_Worth_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter how much the item is worth.
        /// </summary>
        public static string Creditors_SiezedAndSoldAssetsResources_Item_Worth_Required {
            get {
                return ResourceManager.GetString("Creditors_SiezedAndSoldAssetsResources_Item_Worth_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to asset.
        /// </summary>
        public static string Creditors_SiezedAndSoldAssetsResources_ItemSold_Delete_Message {
            get {
                return ResourceManager.GetString("Creditors_SiezedAndSoldAssetsResources_ItemSold_Delete_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        public static string Creditors_SiezedAndSoldAssetsResources_ItemSold_No_Label {
            get {
                return ResourceManager.GetString("Creditors_SiezedAndSoldAssetsResources_ItemSold_No_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        public static string Creditors_SiezedAndSoldAssetsResources_ItemSold_Yes_Label {
            get {
                return ResourceManager.GetString("Creditors_SiezedAndSoldAssetsResources_ItemSold_Yes_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is it jointly owned?.
        /// </summary>
        public static string Creditors_SiezedAndSoldAssetsResources_Jointly_Owned_Label {
            get {
                return ResourceManager.GetString("Creditors_SiezedAndSoldAssetsResources_Jointly_Owned_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Asset description.
        /// </summary>
        public static string Creditors_SiezedAndSoldAssetsResources_PageTitle {
            get {
                return ResourceManager.GetString("Creditors_SiezedAndSoldAssetsResources_PageTitle", resourceCulture);
            }
        }
    }
}
