//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace INSS.ODS.Bankruptcy.API.Common.Resources.Creditors {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class StartResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal StartResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("INSS.ODS.Bankruptcy.API.Common.Resources.Creditors.StartResources", typeof(StartResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Continue - I have added all creditors.
        /// </summary>
        public static string Creditors_Start_ContinueButton_Label {
            get {
                return ResourceManager.GetString("Creditors_Start_ContinueButton_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter your creditor&apos;s name.
        /// </summary>
        public static string Creditors_Start_CreditorName_Error_Mandatory {
            get {
                return ResourceManager.GetString("Creditors_Start_CreditorName_Error_Mandatory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to For example, ABC Bank Ltd or John Smith. You can add more creditors later..
        /// </summary>
        public static string Creditors_Start_CreditorName_Hint {
            get {
                return ResourceManager.GetString("Creditors_Start_CreditorName_Hint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter a creditor&apos;s name.
        /// </summary>
        public static string Creditors_Start_CreditorName_Label {
            get {
                return ResourceManager.GetString("Creditors_Start_CreditorName_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to creditor.
        /// </summary>
        public static string Creditors_Start_DeleteConfirmation_ItemName {
            get {
                return ResourceManager.GetString("Creditors_Start_DeleteConfirmation_ItemName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Organisations and people you owe money to are known as creditors..
        /// </summary>
        public static string Creditors_Start_IntroText_1 {
            get {
                return ResourceManager.GetString("Creditors_Start_IntroText_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We need to know about all of your creditors, including family members or friends..
        /// </summary>
        public static string Creditors_Start_IntroText_2 {
            get {
                return ResourceManager.GetString("Creditors_Start_IntroText_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If you have multiple debts with one creditor, please tell us about each one separately..
        /// </summary>
        public static string Creditors_Start_IntroText_3 {
            get {
                return ResourceManager.GetString("Creditors_Start_IntroText_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Money you owe.
        /// </summary>
        public static string Creditors_Start_Page_Title {
            get {
                return ResourceManager.GetString("Creditors_Start_Page_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add creditor.
        /// </summary>
        public static string Creditors_Start_Search_Label {
            get {
                return ResourceManager.GetString("Creditors_Start_Search_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add another creditor.
        /// </summary>
        public static string Creditors_Start_Search_Label_Alt {
            get {
                return ResourceManager.GetString("Creditors_Start_Search_Label_Alt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your search returned no results..
        /// </summary>
        public static string Creditors_Start_Search_NoResults {
            get {
                return ResourceManager.GetString("Creditors_Start_Search_NoResults", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Amount.
        /// </summary>
        public static string Creditors_Start_Table_Amount {
            get {
                return ResourceManager.GetString("Creditors_Start_Table_Amount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Debt Started.
        /// </summary>
        public static string Creditors_Start_Table_DebtStarted {
            get {
                return ResourceManager.GetString("Creditors_Start_Table_DebtStarted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string Creditors_Start_Table_Name {
            get {
                return ResourceManager.GetString("Creditors_Start_Table_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reference.
        /// </summary>
        public static string Creditors_Start_Table_Reference {
            get {
                return ResourceManager.GetString("Creditors_Start_Table_Reference", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total.
        /// </summary>
        public static string Creditors_Start_Table_TotalPrefix {
            get {
                return ResourceManager.GetString("Creditors_Start_Table_TotalPrefix", resourceCulture);
            }
        }
    }
}
