//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace INSS.ODS.Bankruptcy.API.Common.Resources.Expenses {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class SavingsFinesOtherCostsResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SavingsFinesOtherCostsResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("INSS.ODS.Bankruptcy.API.Common.Resources.Expenses.SavingsFinesOtherCostsResources", typeof(SavingsFinesOtherCostsResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fines.
        /// </summary>
        public static string Expenses_SavingsFinesOtherCosts_CourtFines_Label {
            get {
                return ResourceManager.GetString("Expenses_SavingsFinesOtherCosts_CourtFines_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Don&apos;t include County Court Judgements (CCJs) or Penalty Charge Notices (PCNs), for example parking fines from local councils..
        /// </summary>
        public static string Expenses_SavingsFinesOtherCosts_CourtFines_Label_Hint {
            get {
                return ResourceManager.GetString("Expenses_SavingsFinesOtherCosts_CourtFines_Label_Hint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter the type of expense.
        /// </summary>
        public static string Expenses_SavingsFinesOtherCosts_Expense_Type_Error_Empty {
            get {
                return ResourceManager.GetString("Expenses_SavingsFinesOtherCosts_Expense_Type_Error_Empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter the expense amount.
        /// </summary>
        public static string Expenses_SavingsFinesOtherCosts_Expense_Value_Error_Empty {
            get {
                return ResourceManager.GetString("Expenses_SavingsFinesOtherCosts_Expense_Value_Error_Empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter a value greater than or equal to zero.
        /// </summary>
        public static string Expenses_SavingsFinesOtherCosts_Expense_Value_Error_Negative {
            get {
                return ResourceManager.GetString("Expenses_SavingsFinesOtherCosts_Expense_Value_Error_Negative", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please use the correct format, eg £120.50.
        /// </summary>
        public static string Expenses_SavingsFinesOtherCosts_Expense_Value_Error_Scale {
            get {
                return ResourceManager.GetString("Expenses_SavingsFinesOtherCosts_Expense_Value_Error_Scale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter who entered the fine.
        /// </summary>
        public static string Expenses_SavingsFinesOtherCosts_Fines_Type_Error_Empty {
            get {
                return ResourceManager.GetString("Expenses_SavingsFinesOtherCosts_Fines_Type_Error_Empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter the fine amount.
        /// </summary>
        public static string Expenses_SavingsFinesOtherCosts_Fines_Value_Error_Empty {
            get {
                return ResourceManager.GetString("Expenses_SavingsFinesOtherCosts_Fines_Value_Error_Empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter a value greater than or equal to zero.
        /// </summary>
        public static string Expenses_SavingsFinesOtherCosts_Fines_Value_Error_Negative {
            get {
                return ResourceManager.GetString("Expenses_SavingsFinesOtherCosts_Fines_Value_Error_Negative", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please use the correct format, eg £120.50.
        /// </summary>
        public static string Expenses_SavingsFinesOtherCosts_Fines_Value_Error_Scale {
            get {
                return ResourceManager.GetString("Expenses_SavingsFinesOtherCosts_Fines_Value_Error_Scale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add your regular savings, fines and other expenses..
        /// </summary>
        public static string Expenses_SavingsFinesOtherCosts_Page_Help1 {
            get {
                return ResourceManager.GetString("Expenses_SavingsFinesOtherCosts_Page_Help1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string Expenses_SavingsFinesOtherCosts_Page_Help2 {
            get {
                return ResourceManager.GetString("Expenses_SavingsFinesOtherCosts_Page_Help2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If you don&apos;t contribute towards something, leave it blank..
        /// </summary>
        public static string Expenses_SavingsFinesOtherCosts_Page_Help3 {
            get {
                return ResourceManager.GetString("Expenses_SavingsFinesOtherCosts_Page_Help3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Regular savings, fines and other costs.
        /// </summary>
        public static string Expenses_SavingsFinesOtherCosts_PageTitle {
            get {
                return ResourceManager.GetString("Expenses_SavingsFinesOtherCosts_PageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The amount you entered for fines is invalid.
        /// </summary>
        public static string Expenses_SavingsFinesOtherCosts_Positive_CourtFines_Label {
            get {
                return ResourceManager.GetString("Expenses_SavingsFinesOtherCosts_Positive_CourtFines_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The amount you entered for savings is invalid.
        /// </summary>
        public static string Expenses_SavingsFinesOtherCosts_Positive_Savings_Label {
            get {
                return ResourceManager.GetString("Expenses_SavingsFinesOtherCosts_Positive_Savings_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Savings.
        /// </summary>
        public static string Expenses_SavingsFinesOtherCosts_Savings_Label {
            get {
                return ResourceManager.GetString("Expenses_SavingsFinesOtherCosts_Savings_Label", resourceCulture);
            }
        }
    }
}
