//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace INSS.ODS.Bankruptcy.API.Common.Resources.SelfEmployment {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class SelfEmployedAdditionalBusinessDetailsResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SelfEmployedAdditionalBusinessDetailsResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("INSS.ODS.Bankruptcy.API.Common.Resources.SelfEmployment.SelfEmployedAdditionalBusinessDeta" +
                            "ilsResources", typeof(SelfEmployedAdditionalBusinessDetailsResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to At home address.
        /// </summary>
        public static string SelfEmployedAdditonalBusinessDetails_Home_Option {
            get {
                return ResourceManager.GetString("SelfEmployedAdditonalBusinessDetails_Home_Option", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Online.
        /// </summary>
        public static string SelfEmployedAdditonalBusinessDetails_Online_Option {
            get {
                return ResourceManager.GetString("SelfEmployedAdditonalBusinessDetails_Online_Option", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;&quot;.
        /// </summary>
        public static string SelfEmployedAdditonalBusinessDetails_RecordsLocation_Help {
            get {
                return ResourceManager.GetString("SelfEmployedAdditonalBusinessDetails_RecordsLocation_Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to For example receipts, invoices, employee records, etc.
        /// </summary>
        public static string SelfEmployedAdditonalBusinessDetails_RecordsLocation_Hint {
            get {
                return ResourceManager.GetString("SelfEmployedAdditonalBusinessDetails_RecordsLocation_Hint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;&quot;.
        /// </summary>
        public static string SelfEmployedAdditonalBusinessDetails_RecordsLocation_Invalid {
            get {
                return ResourceManager.GetString("SelfEmployedAdditonalBusinessDetails_RecordsLocation_Invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Where do you keep your business records?.
        /// </summary>
        public static string SelfEmployedAdditonalBusinessDetails_RecordsLocation_Label {
            get {
                return ResourceManager.GetString("SelfEmployedAdditonalBusinessDetails_RecordsLocation_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;&quot;.
        /// </summary>
        public static string SelfEmployedAdditonalBusinessDetails_RecordsLocation_Length {
            get {
                return ResourceManager.GetString("SelfEmployedAdditonalBusinessDetails_RecordsLocation_Length", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select where you keep your business records.
        /// </summary>
        public static string SelfEmployedAdditonalBusinessDetails_RecordsLocation_Required {
            get {
                return ResourceManager.GetString("SelfEmployedAdditonalBusinessDetails_RecordsLocation_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Additional business details.
        /// </summary>
        public static string SelfEmployedAdditonalBusinessDetails_Title {
            get {
                return ResourceManager.GetString("SelfEmployedAdditonalBusinessDetails_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to At trading address.
        /// </summary>
        public static string SelfEmployedAdditonalBusinessDetails_Trading_Address_Option {
            get {
                return ResourceManager.GetString("SelfEmployedAdditonalBusinessDetails_Trading_Address_Option", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;&quot;.
        /// </summary>
        public static string SelfEmployedAdditonalBusinessDetails_UTR_Help {
            get {
                return ResourceManager.GetString("SelfEmployedAdditonalBusinessDetails_UTR_Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can find this on your P60, tax return or statement of account from HMRC.
        /// </summary>
        public static string SelfEmployedAdditonalBusinessDetails_UTR_Hint {
            get {
                return ResourceManager.GetString("SelfEmployedAdditonalBusinessDetails_UTR_Hint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;&quot;.
        /// </summary>
        public static string SelfEmployedAdditonalBusinessDetails_UTR_Invalid {
            get {
                return ResourceManager.GetString("SelfEmployedAdditonalBusinessDetails_UTR_Invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your current or last Income Tax reference number or Unique Taxpayer Reference.
        /// </summary>
        public static string SelfEmployedAdditonalBusinessDetails_UTR_Label {
            get {
                return ResourceManager.GetString("SelfEmployedAdditonalBusinessDetails_UTR_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your Income Tax reference number of Unique Taxpayer Reference must be between 1 and  15 characters long.
        /// </summary>
        public static string SelfEmployedAdditonalBusinessDetails_UTR_Length {
            get {
                return ResourceManager.GetString("SelfEmployedAdditonalBusinessDetails_UTR_Length", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter your Income Tax reference number or Unique Taxpayer Reference.
        /// </summary>
        public static string SelfEmployedAdditonalBusinessDetails_UTR_Required {
            get {
                return ResourceManager.GetString("SelfEmployedAdditonalBusinessDetails_UTR_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Leave blank if your business isn&apos;t VAT registered.
        /// </summary>
        public static string SelfEmployedAdditonalBusinessDetails_VATNumber_Help {
            get {
                return ResourceManager.GetString("SelfEmployedAdditonalBusinessDetails_VATNumber_Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;br&gt;Leave blank if your business isn&apos;t VAT registered&lt;br&gt; For example GB 551 6778 32.
        /// </summary>
        public static string SelfEmployedAdditonalBusinessDetails_VATNumber_Hint {
            get {
                return ResourceManager.GetString("SelfEmployedAdditonalBusinessDetails_VATNumber_Hint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please check the VAT number. Your answer must begin with GB, followed by 9 digits. For example - GB123456789, GB 123 4567 89.
        /// </summary>
        public static string SelfEmployedAdditonalBusinessDetails_VATNumber_Invalid {
            get {
                return ResourceManager.GetString("SelfEmployedAdditonalBusinessDetails_VATNumber_Invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VAT number.
        /// </summary>
        public static string SelfEmployedAdditonalBusinessDetails_VATNumber_Label {
            get {
                return ResourceManager.GetString("SelfEmployedAdditonalBusinessDetails_VATNumber_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The VAT number is too long. Please answer in less than 15 characters..
        /// </summary>
        public static string SelfEmployedAdditonalBusinessDetails_VATNumber_Length {
            get {
                return ResourceManager.GetString("SelfEmployedAdditonalBusinessDetails_VATNumber_Length", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;&quot;.
        /// </summary>
        public static string SelfEmployedAdditonalBusinessDetails_VATNumber_Required {
            get {
                return ResourceManager.GetString("SelfEmployedAdditonalBusinessDetails_VATNumber_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to With current accountant.
        /// </summary>
        public static string SelfEmployedAdditonalBusinessDetails_With_Current_Accountant_Option {
            get {
                return ResourceManager.GetString("SelfEmployedAdditonalBusinessDetails_With_Current_Accountant_Option", resourceCulture);
            }
        }
    }
}
