//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace INSS.ODS.Bankruptcy.API.Common.Resources.Debt {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class DebtPreferentialPaymentsResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal DebtPreferentialPaymentsResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("INSS.ODS.Bankruptcy.API.Common.Resources.Debt.DebtPreferentialPaymentsResources", typeof(DebtPreferentialPaymentsResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter the name of another creditor you made a preferential payment to.
        /// </summary>
        public static string Debt_DebtPreferentialPayments_AddAnotherCreditorName_Label {
            get {
                return ResourceManager.GetString("Debt_DebtPreferentialPayments_AddAnotherCreditorName_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add creditor.
        /// </summary>
        public static string Debt_DebtPreferentialPayments_AddPreferredCreditorButton_Label {
            get {
                return ResourceManager.GetString("Debt_DebtPreferentialPayments_AddPreferredCreditorButton_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add another creditor.
        /// </summary>
        public static string Debt_DebtPreferentialPayments_AddPreferredCreditorButton_Label_Alt {
            get {
                return ResourceManager.GetString("Debt_DebtPreferentialPayments_AddPreferredCreditorButton_Label_Alt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to For example, ABC Bank Ltd or John Smith..
        /// </summary>
        public static string Debt_DebtPreferentialPayments_AnotherCreditorName_Hint {
            get {
                return ResourceManager.GetString("Debt_DebtPreferentialPayments_AnotherCreditorName_Hint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Continue - I have added all my relevant creditors.
        /// </summary>
        public static string Debt_DebtPreferentialPayments_ContinueAllRelevantCreditorsAddedButton_Label {
            get {
                return ResourceManager.GetString("Debt_DebtPreferentialPayments_ContinueAllRelevantCreditorsAddedButton_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Continue – I haven&apos;t made any preferential payments.
        /// </summary>
        public static string Debt_DebtPreferentialPayments_ContinueNoPreferentialPaymentsToAddButton_Label {
            get {
                return ResourceManager.GetString("Debt_DebtPreferentialPayments_ContinueNoPreferentialPaymentsToAddButton_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter the creditor&apos;s name.
        /// </summary>
        public static string Debt_DebtPreferentialPayments_CreditorName_Error_Empty {
            get {
                return ResourceManager.GetString("Debt_DebtPreferentialPayments_CreditorName_Error_Empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The creditor name is too long. Please answer in less than 51 characters..
        /// </summary>
        public static string Debt_DebtPreferentialPayments_CreditorName_Error_TooLong {
            get {
                return ResourceManager.GetString("Debt_DebtPreferentialPayments_CreditorName_Error_TooLong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The creditor name is too short. Please answer in more than 2 characters..
        /// </summary>
        public static string Debt_DebtPreferentialPayments_CreditorName_Error_TooShort {
            get {
                return ResourceManager.GetString("Debt_DebtPreferentialPayments_CreditorName_Error_TooShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to add the creditor you typed in below? To add this creditor, please select the green &apos;Add creditor&apos; button..
        /// </summary>
        public static string Debt_DebtPreferentialPayments_CreditorName_Error_WrongButtonPressed {
            get {
                return ResourceManager.GetString("Debt_DebtPreferentialPayments_CreditorName_Error_WrongButtonPressed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to For example, ABC Bank Ltd or John Smith.  You can add more creditors later..
        /// </summary>
        public static string Debt_DebtPreferentialPayments_CreditorName_Hint {
            get {
                return ResourceManager.GetString("Debt_DebtPreferentialPayments_CreditorName_Hint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter the name of a creditor you made a preferential payment to.
        /// </summary>
        public static string Debt_DebtPreferentialPayments_CreditorName_Label {
            get {
                return ResourceManager.GetString("Debt_DebtPreferentialPayments_CreditorName_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The table above summarises the preferential payments you have told us about..
        /// </summary>
        public static string Debt_DebtPreferentialPayments_Page_HasItems_ParagraphOne {
            get {
                return ResourceManager.GetString("Debt_DebtPreferentialPayments_Page_HasItems_ParagraphOne", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We need to know about any another preferential payments you have made in the last 2 years..
        /// </summary>
        public static string Debt_DebtPreferentialPayments_Page_HasItems_ParagraphTwo {
            get {
                return ResourceManager.GetString("Debt_DebtPreferentialPayments_Page_HasItems_ParagraphTwo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We need to know about any preferential payments you have made in the last 2 years..
        /// </summary>
        public static string Debt_DebtPreferentialPayments_Page_ParagraphOne {
            get {
                return ResourceManager.GetString("Debt_DebtPreferentialPayments_Page_ParagraphOne", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preferential payments.
        /// </summary>
        public static string Debt_DebtPreferentialPayments_Page_Title {
            get {
                return ResourceManager.GetString("Debt_DebtPreferentialPayments_Page_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to preferential payment.
        /// </summary>
        public static string Debt_DebtPreferentialPayments_PreferentialPayment_DeleteItem_Label {
            get {
                return ResourceManager.GetString("Debt_DebtPreferentialPayments_PreferentialPayment_DeleteItem_Label", resourceCulture);
            }
        }
    }
}
