//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace INSS.ODS.Bankruptcy.API.Common.Resources.Debt {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class PreferentialPaymentDetailsResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal PreferentialPaymentDetailsResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("INSS.ODS.Bankruptcy.API.Common.Resources.Debt.PreferentialPaymentDetailsResources", typeof(PreferentialPaymentDetailsResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The asset name is too long. Please answer in less than 61 characters.
        /// </summary>
        public static string Debt_PreferentialPaymentDetails_AssetName_Error_TooLong {
            get {
                return ResourceManager.GetString("Debt_PreferentialPaymentDetails_AssetName_Error_TooLong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The asset name is too short. Please answer in more than 1 characters.
        /// </summary>
        public static string Debt_PreferentialPaymentDetails_AssetName_Error_TooShort {
            get {
                return ResourceManager.GetString("Debt_PreferentialPaymentDetails_AssetName_Error_TooShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Leave blank if this doesn&apos;t apply.
        /// </summary>
        public static string Debt_PreferentialPaymentDetails_AssetName_Hint {
            get {
                return ResourceManager.GetString("Debt_PreferentialPaymentDetails_AssetName_Hint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If you gave them an asset, what was it?.
        /// </summary>
        public static string Debt_PreferentialPaymentDetails_AssetName_Label {
            get {
                return ResourceManager.GetString("Debt_PreferentialPaymentDetails_AssetName_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preferential payment details.
        /// </summary>
        public static string Debt_PreferentialPaymentDetails_Page_Title {
            get {
                return ResourceManager.GetString("Debt_PreferentialPaymentDetails_Page_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter the amount you paid the creditor.
        /// </summary>
        public static string Debt_PreferentialPaymentDetails_PaymentAmount_Error_Empty {
            get {
                return ResourceManager.GetString("Debt_PreferentialPaymentDetails_PaymentAmount_Error_Empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter a value greater than 0 for the payment amount.
        /// </summary>
        public static string Debt_PreferentialPaymentDetails_PaymentAmount_Error_InvalidValue {
            get {
                return ResourceManager.GetString("Debt_PreferentialPaymentDetails_PaymentAmount_Error_InvalidValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If you made multiple preferential payments to this creditor, enter the total amount you paid them. &lt;br/&gt;
        /// If you gave them any assets as payment (e.g. shares, vehicle, property), enter the total value of the item or items..
        /// </summary>
        public static string Debt_PreferentialPaymentDetails_PaymentAmount_Hint {
            get {
                return ResourceManager.GetString("Debt_PreferentialPaymentDetails_PaymentAmount_Hint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payment amount.
        /// </summary>
        public static string Debt_PreferentialPaymentDetails_PaymentAmount_Label {
            get {
                return ResourceManager.GetString("Debt_PreferentialPaymentDetails_PaymentAmount_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter the date you made the payment.
        /// </summary>
        public static string Debt_PreferentialPaymentDetails_PaymentDate_Error_Empty {
            get {
                return ResourceManager.GetString("Debt_PreferentialPaymentDetails_PaymentDate_Error_Empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payment date can&apos;t be in the future.
        /// </summary>
        public static string Debt_PreferentialPaymentDetails_PaymentDate_Error_InTheFuture {
            get {
                return ResourceManager.GetString("Debt_PreferentialPaymentDetails_PaymentDate_Error_InTheFuture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter a date that&apos;s after 01/01/1900.
        /// </summary>
        public static string Debt_PreferentialPaymentDetails_PaymentDate_Error_MinimumDate {
            get {
                return ResourceManager.GetString("Debt_PreferentialPaymentDetails_PaymentDate_Error_MinimumDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If you made multiple preferential payments to this creditor, 
        ///enter the date of the most recent one.
        /// </summary>
        public static string Debt_PreferentialPaymentDetails_PaymentDate_Hint {
            get {
                return ResourceManager.GetString("Debt_PreferentialPaymentDetails_PaymentDate_Hint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date you made the payment.
        /// </summary>
        public static string Debt_PreferentialPaymentDetails_PaymentDate_Label {
            get {
                return ResourceManager.GetString("Debt_PreferentialPaymentDetails_PaymentDate_Label", resourceCulture);
            }
        }
    }
}
