//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace INSS.ODS.Bankruptcy.API.Common.Resources.Assets {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AssetsResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AssetsResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("INSS.ODS.Bankruptcy.API.Common.Resources.Assets.AssetsResources", typeof(AssetsResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Don&apos;t include your basic State Pension. Do include your workplace pension even if you are a government employee..
        /// </summary>
        public static string Assets_Overview_Insurance_Hint {
            get {
                return ResourceManager.GetString("Assets_Overview_Insurance_Hint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you have any pension, endowment or life insurance policies?.
        /// </summary>
        public static string Assets_Overview_Insurance_Label {
            get {
                return ResourceManager.GetString("Assets_Overview_Insurance_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We need to know about all the assets you own or have a financial interest in.  This is to help us build a complete understanding of your financial situation..
        /// </summary>
        public static string Assets_Overview_Intro {
            get {
                return ResourceManager.GetString("Assets_Overview_Intro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to It’s important you be as thorough as you can when telling us about your assets..
        /// </summary>
        public static string Assets_Overview_Intro_2 {
            get {
                return ResourceManager.GetString("Assets_Overview_Intro_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We understand that mistakes can happen. If there are any questions, an Insolvency Service official will contact you discuss the information you provided. You are unlikely to be penalised for accidental omissions..
        /// </summary>
        public static string Assets_Overview_Intro_3 {
            get {
                return ResourceManager.GetString("Assets_Overview_Intro_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to However, it&apos;s a criminal offense to purposefully mislead the Insolvency Service about your assets, and those who do so can face legal action..
        /// </summary>
        public static string Assets_Overview_Intro_4 {
            get {
                return ResourceManager.GetString("Assets_Overview_Intro_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to For example cash, furniture, jewellery, tools etc.
        /// </summary>
        public static string Assets_Overview_OtherAssets_Hint {
            get {
                return ResourceManager.GetString("Assets_Overview_OtherAssets_Hint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We need to know about any other items you currently have.
        /// </summary>
        public static string Assets_Overview_OtherAssets_Label {
            get {
                return ResourceManager.GetString("Assets_Overview_OtherAssets_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assets.
        /// </summary>
        public static string Assets_Overview_PageTitle {
            get {
                return ResourceManager.GetString("Assets_Overview_PageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can have a beneficial interest in a property even if you don&apos;t legally own it
        ///&lt;p&gt;
        ///For example, if you have contributed towards buying or improving the property (mortgage payments, initial deposit, extensions, etc).
        /// </summary>
        public static string Assets_Overview_Property_Hint {
            get {
                return ResourceManager.GetString("Assets_Overview_Property_Hint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you own or have a financial interest in any properties?.
        /// </summary>
        public static string Assets_Overview_Property_Label {
            get {
                return ResourceManager.GetString("Assets_Overview_Property_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Include any vehicles you currently own &lt;p&gt;
        ///Include any vehicles you have sold or gotten rid of in the past 12 months.
        /// </summary>
        public static string Assets_Overview_Vehicle_Hint {
            get {
                return ResourceManager.GetString("Assets_Overview_Vehicle_Hint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Have you owned or regularly used any vehicles in the last 12 months?.
        /// </summary>
        public static string Assets_Overview_Vehicle_Label {
            get {
                return ResourceManager.GetString("Assets_Overview_Vehicle_Label", resourceCulture);
            }
        }
    }
}
